<?php
declare(strict_types=1);
header('X-Content-Type-Options: nosniff');
header('Referrer-Policy: strict-origin-when-cross-origin');
function mark(): string { return '<span class="brand-mark" aria-hidden="true"><i></i><i></i><i></i></span>'; }
?><!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>About AAB | Governed Scientific Intelligence</title>
<meta name="description" content="Discover how AAB preserves scientific evidence, uncertainty and learning to support governed, scientist-approved investigation across countries and scientific domains.">
<link rel="canonical" href="https://aab.ag/about/">
<meta property="og:type" content="website"><meta property="og:title" content="About AAB — Governed Scientific Intelligence"><meta property="og:description" content="A governed scientific memory and reasoning infrastructure designed to help countries preserve what their scientists learn."><meta property="og:url" content="https://aab.ag/about/">
<link rel="icon" href="/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/site.css"><link rel="stylesheet" href="/about/about.css"><script src="/site.js" defer></script>
<script type="application/ld+json">{"@context":"https://schema.org","@type":"AboutPage","name":"About AAB","url":"https://aab.ag/about/","description":"AAB is governed scientific intelligence infrastructure designed to preserve evidence, uncertainty, reasoning and learning while keeping scientists and authorised institutions in control.","mainEntity":{"@type":"Organization","name":"AAB","url":"https://aab.ag/"}}</script></head>
<body><main>
<header class="site-header"><a class="brand" href="/" aria-label="AAB home"><?=mark()?><span>AAB</span></a><button class="menu-toggle" data-menu-toggle aria-expanded="false">Menu</button><nav data-nav aria-label="Primary navigation"><a href="/about/" aria-current="page">About AAB</a><a href="/how-aab-works">How AAB Works</a><a href="/agriculture">Agriculture</a><a href="/countries">Countries</a><a href="/institutions-researchers">Institutions</a><a href="/governance-trust">Governance</a></nav><a class="header-action" href="/enter-aab">Enter AAB <span>↗</span></a></header>

<section class="about-hero" id="top"><div class="about-hero-copy"><p class="eyebrow"><span></span> About AAB</p><h1>Science should remember more than its conclusions.</h1><p class="about-hero-lead">AAB is being developed as governed scientific memory and reasoning infrastructure—helping countries connect evidence, uncertainty, failures, mechanisms and future questions without transferring authority away from scientists and authorised institutions.</p><div class="about-hero-actions"><a class="button primary" href="#experience">Experience AAB ↘</a><a class="button secondary" href="#governance">See the governance boundary</a></div></div><aside class="about-truth" aria-label="AAB at a glance"><small>AAB at a glance</small><div class="truth-row"><strong>Human-governed</strong><span>Scientists and authorised institutions approve real-world investigation and decisions.</span></div><div class="truth-row"><strong>Evidence-traceable</strong><span>Claims retain their sources, lineage, contradictions and uncertainty.</span></div><div class="truth-row"><strong>Built to learn</strong><span>Positive, negative and unresolved outcomes remain part of scientific memory.</span></div></aside></section>

<nav class="about-anchorbar" aria-label="About page sections"><a href="#purpose">Purpose</a><a href="#experience">The experience</a><a href="#opportunity">Country opportunity</a><a href="#governance">Governance</a></nav>

<section class="about-section about-intro" id="purpose"><p class="eyebrow dark"><span></span> The essential idea</p><div><h2>A country should never lose what its scientists learn.</h2><p class="about-lead">Scientific knowledge is often scattered across projects, institutions, reports and people. Final conclusions survive; the evidence trail, failed attempts, competing explanations and unanswered questions often do not. AAB is designed to preserve that complete learning chain so future teams can understand not only what is believed, but why.</p></div><aside class="about-side-note"><strong>What AAB is not</strong>AAB is not a regulator, laboratory, certification body or autonomous decision-maker. It does not make an untested material safe, turn a hypothesis into fact, or approve a formulation or Trial.</aside></section>

<section class="about-section about-animation" id="experience"><div class="about-animation-head"><div><p class="eyebrow"><span></span> The AAB story</p><h2>See how governed possibility becomes evidence, learning and national memory.</h2></div><p>This 23-part experience follows a country problem through resource investigation, scientific review, controlled trials, evidence preservation and cross-domain learning. It describes a governed pathway—not an automatic promise of outcomes.</p></div><div class="experience-shell"><div class="experience-toolbar"><span>Experience AAB</span><a href="/assets/pitch/aab-about-experience.html" target="_blank" rel="noopener">Open full presentation ↗</a></div><iframe class="experience-frame" src="/assets/pitch/aab-about-experience.html" title="The AAB governed scientific intelligence experience" loading="lazy" allow="fullscreen"></iframe></div></section>

<section class="about-section about-path" id="opportunity"><p class="eyebrow dark"><span></span> Country opportunity</p><h2>Better questions before bigger claims.</h2><p class="about-lead">AAB’s future Country Opportunity Register is intended to connect national problems, underused resources, scientific evidence, hazards, economics and governed investigation. A possible resource is never treated as automatically useful or safe.</p><div class="opportunity-flow"><article><span>01 · IDENTIFY</span><h3>Country problem</h3><p>Define the need, resource pressure or waste stream in its real geographic and institutional context.</p><small>OWNERSHIP + CONTEXT</small></article><article><span>02 · QUESTION</span><h3>Potential resource</h3><p>Assess availability, variability, competing uses, contaminants, processing and regulatory classification.</p><small>EVIDENCE + HAZARDS</small></article><article><span>03 · INVESTIGATE</span><h3>Scientist-approved Trial</h3><p>Authorised scientists decide whether a controlled investigation is justified and what evidence must be captured.</p><small>HUMAN AUTHORITY</small></article><article><span>04 · LEARN</span><h3>Outcome and memory</h3><p>Preserve positive, negative and uncertain results so future reasoning begins from what was actually learned.</p><small>TRACEABLE LINEAGE</small></article></div></section>

<section class="about-section about-governance" id="governance"><div class="governance-layout"><div class="authority-statement"><p class="eyebrow"><span></span> Authority boundary</p><h2>Governed. Never automatic.</h2><p>AAB can organise evidence, expose uncertainty, identify contradictions and propose questions worth investigation. It cannot award truth, approve regulated activity or replace accountable scientific judgement.</p><strong>Scientists remain the execution authority.</strong></div><div class="authority-grid"><article><span>01 · SCIENCE</span><h3>Scientists approve investigation</h3><p>Experimental candidates remain unverified until authorised, tested and reviewed against defined evidence requirements.</p></article><article><span>02 · INSTITUTIONS</span><h3>Institutions control participation</h3><p>Country, university, laboratory and research roles operate within explicit responsibility and data boundaries.</p></article><article><span>03 · REGULATION</span><h3>Regulators retain authority</h3><p>AAB may map evidence readiness and jurisdiction gaps. It never guarantees approval, certification or market access.</p></article><article><span>04 · MEMORY</span><h3>Uncertainty stays visible</h3><p>Missing data becomes a knowledge gap. Contradictions, failures and limitations are preserved rather than smoothed away.</p></article></div></div></section>

<section class="about-section stage-section"><p class="eyebrow dark"><span></span> Honest development position</p><h2>What exists now, and what must be established with partners.</h2><div class="stage-grid"><article class="stage-card"><small>Current foundation</small><h3>A governed digital platform in active development.</h3><ul><li>Scientific memory and evidence-lineage architecture</li><li>Agriculture as the first proving domain</li><li>Role-based country and institutional participation model</li><li>Human-authority and fail-closed governance boundaries</li></ul></article><article class="stage-card future"><small>Progressive establishment</small><h3>Country deployments grow through authorised collaboration.</h3><ul><li>Scientific and university partnerships</li><li>Physical Trial and laboratory networks</li><li>Country-specific data and regulatory pathways</li><li>Future water, environment and other scientific domains</li></ul></article></div></section>

<section class="about-section about-audience"><div class="audience-head"><p class="eyebrow"><span></span> Built for collaboration</p><h2>One governed foundation. Distinct responsibilities.</h2><p>AAB is intended to help trusted participants contribute without confusing access, evidence or authority.</p></div><div class="audience-grid"><article><span>GOVERNMENTS</span><h3>National continuity</h3><p>Preserve learning across programs, institutions and policy cycles while keeping national responsibilities explicit.</p></article><article><span>UNIVERSITIES + RESEARCH</span><h3>Traceable collaboration</h3><p>Connect evidence and questions across teams without erasing provenance, uncertainty or institutional ownership.</p></article><article><span>SCIENTISTS + REVIEWERS</span><h3>Reasoning with control</h3><p>Use structured intelligence to examine evidence and gaps while retaining approval and execution authority.</p></article></div></section>

<section class="about-cta"><div><p class="eyebrow dark"><span></span> Continue</p><h2>Explore the platform, or enter an authorised AAB workspace.</h2></div><div class="about-cta-actions"><a class="button primary" href="/how-aab-works">How AAB works ↗</a><a class="button outline-button" href="/enter-aab">Enter AAB ↗</a></div></section>

<footer><div class="footer-brand"><?=mark()?><div><strong>AAB</strong><p>Governed Scientific Intelligence Infrastructure</p></div></div><div class="footer-links"><a href="/about/">About</a><a href="/agriculture">Agriculture</a><a href="/governance-trust">Governance</a><a href="/enter-aab">Access</a></div><p class="copyright">© 2026 AAB. Research and systems development stage.</p></footer>
</main></body></html>
