/* eslint-disable */
/**
 * GENERATED FILE — DO NOT EDIT BY HAND.
 * Generated by json-schema-to-typescript from:
 *   src/schemas/cap-04/evidence-submission-request.schema.json
 *   src/schemas/cap-04/evidence-admission-decision.schema.json
 *   src/schemas/cap-04/evidence-admission-receipt.schema.json
 *   src/schemas/cap-04/evidence-admission-response.schema.json
 * To change these types, edit the schema(s) above, then run:
 *   npm run generate:types
 * npm test fails if this file differs from what the schemas generate.
 */

import type { ActorReference } from "./shared.js";

/**
 * SCS-CAP-04 ScsDeforestationEvidenceSubmissionRequest (contract 5c6a263). The system sets evidenceId, evidenceVersion, schemaVersion, plotVersion, evidenceRequirementSpecId (from the association), submittedBy, submittedAt, integrityStatus, intersectionWithPlot and the whole admission block. The claim vocabulary is DETECTED, never OCCURRED: an analysis cannot establish what occurred. Dates, geometry, integrity, the plot, association and parties are checked by the capability so that the contract's failure codes are returned.
 */
export interface ScsDeforestationEvidenceSubmissionRequest {
  plotId: string;
  frameworkAssociationId: string;
  evidenceType:
    | "SATELLITE_IMAGE"
    | "REMOTE_SENSING_ANALYSIS"
    | "LAND_COVER_DATA_PRODUCT"
    | "FORESTRY_AUTHORITY_CERTIFICATE"
    | "GOVERNMENT_RECORD"
    | "FIELD_VERIFICATION"
    | "EXPERT_ASSESSMENT"
    | "OTHER";
  source: ScsDeforestationEvidenceSource;
  evidenceObject: ScsDeforestationEvidenceObjectInput;
  spatialCoverage: ScsDeforestationSpatialCoverageInput;
  temporalCoverage: ScsDeforestationTemporalCoverage;
  analyticalMethod?: ScsAnalyticalMethod;
  evidenceClaim: ScsEvidenceClaim;
  coverageAttestation: ScsCoverageAttestation;
}
export interface ScsDeforestationEvidenceSource {
  sourceId: string;
  /**
   * An identifier issued outside SCS.
   */
  sourceOrganizationId: string;
  sourceTitle?: string;
  providerName?: string;
  productName?: string;
  productVersion?: string;
  sourceReference: string;
  issuingAuthority?: string;
}
export interface ScsDeforestationEvidenceObjectInput {
  /**
   * The SCS-PLATFORM-01 objectId of the stored file, when one is cited.
   */
  objectId?: string;
  originalObjectReference: string;
  /**
   * Lowercase hexadecimal SHA-256 of the file.
   */
  contentDigest: string;
  /**
   * As declared by the submitter.
   */
  chainOfCustodyComplete: boolean;
  /**
   * @maxItems 100
   */
  derivedFromEvidenceIds?: string[];
}
export interface ScsDeforestationSpatialCoverageInput {
  coverageGeometry: ScsCoverageGeometryInput;
  /**
   * Declared; not computed in the pilot.
   */
  plotCoveragePercent?: number;
  spatialResolutionMetres?: number;
  positionalAccuracyMetres?: number;
  /**
   * @maxItems 50
   */
  excludedAreas?: ScsExcludedAreaInput[];
}
export interface ScsCoverageGeometryInput {
  geometryType: "POINT" | "POLYGON" | "MULTIPOLYGON";
  /**
   * The GeoJSON (RFC 7946) coordinates member; validated by the capability.
   */
  coordinates: unknown[];
  /**
   * Must be EPSG:4326 (checked by the capability).
   */
  coordinateReferenceSystem: string;
}
export interface ScsExcludedAreaInput {
  geometry: ScsExcludedAreaGeometryInput;
  reason: string;
}
export interface ScsExcludedAreaGeometryInput {
  geometryType: "POINT" | "POLYGON" | "MULTIPOLYGON";
  /**
   * The GeoJSON (RFC 7946) coordinates member; validated by the capability.
   */
  coordinates: unknown[];
  /**
   * Must be EPSG:4326 (checked by the capability).
   */
  coordinateReferenceSystem: string;
}
export interface ScsDeforestationTemporalCoverage {
  acquisitionInstant?: string;
  acquisitionStart?: string;
  acquisitionEnd?: string;
  analysisPeriodStart?: string;
  analysisPeriodEnd?: string;
  attestedPeriodStart?: string;
  attestedPeriodEnd?: string;
  coverageMode:
    "POINT_IN_TIME" | "MULTIPLE_OBSERVATIONS" | "CONTINUOUS_MONITORING" | "CHANGE_ANALYSIS" | "AUTHORITY_ATTESTATION";
  /**
   * @maxItems 100
   */
  knownGapPeriods: ScsKnownGapPeriod[];
}
export interface ScsKnownGapPeriod {
  start: string;
  end: string;
  reason: "CLOUD_COVER" | "NO_ACQUISITION" | "SENSOR_LIMITATION" | "DATA_UNAVAILABLE" | "ANALYSIS_EXCLUDED" | "OTHER";
}
export interface ScsAnalyticalMethod {
  methodName: string;
  methodVersion?: string;
  /**
   * A registered SCS-CAP-02 partyId, not RETIRED.
   */
  analystOrganizationId?: string;
  /**
   * @maxItems 100
   */
  baselineEvidenceIds?: string[];
  /**
   * @maxItems 100
   */
  comparisonEvidenceIds?: string[];
  detectionTarget: "DEFORESTATION" | "FOREST_DEGRADATION" | "LAND_COVER_CHANGE" | "TREE_COVER_CHANGE" | "OTHER";
  minimumDetectableChange?: string;
  cloudCoverPercent?: number;
  qualityStatus: "ACCEPTABLE" | "LIMITED" | "UNASSESSED";
}
export interface ScsEvidenceClaim {
  /**
   * Claim vocabulary: DETECTED, never OCCURRED.
   */
  claimType:
    | "NO_DEFORESTATION_DETECTED"
    | "POSSIBLE_DEFORESTATION_DETECTED"
    | "DEFORESTATION_DETECTED"
    | "NO_FOREST_DEGRADATION_DETECTED"
    | "POSSIBLE_FOREST_DEGRADATION_DETECTED"
    | "FOREST_DEGRADATION_DETECTED"
    | "INCONCLUSIVE";
  claimSummary: string;
  claimedPeriodStart?: string;
  claimedPeriodEnd?: string;
  confidence: "HIGH" | "MEDIUM" | "LOW" | "NOT_STATED";
  /**
   * Stated by the source; preserved verbatim.
   *
   * @maxItems 200
   */
  limitations: string[];
}
export interface ScsCoverageAttestation {
  attestationProvided: boolean;
  /**
   * A registered SCS-CAP-02 partyId, not RETIRED.
   */
  attestingPartyId?: string;
  attestingRole?: string;
  authorityBasis?: string;
  attestedAt?: string;
  declaredCoverageStart?: string;
  declaredCoverageEnd?: string;
  declarationTextReference?: string;
}

export type ScsDeforestationEvidenceLimitationCode =
  | "SPATIAL_COVERAGE_NOT_VERIFIED"
  | "TEMPORAL_COVERAGE_NOT_EVALUATED"
  | "INTEGRITY_UNVERIFIED"
  | "ATTESTATION_EXCEEDS_ANALYSIS"
  | "PROVENANCE_INCOMPLETE"
  | "CHAIN_OF_CUSTODY_INCOMPLETE"
  | "RESOLUTION_BELOW_REQUIREMENT"
  | "RECENCY_BELOW_REQUIREMENT"
  | "RECENCY_NOT_EVALUATED"
  | "AUTHORITY_CONFIRMATION_MISSING"
  | "SOURCE_TYPE_VOCABULARY_UNKNOWN";

/**
 * SCS-CAP-04 ScsDeforestationEvidenceAdmissionDecision (contract 5c6a263). Admission means the evidence is trustworthy as a record, not that its conclusion is sufficient. An admission check is true only if it was performed and passed; every limitation is recorded as a code and in prose.
 */
export interface ScsDeforestationEvidenceAdmissionDecision {
  decisionId: string;
  evidenceId: string;
  plotId: string;
  frameworkAssociationId: string;
  decision: "ADMITTED" | "ADMITTED_WITH_LIMITATIONS" | "QUARANTINED" | "REJECTED";
  admissionChecks: ScsEvidenceAdmissionChecks;
  temporalCoverageCompleteAtAdmission: boolean;
  spatialCoverageCompleteAtAdmission: boolean;
  /**
   * @maxItems 200
   */
  limitations: string[];
  /**
   * @maxItems 11
   */
  limitationCodes: ScsDeforestationEvidenceLimitationCode[];
  /**
   * @maxItems 50
   */
  rejectionReasons?: string[];
  decidedBy: ActorReference;
  decidedAt: string;
}
export interface ScsEvidenceAdmissionChecks {
  sourceIdentifiable: boolean;
  attributionEstablished: boolean;
  objectIntegrityVerified: boolean;
  evidenceRelatedToClaimedPlot: boolean;
  temporalDatesInternallyConsistent: boolean;
  attestationConsistentWithAnalysis: boolean;
  provenanceComplete: boolean;
  evidenceTypeCompatibleWithRequirement: boolean;
  submitterAuthorised: boolean;
}

/**
 * Immutable receipt for an SCS-CAP-04 deforestation evidence admission decision, written in the same transaction as the decision (foundation/receipts.ts). Its SHA-256 over canonical JSON is returned alongside it as receiptDigest.
 */
export interface ScsDeforestationEvidenceAdmissionReceipt {
  receiptId: string;
  receiptVersion: "1";
  capabilityId: "SCS-CAP-04";
  decisionType: "DEFORESTATION_EVIDENCE_ADMISSION";
  /**
   * evidenceId of the admitted record.
   */
  subjectId: string;
  correlationId: string;
  /**
   * SHA-256 (hex) of the canonical request: method, route and body.
   */
  requestDigest: string;
  idempotencyKey: string | null;
  issuedAt: string;
  /**
   * The authenticated actor whose request produced this decision.
   */
  issuedFor: ActorReference;
  decision: ScsDeforestationEvidenceAdmissionDecision;
}

/**
 * Body of a successful POST /scs/v1/deforestation-evidence (201): the admission decision, the immutable receipt that records it, and the receipt's SHA-256 over canonical JSON.
 */
export interface ScsDeforestationEvidenceAdmissionResponse {
  decision: ScsDeforestationEvidenceAdmissionDecision;
  receipt: ScsDeforestationEvidenceAdmissionReceipt;
  receiptDigest: string;
}
