/* eslint-disable */
/**
 * GENERATED FILE — DO NOT EDIT BY HAND.
 * Generated by json-schema-to-typescript from:
 *   src/schemas/cap-02/party-registration-request.schema.json
 *   src/schemas/cap-02/party-registration-decision.schema.json
 *   src/schemas/cap-02/party-registration-receipt.schema.json
 *   src/schemas/cap-02/party-registration-response.schema.json
 *   src/schemas/cap-02/identity-evidence-submission-params.schema.json
 *   src/schemas/cap-02/identity-evidence-submission-request.schema.json
 *   src/schemas/cap-02/identity-evidence-submission-decision.schema.json
 *   src/schemas/cap-02/identity-evidence-submission-receipt.schema.json
 *   src/schemas/cap-02/identity-evidence-submission-response.schema.json
 *   src/schemas/cap-02/relationship-registration-request.schema.json
 *   src/schemas/cap-02/relationship-registration-decision.schema.json
 *   src/schemas/cap-02/relationship-registration-receipt.schema.json
 *   src/schemas/cap-02/relationship-registration-response.schema.json
 *   src/schemas/cap-02/mandate-registration-request.schema.json
 *   src/schemas/cap-02/mandate-registration-decision.schema.json
 *   src/schemas/cap-02/mandate-registration-receipt.schema.json
 *   src/schemas/cap-02/mandate-registration-response.schema.json
 *   src/schemas/cap-02/role-claim-params.schema.json
 *   src/schemas/cap-02/role-claim-request.schema.json
 *   src/schemas/cap-02/role-claim-decision.schema.json
 *   src/schemas/cap-02/role-claim-receipt.schema.json
 *   src/schemas/cap-02/role-claim-response.schema.json
 *   src/schemas/cap-02/verification-assessment-params.schema.json
 *   src/schemas/cap-02/verification-assessment-request.schema.json
 *   src/schemas/cap-02/verification-assessment-decision.schema.json
 *   src/schemas/cap-02/verification-assessment-receipt.schema.json
 *   src/schemas/cap-02/verification-assessment-response.schema.json
 * To change these types, edit the schema(s) above, then run:
 *   npm run generate:types
 * npm test fails if this file differs from what the schemas generate.
 */

import type { ActorReference } from "./shared.js";

export type NonBlankText = string;

/**
 * SCS-CAP-02 party identity registration request: every ScsPartyIdentity field a submitter provides. Not in the request, because the system sets them: partyId (database-generated), partyVersion (1 on registration), schemaVersion, registeredAt, registeredBy and provenance.submittedBy (the authenticated actor), provenance.recordedAt, registrationStatus (REGISTERED on registration) and verificationAssessments (recorded separately; registration is not verification). Country codes are checked by the capability against ISO 3166-1 alpha-2, so an unrecognised code is refused with the contract's COUNTRY_CODE_UNRECOGNISED rather than a schema error.
 */
export interface ScsPartyRegistrationRequest {
  partyType: "NATURAL_PERSON" | "LEGAL_ENTITY" | "COOPERATIVE" | "COMMUNITY_GROUP" | "GOVERNMENT_BODY" | "OTHER";
  partyName: NonBlankText;
  /**
   * ISO 3166-1 alpha-2, uppercase (checked by the capability).
   */
  countryOfRegistration: string;
  /**
   * ISO 3166-1 alpha-2, uppercase (checked by the capability). Optional.
   */
  countryOfOperation?: string;
  identityEvidence: ScsPartyIdentityEvidenceInput;
  /**
   * ScsPartyIdentity.provenance.submittingOrganizationId. Optional.
   */
  submittingOrganizationId?: string;
}
/**
 * What documents support this identity (ScsPartyIdentity.identityEvidence). Evidence ids are recorded, not verified. Evidence ids are lowercase canonical UUIDs, so a duplicate within one request is always caught here.
 */
export interface ScsPartyIdentityEvidenceInput {
  /**
   * @maxItems 200
   */
  evidenceIds: string[];
  /**
   * @maxItems 200
   */
  evidenceLimitations: NonBlankText[];
}

/**
 * SCS-CAP-02 ScsPartyRegistrationDecision, as defined in the canonical contract. An eligibility check is true only if it was actually performed and passed.
 */
export interface ScsPartyRegistrationDecision {
  decisionId: string;
  partyId: string;
  decision: "REGISTERED" | "REGISTERED_WITH_GAPS" | "REJECTED" | "REQUIRES_HUMAN_REVIEW";
  eligibilityChecks: ScsPartyEligibilityChecks;
  /**
   * @maxItems 200
   */
  gaps: ScsPartyRegistrationGap[];
  /**
   * @maxItems 200
   */
  decisionReasons: string[];
  decidedBy: ActorReference;
  decidedAt: string;
}
export interface ScsPartyEligibilityChecks {
  partyTypeValid: boolean;
  countryCodeValid: boolean;
  partyNameProvided: boolean;
  registrantAuthorised: boolean;
  noConflictingRegistrationDetected: boolean;
}
export interface ScsPartyRegistrationGap {
  gapCode: string;
  gapDescription: string;
  humanReviewRequired: boolean;
}

/**
 * Immutable receipt for an SCS-CAP-02 party registration decision, written in the same transaction as the decision (foundation/receipts.ts). Its SHA-256 over canonical JSON is returned alongside it as receiptDigest.
 */
export interface ScsPartyRegistrationReceipt {
  receiptId: string;
  receiptVersion: "1";
  capabilityId: "SCS-CAP-02";
  decisionType: "PARTY_REGISTRATION";
  /**
   * partyId of the registered party; null when the decision registered nothing.
   */
  subjectId: string | null;
  correlationId: string;
  /**
   * SHA-256 (hex) of the canonical request: method, route and body.
   */
  requestDigest: string;
  idempotencyKey: string | null;
  issuedAt: string;
  /**
   * The authenticated actor whose request produced this decision.
   */
  issuedFor: ActorReference;
  decision: ScsPartyRegistrationDecision;
}

/**
 * Body of a successful POST /scs/v1/parties (201): the registration decision, the immutable receipt that records it, and the receipt's SHA-256 over canonical JSON.
 */
export interface ScsPartyRegistrationResponse {
  decision: ScsPartyRegistrationDecision;
  receipt: ScsPartyRegistrationReceipt;
  receiptDigest: string;
}

/**
 * Path parameters of POST /scs/v1/parties/:partyId/evidence.
 */
export interface ScsIdentityEvidenceSubmissionPathParams {
  partyId: string;
}

/**
 * SCS-CAP-02 ScsIdentityEvidenceSubmissionRequest: evidence submitted for an already registered party. partyId is taken from the request path. Not in the request, because the system sets them: submissionId (database-generated), partyVersion (the party's current version), submittedBy (the authenticated actor) and submittedAt. Evidence ids are lowercase canonical UUIDs, so a duplicate within one request is always caught here.
 */
export interface ScsIdentityEvidenceSubmissionRequest {
  /**
   * One to 200 identifiers, no duplicates.
   *
   * @minItems 1
   * @maxItems 200
   */
  evidenceIds: string[];
  /**
   * @maxItems 200
   */
  evidenceLimitations: string[];
  /**
   * Optional; an identifier issued outside SCS.
   */
  submittingOrganizationId?: string;
}

/**
 * SCS-CAP-02 ScsIdentityEvidenceSubmissionDecision, as defined in the canonical contract. RECORDED means the evidence was admitted, not verified. An eligibility check is true only if it was actually performed and passed.
 */
export interface ScsIdentityEvidenceSubmissionDecision {
  decisionId: string;
  submissionId: string;
  partyId: string;
  partyVersion: number;
  decision: "RECORDED";
  eligibilityChecks: ScsIdentityEvidenceEligibilityChecks;
  /**
   * @maxItems 200
   */
  decisionReasons: string[];
  decidedBy: ActorReference;
  decidedAt: string;
}
export interface ScsIdentityEvidenceEligibilityChecks {
  partyExists: boolean;
  partyNotRetired: boolean;
  submitterAuthorised: boolean;
  evidenceIdsNotAlreadyLinked: boolean;
}

/**
 * Immutable receipt for an SCS-CAP-02 identity evidence submission decision, written in the same transaction as the decision (foundation/receipts.ts). Its SHA-256 over canonical JSON is returned alongside it as receiptDigest.
 */
export interface ScsIdentityEvidenceSubmissionReceipt {
  receiptId: string;
  receiptVersion: "1";
  capabilityId: "SCS-CAP-02";
  decisionType: "IDENTITY_EVIDENCE_SUBMISSION";
  /**
   * submissionId of the recorded submission.
   */
  subjectId: string;
  correlationId: string;
  /**
   * SHA-256 (hex) of the canonical request: method, concrete path (partyId included) and body.
   */
  requestDigest: string;
  idempotencyKey: string | null;
  issuedAt: string;
  /**
   * The authenticated actor whose request produced this decision.
   */
  issuedFor: ActorReference;
  decision: ScsIdentityEvidenceSubmissionDecision;
}

/**
 * Body of a successful POST /scs/v1/parties/:partyId/evidence (201): the submission decision, the immutable receipt that records it, and the receipt's SHA-256 over canonical JSON.
 */
export interface ScsIdentityEvidenceSubmissionResponse {
  decision: ScsIdentityEvidenceSubmissionDecision;
  receipt: ScsIdentityEvidenceSubmissionReceipt;
  receiptDigest: string;
}

/**
 * SCS-CAP-02 ScsRelationshipRegistrationRequest (contract 9a3e978). Not in the request, because the system sets them: relationshipId, schemaVersion, claimedAt, verificationStatus (CLAIMED_UNVERIFIED), lifecycleStatus (ACTIVE), representationVersion ("1" until the contract defines it), createdAt and createdBy. A registration never supersedes another relationship. Rules that span fields (OTHER description, validity period, claiming party, framework scope) are checked by the capability so that the contract's failure codes are returned.
 */
export interface ScsRelationshipRegistrationRequest {
  fromPartyId: string;
  toPartyId: string;
  relationshipType: "SUPPLIES_TO" | "PROCESSES_FOR" | "AGGREGATES_FOR" | "EXPORTS_FOR" | "CERTIFIES_FOR" | "OTHER";
  /**
   * Required exactly when relationshipType is OTHER.
   */
  otherRelationshipTypeDescription?: string;
  /**
   * Each value must equal the scope.commodityCode of a referenced framework.
   *
   * @minItems 1
   * @maxItems 50
   */
  commodityScope: string[];
  /**
   * Each value must equal the scope.countryOfOrigin of a referenced framework.
   *
   * @minItems 1
   * @maxItems 50
   */
  geographicScope: string[];
  /**
   * CAP-01 frameworkIds; at least one, each ACTIVE.
   *
   * @minItems 1
   * @maxItems 50
   */
  frameworkAssociationIds: string[];
  validFrom?: string;
  /**
   * When given with validFrom, must be after it.
   */
  validUntil?: string;
  /**
   * One of the two parties: fromPartyId or toPartyId.
   */
  claimedByPartyId: string;
  /**
   * @maxItems 200
   */
  relationshipEvidenceIds: string[];
}

/**
 * SCS-CAP-02 ScsRelationshipRegistrationDecision (contract 9a3e978). REGISTERED means a governed record of a claimed relationship exists; it verifies neither party nor any commodity movement. An eligibility check is true only if it was actually performed and passed.
 */
export interface ScsRelationshipRegistrationDecision {
  decisionId: string;
  relationshipId: string;
  decision: "REGISTERED";
  eligibilityChecks: ScsRelationshipEligibilityChecks;
  /**
   * @maxItems 200
   */
  decisionReasons: string[];
  decidedBy: ActorReference;
  decidedAt: string;
}
export interface ScsRelationshipEligibilityChecks {
  registrantAuthorised: boolean;
  fromPartyExists: boolean;
  toPartyExists: boolean;
  partiesNotRetired: boolean;
  notSelfReferential: boolean;
  claimingPartyIsAParty: boolean;
  otherTypeDescribed: boolean;
  frameworksExist: boolean;
  frameworksActive: boolean;
  scopeWithinFrameworks: boolean;
  validityPeriodValid: boolean;
  noConflictingRecord: boolean;
}

/**
 * Immutable receipt for an SCS-CAP-02 relationship registration decision, written in the same transaction as the decision (foundation/receipts.ts). Its SHA-256 over canonical JSON is returned alongside it as receiptDigest.
 */
export interface ScsRelationshipRegistrationReceipt {
  receiptId: string;
  receiptVersion: "1";
  capabilityId: "SCS-CAP-02";
  decisionType: "RELATIONSHIP_REGISTRATION";
  /**
   * relationshipId of the registered relationship.
   */
  subjectId: string;
  correlationId: string;
  /**
   * SHA-256 (hex) of the canonical request: method, route and body.
   */
  requestDigest: string;
  idempotencyKey: string | null;
  issuedAt: string;
  /**
   * The authenticated actor whose request produced this decision.
   */
  issuedFor: ActorReference;
  decision: ScsRelationshipRegistrationDecision;
}

/**
 * Body of a successful POST /scs/v1/relationships (201): the registration decision, the immutable receipt that records it, and the receipt's SHA-256 over canonical JSON.
 */
export interface ScsRelationshipRegistrationResponse {
  decision: ScsRelationshipRegistrationDecision;
  receipt: ScsRelationshipRegistrationReceipt;
  receiptDigest: string;
}

/**
 * SCS-CAP-02 ScsMandateRegistrationRequest (contract 9a3e978). Not in the request, because the system sets them: mandateId, schemaVersion, verificationStatus (CLAIMED_UNVERIFIED), revocationStatus (NOT_REVOKED), createdAt, createdBy and the authorityBoundary flags (always true). validUntil is required (a mandate always expires) and mandateEvidenceIds needs at least one id (evidence that the granting party agreed); an action outside the enumeration is refused here. Rules that span fields or records (OTHER_EXPLICITLY_NAMED description, validity period, parties, relationship prerequisite, framework scope) are checked by the capability so that the contract's failure codes are returned.
 */
export interface ScsMandateRegistrationRequest {
  grantingPartyId: string;
  representativePartyId: string;
  /**
   * Enumerated, never open-ended: at least one, no duplicates.
   *
   * @minItems 1
   * @maxItems 6
   */
  permittedActions: (
    | "SUBMIT_IDENTITY_EVIDENCE"
    | "SUBMIT_PLOT_ASSOCIATION_EVIDENCE"
    | "SUBMIT_CUSTODY_EVIDENCE"
    | "SUBMIT_DEFORESTATION_EVIDENCE"
    | "REQUEST_FRAMEWORK_ASSOCIATION"
    | "OTHER_EXPLICITLY_NAMED"
  )[];
  /**
   * Required exactly when permittedActions includes OTHER_EXPLICITLY_NAMED.
   */
  otherActionDescription?: string;
  /**
   * CAP-01 frameworkIds; at least one, each ACTIVE, each referenced by the prerequisite relationship.
   *
   * @minItems 1
   * @maxItems 50
   */
  frameworkAssociationIds: string[];
  /**
   * Each value must equal the scope.commodityCode of a referenced framework.
   *
   * @minItems 1
   * @maxItems 50
   */
  commodityScope: string[];
  /**
   * Each value must equal the scope.countryOfOrigin of a referenced framework.
   *
   * @minItems 1
   * @maxItems 50
   */
  geographicScope: string[];
  validFrom: string;
  /**
   * Required; must be after validFrom.
   */
  validUntil: string;
  /**
   * At least one: evidence that the granting party agreed.
   *
   * @minItems 1
   * @maxItems 200
   */
  mandateEvidenceIds: string[];
}

/**
 * SCS-CAP-02 ScsMandateRegistrationDecision (contract 9a3e978). REGISTERED means a governed, scoped, expiring and revocable record of representation authority exists; it verifies neither party and grants nothing beyond the enumerated actions. An eligibility check is true only if it was actually performed and passed.
 */
export interface ScsMandateRegistrationDecision {
  decisionId: string;
  mandateId: string;
  decision: "REGISTERED";
  eligibilityChecks: ScsMandateEligibilityChecks;
  /**
   * @maxItems 200
   */
  decisionReasons: string[];
  decidedBy: ActorReference;
  decidedAt: string;
}
export interface ScsMandateEligibilityChecks {
  registrantAuthorised: boolean;
  grantingPartyExists: boolean;
  representativePartyExists: boolean;
  partiesNotRetired: boolean;
  notSelfGranted: boolean;
  activeRelationshipExists: boolean;
  otherActionDescribed: boolean;
  frameworksExist: boolean;
  frameworksActive: boolean;
  scopeWithinFrameworks: boolean;
  validityPeriodValid: boolean;
  consentEvidenceProvided: boolean;
  noConflictingRecord: boolean;
}

/**
 * Immutable receipt for an SCS-CAP-02 mandate registration decision, written in the same transaction as the decision (foundation/receipts.ts). Its SHA-256 over canonical JSON is returned alongside it as receiptDigest.
 */
export interface ScsMandateRegistrationReceipt {
  receiptId: string;
  receiptVersion: "1";
  capabilityId: "SCS-CAP-02";
  decisionType: "MANDATE_REGISTRATION";
  /**
   * mandateId of the registered mandate.
   */
  subjectId: string;
  correlationId: string;
  /**
   * SHA-256 (hex) of the canonical request: method, route and body.
   */
  requestDigest: string;
  idempotencyKey: string | null;
  issuedAt: string;
  /**
   * The authenticated actor whose request produced this decision.
   */
  issuedFor: ActorReference;
  decision: ScsMandateRegistrationDecision;
}

/**
 * Body of a successful POST /scs/v1/mandates (201): the registration decision, the immutable receipt that records it, and the receipt's SHA-256 over canonical JSON.
 */
export interface ScsMandateRegistrationResponse {
  decision: ScsMandateRegistrationDecision;
  receipt: ScsMandateRegistrationReceipt;
  receiptDigest: string;
}

/**
 * Path parameters of POST /scs/v1/parties/:partyId/roles.
 */
export interface ScsRoleClaimPathParams {
  partyId: string;
}

/**
 * SCS-CAP-02 ScsRoleClaimRequest (contract 9a3e978). partyId is taken from the request path. Not in the request, because the system sets them: roleClaimId, partyVersion (the party's current version), frameworkVersion (the framework's regulationVersion), verificationStatus (CLAIMED_UNVERIFIED), claimedAt and claimedBy. Rules that span fields or records (OTHER description, validity period, framework and scope) are checked by the capability so that the contract's failure codes are returned.
 */
export interface ScsRoleClaimRequest {
  claimedRole: "OPERATOR" | "SUPPLIER" | "AGGREGATOR" | "PROCESSOR" | "EXPORTER" | "IMPORTER" | "TRADER" | "OTHER";
  /**
   * Required exactly when claimedRole is OTHER.
   */
  otherRoleDescription?: string;
  /**
   * A CAP-01 frameworkId; the framework must be ACTIVE.
   */
  frameworkAssociationId: string;
  /**
   * Each value must equal the framework's scope.commodityCode.
   *
   * @minItems 1
   * @maxItems 50
   */
  commodityScope: string[];
  /**
   * Each value must equal the framework's scope.countryOfOrigin.
   *
   * @minItems 1
   * @maxItems 50
   */
  geographicScope: string[];
  /**
   * @maxItems 200
   */
  roleEvidenceIds: string[];
  validFrom?: string;
  /**
   * When given with validFrom, must be after it.
   */
  validUntil?: string;
  /**
   * @maxItems 200
   */
  limitations: string[];
}

/**
 * SCS-CAP-02 ScsRoleClaimDecision (contract 9a3e978). REGISTERED means a governed record of a claimed role exists; the role is not verified. An eligibility check is true only if it was actually performed and passed.
 */
export interface ScsRoleClaimDecision {
  decisionId: string;
  roleClaimId: string;
  partyId: string;
  partyVersion: number;
  decision: "REGISTERED";
  eligibilityChecks: ScsRoleClaimEligibilityChecks;
  /**
   * @maxItems 200
   */
  decisionReasons: string[];
  decidedBy: ActorReference;
  decidedAt: string;
}
export interface ScsRoleClaimEligibilityChecks {
  registrantAuthorised: boolean;
  partyExists: boolean;
  partyNotRetired: boolean;
  otherRoleDescribed: boolean;
  frameworkExists: boolean;
  frameworkActive: boolean;
  scopeWithinFramework: boolean;
  validityPeriodValid: boolean;
  noConflictingRecord: boolean;
}

/**
 * Immutable receipt for an SCS-CAP-02 role claim decision, written in the same transaction as the decision (foundation/receipts.ts). Its SHA-256 over canonical JSON is returned alongside it as receiptDigest.
 */
export interface ScsRoleClaimReceipt {
  receiptId: string;
  receiptVersion: "1";
  capabilityId: "SCS-CAP-02";
  decisionType: "ROLE_CLAIM_REGISTRATION";
  /**
   * roleClaimId of the registered role claim.
   */
  subjectId: string;
  correlationId: string;
  /**
   * SHA-256 (hex) of the canonical request: method, concrete path (partyId included) and body.
   */
  requestDigest: string;
  idempotencyKey: string | null;
  issuedAt: string;
  /**
   * The authenticated actor whose request produced this decision.
   */
  issuedFor: ActorReference;
  decision: ScsRoleClaimDecision;
}

/**
 * Body of a successful POST /scs/v1/parties/:partyId/roles (201): the role claim decision, the immutable receipt that records it, and the receipt's SHA-256 over canonical JSON.
 */
export interface ScsRoleClaimResponse {
  decision: ScsRoleClaimDecision;
  receipt: ScsRoleClaimReceipt;
  receiptDigest: string;
}

/**
 * Path parameters of POST /scs/v1/parties/:partyId/verifications.
 */
export interface ScsVerificationAssessmentPathParams {
  partyId: string;
}

/**
 * SCS-CAP-02 ScsVerificationAssessmentRequest (contract e85c58a). partyId is taken from the request path. Not in the request, because the system sets them: assessmentId, partyVersion (the party's current version), recordedBy, recordedAt and the authorityBoundary flags (always true). verificationStatus accepts the contract's ScsIdentityVerificationStatus values; the capability refuses the two that are derived, not recorded, with VERIFICATION_STATUS_NOT_RECORDABLE. Jurisdiction codes, dates, evidence linkage and supersession are checked by the capability so that the contract's failure codes are returned.
 */
export interface ScsVerificationAssessmentRequest {
  verificationStatus:
    | "REGISTERED_UNVERIFIED"
    | "PARTIALLY_VERIFIED"
    | "VERIFIED_FOR_DECLARED_SCOPE"
    | "VERIFICATION_EXPIRED"
    | "DISPUTED"
    | "FAIL_CLOSED";
  verificationScope: ScsVerificationScopeInput;
  verifyingAuthority: ScsVerifyingAuthorityInput;
  /**
   * Not in the future; may be earlier than the party's registration.
   */
  verifiedAt: string;
  /**
   * When given, strictly after verifiedAt; may already have passed.
   */
  expiresAt?: string;
  /**
   * At least one; each already linked to the party's current version.
   *
   * @minItems 1
   * @maxItems 200
   */
  evidenceIds: string[];
  /**
   * @maxItems 200
   */
  limitations: string[];
  /**
   * An earlier assessment of the same party, not already superseded.
   */
  supersedesAssessmentId?: string;
}
export interface ScsVerificationScopeInput {
  scopeDescription: string;
  /**
   * ISO 3166-1 alpha-2, uppercase (checked by the capability).
   */
  jurisdictionCode: string;
  /**
   * @maxItems 200
   */
  verifiedAttributes: string[];
  /**
   * Explicit exclusions: what was NOT verified.
   *
   * @maxItems 200
   */
  excludedFromVerification: string[];
}
/**
 * Recorded as declared: there is no registry of verifying authorities to check it against.
 */
export interface ScsVerifyingAuthorityInput {
  authorityId: string;
  authorityName: string;
  authorityBasis: string;
  /**
   * ISO 3166-1 alpha-2, uppercase (checked by the capability).
   */
  jurisdictionCode: string;
}

/**
 * SCS-CAP-02 ScsVerificationAssessmentDecision (contract e85c58a). RECORDED means the assessment is on record, scoped and attributed; it never changes the party's registrationStatus. An eligibility check is true only if it was actually performed and passed.
 */
export interface ScsVerificationAssessmentDecision {
  decisionId: string;
  assessmentId: string;
  partyId: string;
  partyVersion: number;
  decision: "RECORDED";
  eligibilityChecks: ScsVerificationEligibilityChecks;
  /**
   * @maxItems 200
   */
  decisionReasons: string[];
  decidedBy: ActorReference;
  decidedAt: string;
}
export interface ScsVerificationEligibilityChecks {
  verifierAuthorised: boolean;
  statusRecordable: boolean;
  datesValid: boolean;
  jurisdictionsRecognised: boolean;
  partyExists: boolean;
  partyNotRetired: boolean;
  verifierIndependentOfRegistrant: boolean;
  evidenceLinkedToParty: boolean;
  supersessionValid: boolean;
}

/**
 * Immutable receipt for an SCS-CAP-02 verification assessment decision, written in the same transaction as the decision (foundation/receipts.ts). Its SHA-256 over canonical JSON is returned alongside it as receiptDigest.
 */
export interface ScsVerificationAssessmentReceipt {
  receiptId: string;
  receiptVersion: "1";
  capabilityId: "SCS-CAP-02";
  decisionType: "VERIFICATION_ASSESSMENT";
  /**
   * assessmentId of the recorded assessment.
   */
  subjectId: string;
  correlationId: string;
  /**
   * SHA-256 (hex) of the canonical request: method, concrete path (partyId included) and body.
   */
  requestDigest: string;
  idempotencyKey: string | null;
  issuedAt: string;
  /**
   * The authenticated actor whose request produced this decision.
   */
  issuedFor: ActorReference;
  decision: ScsVerificationAssessmentDecision;
}

/**
 * Body of a successful POST /scs/v1/parties/:partyId/verifications (201): the assessment decision, the immutable receipt that records it, and the receipt's SHA-256 over canonical JSON.
 */
export interface ScsVerificationAssessmentResponse {
  decision: ScsVerificationAssessmentDecision;
  receipt: ScsVerificationAssessmentReceipt;
  receiptDigest: string;
}
