/* eslint-disable */
/**
 * GENERATED FILE — DO NOT EDIT BY HAND.
 * Generated by json-schema-to-typescript from:
 *   src/schemas/cap-05/custody-event-submission-request.schema.json
 *   src/schemas/cap-05/custody-event-admission-decision.schema.json
 *   src/schemas/cap-05/custody-event-admission-receipt.schema.json
 *   src/schemas/cap-05/custody-event-admission-response.schema.json
 * To change these types, edit the schema(s) above, then run:
 *   npm run generate:types
 * npm test fails if this file differs from what the schemas generate.
 */

import type { ScsActingUnder, ScsRepresentationChecks } from "./cap-02.js";
import type { ActorReference } from "./shared.js";

export type ScsCustodyQuantityUnit = "KG" | "TONNE" | "LITRE" | "M3" | "BALE" | "SACK" | "UNIT" | "OTHER";

/**
 * SCS-CAP-05 ScsCustodyEventSubmissionRequest (contract 7b4fc02, 9845179). The system sets eventId, eventVersion, schemaVersion, evidenceRequirementSpecId, both partyVersions, integrityStatus, submittedBy, submittedAt and the whole admission block. A quantity is required except for CERTIFICATION and INSPECTION events. Consistency rules the contract assigns to INTERNAL_INCONSISTENCY (positive amounts, unit descriptions, coordinates, country codes, event-type rules, dates) are checked by the capability so that its failure code is returned.
 */
export interface ScsCustodyEventSubmissionRequest {
  /**
   * An SCS-CAP-01 frameworkId (as in SCS-CAP-02), not an SCS-CAP-03 plot association.
   */
  frameworkAssociationId: string;
  eventType:
    | "PURCHASE"
    | "TRANSFER"
    | "WEIGHING"
    | "PROCESSING"
    | "TRANSFORMATION"
    | "SPLIT"
    | "CONSOLIDATION"
    | "EXPORT"
    | "IMPORT"
    | "CERTIFICATION"
    | "INSPECTION"
    | "OTHER";
  sourceParty: ScsCustodySourcePartyInput;
  destinationParty: ScsCustodyDestinationPartyInput;
  commodity: ScsCustodyCommodity;
  quantity?: ScsCustodyQuantity;
  eventLocation: ScsCustodyEventLocation;
  eventTime: ScsCustodyEventTime;
  transformation?: ScsCustodyTransformation;
  /**
   * @maxItems 100
   */
  predecessorEventIds: string[];
  /**
   * @maxItems 100
   */
  successorEventIds: string[];
  splitFromEventId?: string;
  /**
   * @maxItems 100
   */
  consolidatedFromEventIds?: string[];
  supportingDocument: ScsCustodySupportingDocumentInput;
  /**
   * Present only for a representative submission. Replaces the former submissionMandateId (amendment of 2026-09-27): a request that sends submissionMandateId is refused as invalid. The system sets the record's provenance.submissionMandateId from actingUnder.mandateId.
   */
  actingUnder?: ScsActingUnder;
  /**
   * As declared by the submitter.
   */
  chainOfCustodyComplete: boolean;
  /**
   * @maxItems 200
   */
  uncertainties: string[];
  /**
   * @maxItems 200
   */
  contradictions: string[];
  /**
   * @maxItems 200
   */
  knownGaps: string[];
}
export interface ScsCustodySourcePartyInput {
  partyId: string;
  partyRoleAtEvent: "SUPPLIER" | "AGGREGATOR" | "PROCESSOR" | "EXPORTER" | "OTHER";
  /**
   * An SCS-CAP-02 mandateId; checked, never authorising.
   */
  actingUnderMandateId?: string;
}
export interface ScsCustodyDestinationPartyInput {
  partyId: string;
  partyRoleAtEvent: "AGGREGATOR" | "PROCESSOR" | "EXPORTER" | "IMPORTER" | "OTHER";
}
export interface ScsCustodyCommodity {
  commodityCode: string;
  commodityName: string;
  /**
   * @maxItems 500
   */
  sourcePlotIds: string[];
  sourcePlotIdsComplete: boolean;
  batchIdentifier: string;
  batchVersion?: number;
}
export interface ScsCustodyQuantity {
  /**
   * Greater than 0 (checked by the capability: INTERNAL_INCONSISTENCY).
   */
  amount: number;
  unit: ScsCustodyQuantityUnit;
  /**
   * Required when unit is OTHER; absent otherwise.
   */
  unitDescription?: string;
  measurementMethod?: string;
  measurementUncertainty?: string;
}
export interface ScsCustodyEventLocation {
  /**
   * ISO 3166-1 alpha-2 (checked by the capability).
   */
  countryCode: string;
  administrativeArea?: string;
  facilityId?: string;
  facilityName?: string;
  coordinates?: ScsCustodyEventCoordinates;
}
export interface ScsCustodyEventCoordinates {
  latitude: number;
  longitude: number;
  accuracyMetres?: number;
}
export interface ScsCustodyEventTime {
  /**
   * The local calendar date at the event location.
   */
  eventDate: string;
  /**
   * A full ISO 8601 timestamp in UTC.
   */
  eventTimeUTC?: string;
  timePrecision: "EXACT" | "DATE_ONLY" | "APPROXIMATE" | "UNKNOWN";
}
export interface ScsCustodyTransformation {
  transformationType: "DRYING" | "MILLING" | "PRESSING" | "BLENDING" | "GRADING" | "PACKAGING" | "OTHER";
  inputQuantity: number;
  inputUnit: ScsCustodyQuantityUnit;
  inputUnitDescription?: string;
  outputQuantity: number;
  outputUnit: ScsCustodyQuantityUnit;
  outputUnitDescription?: string;
  conversionRatioDescription?: string;
}
export interface ScsCustodySupportingDocumentInput {
  /**
   * The AAB-PLATFORM-01 objectId of the stored document, when one is cited.
   */
  objectId?: string;
  documentId: string;
  documentType:
    | "PURCHASE_RECEIPT"
    | "WEIGHT_TICKET"
    | "TRANSPORT_DOCUMENT"
    | "PROCESSING_RECORD"
    | "CERTIFICATION_DOCUMENT"
    | "INSPECTION_REPORT"
    | "CUSTOMS_DECLARATION"
    | "OTHER";
  documentReference: string;
  issuingAuthority?: string;
  documentDate?: string;
  /**
   * Lowercase hexadecimal SHA-256 of the document.
   */
  contentDigest: string;
}

export type ScsCustodyEventLimitationCode =
  | "PARTY_UNVERIFIED"
  | "SOURCE_PLOTS_INCOMPLETE"
  | "SOURCE_PLOT_NOT_REGISTERED"
  | "SOURCE_PLOT_RETIRED"
  | "QUANTITY_PRECISION_UNCERTAIN"
  | "EVENT_TIME_APPROXIMATE"
  | "LINKED_EVENT_NOT_ADMITTED"
  | "LINKED_EVENT_OUT_OF_SCOPE"
  | "INTEGRITY_UNVERIFIED"
  | "CHAIN_OF_CUSTODY_INCOMPLETE"
  | "MANDATE_NOT_VALID"
  | "QUANTITY_GAIN_UNEXPLAINED"
  | "CONTRADICTION_DECLARED";

/**
 * SCS-CAP-05 ScsCustodyEventAdmissionDecision (contract 7b4fc02, 9845179). Admission means the event is genuine and attributable, not that any chain is continuous or sufficient. An admission check is true only if it was performed and passed; every limitation is recorded as a code and in prose. decisionReasons is never a limitation.
 */
export interface ScsCustodyEventAdmissionDecision {
  decisionId: string;
  eventId: string;
  frameworkAssociationId: string;
  decision: "ADMITTED" | "ADMITTED_WITH_LIMITATIONS" | "QUARANTINED" | "REJECTED";
  admissionChecks: ScsCustodyEventAdmissionChecks;
  /**
   * @maxItems 500
   */
  limitations: string[];
  /**
   * @maxItems 13
   */
  limitationCodes: ScsCustodyEventLimitationCode[];
  /**
   * @maxItems 50
   */
  decisionReasons: string[];
  /**
   * @maxItems 50
   */
  rejectionReasons?: string[];
  decidedBy: ActorReference;
  decidedAt: string;
  authorityBoundary: ScsCustodyEventAuthorityBoundary;
}
export interface ScsCustodyEventAdmissionChecks {
  sourcePartyIdentifiable: boolean;
  destinationPartyIdentifiable: boolean;
  commodityCodeRecognised: boolean;
  batchIdentifierPresent: boolean;
  eventTypeValid: boolean;
  quantityRecorded: boolean;
  eventTimeRecorded: boolean;
  supportingDocumentPresent: boolean;
  documentIntegrityVerified: boolean;
  submitterAuthorised: boolean;
  internallyConsistent: boolean;
  /**
   * Present only for a representative submission.
   */
  representation?: ScsRepresentationChecks;
}
export interface ScsCustodyEventAuthorityBoundary {
  admissionIsNotSufficiency: true;
  admittedEventDoesNotProveChainContinuity: true;
  admittedEventDoesNotVerifyPartyIdentity: true;
  admittedEventDoesNotConstituteLegalCompliance: true;
}

/**
 * Immutable receipt for an SCS-CAP-05 custody event admission decision, written in the same transaction as the decision (foundation/receipts.ts). Its SHA-256 over canonical JSON is returned alongside it as receiptDigest.
 */
export interface ScsCustodyEventAdmissionReceipt {
  receiptId: string;
  receiptVersion: "1";
  capabilityId: "SCS-CAP-05";
  decisionType: "CUSTODY_EVENT_ADMISSION";
  /**
   * eventId of the admitted custody event.
   */
  subjectId: string;
  correlationId: string;
  /**
   * SHA-256 (hex) of the canonical request: method, route and body.
   */
  requestDigest: string;
  idempotencyKey: string | null;
  issuedAt: string;
  /**
   * The authenticated actor whose request produced this decision.
   */
  issuedFor: ActorReference;
  decision: ScsCustodyEventAdmissionDecision;
}

/**
 * Body of a successful POST /scs/v1/custody-events (201): the admission decision, the immutable receipt that records it, and the receipt's SHA-256 over canonical JSON.
 */
export interface ScsCustodyEventAdmissionResponse {
  decision: ScsCustodyEventAdmissionDecision;
  receipt: ScsCustodyEventAdmissionReceipt;
  receiptDigest: string;
}
