/* eslint-disable */
/**
 * GENERATED FILE — DO NOT EDIT BY HAND.
 * Generated by json-schema-to-typescript from:
 *   src/schemas/cap-02/party-registration-request.schema.json
 *   src/schemas/cap-02/party-registration-decision.schema.json
 *   src/schemas/cap-02/party-registration-receipt.schema.json
 *   src/schemas/cap-02/party-registration-response.schema.json
 * To change these types, edit the schema(s) above, then run:
 *   npm run generate:types
 * npm test fails if this file differs from what the schemas generate.
 */

import type { ActorReference } from "./shared.js";

export type NonBlankText = string;

/**
 * SCS-CAP-02 party identity registration request: every ScsPartyIdentity field a submitter provides. Not in the request, because the system sets them: partyId (database-generated), partyVersion (1 on registration), schemaVersion, registeredAt, registeredBy and provenance.submittedBy (the authenticated actor), provenance.recordedAt, registrationStatus (REGISTERED on registration) and verificationAssessments (recorded separately; registration is not verification). Country codes are checked by the capability against ISO 3166-1 alpha-2, so an unrecognised code is refused with the contract's COUNTRY_CODE_UNRECOGNISED rather than a schema error.
 */
export interface ScsPartyRegistrationRequest {
  partyType: "NATURAL_PERSON" | "LEGAL_ENTITY" | "COOPERATIVE" | "COMMUNITY_GROUP" | "GOVERNMENT_BODY" | "OTHER";
  partyName: NonBlankText;
  /**
   * ISO 3166-1 alpha-2, uppercase (checked by the capability).
   */
  countryOfRegistration: string;
  /**
   * ISO 3166-1 alpha-2, uppercase (checked by the capability). Optional.
   */
  countryOfOperation?: string;
  identityEvidence: ScsPartyIdentityEvidenceInput;
  /**
   * ScsPartyIdentity.provenance.submittingOrganizationId. Optional.
   */
  submittingOrganizationId?: string;
}
/**
 * What documents support this identity (ScsPartyIdentity.identityEvidence). Evidence ids are recorded, not verified.
 */
export interface ScsPartyIdentityEvidenceInput {
  /**
   * @maxItems 200
   */
  evidenceIds: string[];
  /**
   * @maxItems 200
   */
  evidenceLimitations: NonBlankText[];
}

/**
 * SCS-CAP-02 ScsPartyRegistrationDecision, as defined in the canonical contract. An eligibility check is true only if it was actually performed and passed.
 */
export interface ScsPartyRegistrationDecision {
  decisionId: string;
  partyId: string;
  decision: "REGISTERED" | "REGISTERED_WITH_GAPS" | "REJECTED" | "REQUIRES_HUMAN_REVIEW";
  eligibilityChecks: ScsPartyEligibilityChecks;
  /**
   * @maxItems 200
   */
  gaps: ScsPartyRegistrationGap[];
  /**
   * @maxItems 200
   */
  decisionReasons: string[];
  decidedBy: ActorReference;
  decidedAt: string;
}
export interface ScsPartyEligibilityChecks {
  partyTypeValid: boolean;
  countryCodeValid: boolean;
  partyNameProvided: boolean;
  registrantAuthorised: boolean;
  noConflictingRegistrationDetected: boolean;
}
export interface ScsPartyRegistrationGap {
  gapCode: string;
  gapDescription: string;
  humanReviewRequired: boolean;
}

/**
 * Immutable receipt for an SCS-CAP-02 party registration decision, written in the same transaction as the decision (foundation/receipts.ts). Its SHA-256 over canonical JSON is returned alongside it as receiptDigest.
 */
export interface ScsPartyRegistrationReceipt {
  receiptId: string;
  receiptVersion: "1";
  capabilityId: "SCS-CAP-02";
  decisionType: "PARTY_REGISTRATION";
  /**
   * partyId of the registered party; null when the decision registered nothing.
   */
  subjectId: string | null;
  correlationId: string;
  /**
   * SHA-256 (hex) of the canonical request: method, route and body.
   */
  requestDigest: string;
  idempotencyKey: string | null;
  issuedAt: string;
  /**
   * The authenticated actor whose request produced this decision.
   */
  issuedFor: ActorReference;
  decision: ScsPartyRegistrationDecision;
}

/**
 * Body of a successful POST /scs/v1/parties (201): the registration decision, the immutable receipt that records it, and the receipt's SHA-256 over canonical JSON.
 */
export interface ScsPartyRegistrationResponse {
  decision: ScsPartyRegistrationDecision;
  receipt: ScsPartyRegistrationReceipt;
  receiptDigest: string;
}
