/* eslint-disable */
/**
 * GENERATED FILE — DO NOT EDIT BY HAND.
 * Generated by json-schema-to-typescript from:
 *   src/schemas/cap-03/plot-registration-request.schema.json
 *   src/schemas/cap-03/plot-registration-decision.schema.json
 *   src/schemas/cap-03/plot-registration-receipt.schema.json
 *   src/schemas/cap-03/plot-registration-response.schema.json
 * To change these types, edit the schema(s) above, then run:
 *   npm run generate:types
 * npm test fails if this file differs from what the schemas generate.
 */

import type { ActorReference } from "./shared.js";

/**
 * SCS-CAP-03 RegisterPlotRequest (contract 2151321). Declared fields only: the system sets plotId, plotVersion, schemaVersion, registeredAt, registeredBy, registrationStatus, overlapState (NOT_EVALUATED) and provenance.submittedBy/recordedAt; on tenure claims tenureClaimId, plotId, plotVersion, recordedAt, recordedBy and verificationStatus (UNVERIFIED); on associations associationId, frameworkVersion, evidenceRequirementSpecId, associatedAt, associatedBy, applicabilityStatus (APPLICABLE) and lifecycleStatus (ACTIVE). Geometry validity, the coordinate reference system, the country code and cross-field rules are checked by the capability so that the contract's failure codes are returned.
 */
export interface RegisterPlotRequest {
  plot: ScsPlotRegistrationInput;
  /**
   * At least one: a plot with no tenure claim cannot be registered.
   *
   * @minItems 1
   * @maxItems 50
   */
  tenureClaims: ScsPlotTenureClaimInput[];
  /**
   * Optional. Each framework at most once. A failed association never fails the registration.
   *
   * @maxItems 20
   */
  initialFrameworkAssociations?: ScsPlotFrameworkAssociationInput[];
}
export interface ScsPlotRegistrationInput {
  plotName?: string;
  /**
   * ISO 3166-1 alpha-2, uppercase (checked by the capability).
   */
  countryCode: string;
  /**
   * Free text: no code system is defined (contract gap).
   *
   * @maxItems 200
   */
  administrativeAreas?: string[];
  geometry: ScsPlotGeometryInput;
  identityEvidence: ScsPlotIdentityEvidenceInput;
  /**
   * Optional; an identifier issued outside SCS.
   */
  submittingOrganizationId?: string;
  /**
   * Free text: no code system is defined (contract gap).
   */
  sourceType: string;
}
export interface ScsPlotGeometryInput {
  geometryType: "POINT" | "POLYGON" | "MULTIPOLYGON";
  /**
   * The GeoJSON (RFC 7946) coordinates member for geometryType; validated by the capability.
   */
  coordinates: unknown[];
  /**
   * Must be EPSG:4326 (checked by the capability).
   */
  coordinateReferenceSystem: string;
  /**
   * Declared, not computed. Required for POLYGON and MULTIPOLYGON; for a POINT, at most 4.
   */
  areaHectares?: number;
  captureMethod:
    | "FORMAL_CADASTRAL_SURVEY"
    | "GOVERNMENT_REGISTRY_GEOMETRY"
    | "PROFESSIONAL_SURVEY"
    | "PHONE_GPS"
    | "COMMUNITY_MAPPING"
    | "COOPERATIVE_MAPPING"
    | "REMOTE_SENSING_DERIVATION"
    | "OTHER";
  positionalAccuracyMetres?: number;
  boundaryUncertaintyDescription?: string;
  capturedAt?: string;
}
export interface ScsPlotIdentityEvidenceInput {
  registryReference?: string;
  registryAuthority?: string;
  /**
   * Declared by the registrant. Other than NOT_APPLICABLE requires registryReference.
   */
  registryVerificationStatus: "VERIFIED" | "UNVERIFIED" | "CONFLICTING" | "REGISTRY_UNAVAILABLE" | "NOT_APPLICABLE";
  /**
   * @maxItems 200
   */
  supportingEvidenceIds: string[];
  /**
   * @maxItems 200
   */
  evidenceLimitations: string[];
}
export interface ScsPlotTenureClaimInput {
  /**
   * Declared; not derived from the party's partyType.
   */
  claimantType: "INDIVIDUAL" | "ORGANIZATION" | "COOPERATIVE" | "COMMUNITY" | "GOVERNMENT" | "OTHER";
  /**
   * A registered SCS-CAP-02 partyId, not RETIRED.
   */
  claimantId: string;
  tenureBasis:
    | "FORMAL_TITLE"
    | "LEASE"
    | "PERMIT"
    | "CUSTOMARY_COLLECTIVE_RIGHT"
    | "CUSTOMARY_INDIVIDUAL_RIGHT"
    | "COMMUNITY_ATTESTATION"
    | "OCCUPANCY_OR_USE_CLAIM"
    | "UNKNOWN";
  /**
   * @maxItems 200
   */
  evidenceIds: string[];
  validFrom?: string;
  validUntil?: string;
  /**
   * @maxItems 200
   */
  limitations: string[];
}
export interface ScsPlotFrameworkAssociationInput {
  /**
   * A registered SCS-CAP-01 frameworkId.
   */
  frameworkId: string;
  /**
   * Must equal the framework's scope.commodityCode.
   */
  commodityCode: string;
  /**
   * When present, a registered SCS-CAP-02 partyId, not RETIRED.
   */
  producerOrOperatorId?: string;
  associationReason: string;
}

/**
 * SCS-CAP-03 ScsPlotRegistrationDecision (contract 2151321). An eligibility check is true only if it was actually performed and passed: in the pilot noFatalOverlapDetected is false, NOT EVALUATED. REGISTERED verifies no title, tenure, boundary, compliance or eligibility.
 */
export interface ScsPlotRegistrationDecision {
  decisionId: string;
  plotId: string;
  decision: "REGISTERED" | "REGISTERED_WITH_GAPS" | "REJECTED" | "REQUIRES_HUMAN_REVIEW";
  eligibilityChecks: ScsPlotEligibilityChecks;
  /**
   * @maxItems 100
   */
  gaps: ScsPlotRegistrationGap[];
  /**
   * @maxItems 20
   */
  frameworkAssociationResults: ScsPlotFrameworkAssociationResult[];
  /**
   * @maxItems 200
   */
  decisionReasons: string[];
  decidedBy: ActorReference;
  decidedAt: string;
}
export interface ScsPlotEligibilityChecks {
  geometryValid: boolean;
  countryCodeValid: boolean;
  coordinateReferenceSystemRecognised: boolean;
  captureMethodRecorded: boolean;
  registrantAuthorised: boolean;
  noFatalOverlapDetected: boolean;
  tenureClaimsValid: boolean;
  claimantPartiesRegistered: boolean;
}
export interface ScsPlotRegistrationGap {
  gapCode:
    "REGISTRY_REFERENCE_MISSING" | "OVERLAP_NOT_EVALUATED" | "POINT_AREA_UNDECLARED" | "FRAMEWORK_ASSOCIATION_FAILED";
  gapDescription: string;
  automaticFailure: boolean;
  humanReviewRequired: boolean;
}
export interface ScsPlotFrameworkAssociationResult {
  frameworkId: string;
  associationId?: string;
  outcome: "ASSOCIATED" | "FAILED" | "PENDING_HUMAN_DECISION";
  failureCode?:
    | "FRAMEWORK_REFERENCE_NOT_FOUND"
    | "FRAMEWORK_NOT_ACTIVE"
    | "COMMODITY_OUTSIDE_FRAMEWORK"
    | "PRODUCER_PARTY_NOT_FOUND"
    | "PARTY_RETIRED";
  reason?: string;
}

/**
 * Immutable receipt for an SCS-CAP-03 plot registration decision, written in the same transaction as the decision (foundation/receipts.ts). Its SHA-256 over canonical JSON is returned alongside it as receiptDigest.
 */
export interface ScsPlotRegistrationReceipt {
  receiptId: string;
  receiptVersion: "1";
  capabilityId: "SCS-CAP-03";
  decisionType: "PLOT_REGISTRATION";
  /**
   * plotId of the registered plot.
   */
  subjectId: string;
  correlationId: string;
  /**
   * SHA-256 (hex) of the canonical request: method, route and body.
   */
  requestDigest: string;
  idempotencyKey: string | null;
  issuedAt: string;
  /**
   * The authenticated actor whose request produced this decision.
   */
  issuedFor: ActorReference;
  decision: ScsPlotRegistrationDecision;
}

/**
 * Body of a successful POST /scs/v1/plots (201): the registration decision, the immutable receipt that records it, and the receipt's SHA-256 over canonical JSON.
 */
export interface ScsPlotRegistrationResponse {
  decision: ScsPlotRegistrationDecision;
  receipt: ScsPlotRegistrationReceipt;
  receiptDigest: string;
}
