/* eslint-disable */
/**
 * GENERATED FILE — DO NOT EDIT BY HAND.
 * Generated by json-schema-to-typescript from:
 *   src/schemas/cap-06/sufficiency-evaluation-request.schema.json
 *   src/schemas/cap-06/sufficiency-evaluation-result.schema.json
 *   src/schemas/cap-06/sufficiency-evaluation-receipt.schema.json
 *   src/schemas/cap-06/sufficiency-evaluation-response.schema.json
 *   src/schemas/cap-06/sufficiency-evaluation-params.schema.json
 * To change these types, edit the schema(s) above, then run:
 *   npm run generate:types
 * npm test fails if this file differs from what the schemas generate.
 */

import type { ActorReference } from "./shared.js";

/**
 * SCS-CAP-06 ScsSufficiencyEvaluationSubmission (contract 0fd8c25, 876fc80). The system sets requestId, requestedBy, requestedAt, the referenceDate (the specification's referenceCutoffDate) and every result field. The evidence scope is the system's: a list given here must match it exactly. requestedAnalysis is recorded but never narrows the evaluation.
 */
export interface ScsSufficiencyEvaluationSubmission {
  subject: ScsSufficiencyEvaluationSubject;
  framework: ScsSufficiencyEvaluationFramework;
  evaluationPeriod: ScsSufficiencyEvaluationPeriodInput;
  evidenceScope: ScsSufficiencyEvidenceScopeInput;
  /**
   * @maxItems 7
   */
  requestedAnalysis: (
    | "TEMPORAL_COVERAGE"
    | "SPATIAL_COVERAGE"
    | "REQUIREMENT_BY_REQUIREMENT"
    | "CONFLICT_DETECTION"
    | "GAP_IDENTIFICATION"
    | "PROVENANCE_AND_AUTHORITY"
    | "CUSTODY_CHAIN"
  )[];
  previousEvaluationId?: string;
}
export interface ScsSufficiencyEvaluationSubject {
  /**
   * @minItems 1
   * @maxItems 500
   */
  plotIds: string[];
  /**
   * Each plot's version, which must be its current version.
   */
  plotVersions?: {
    [k: string]: number | undefined;
  };
  commodityCode: string;
  relevantProductCode?: string;
  /**
   * @minItems 1
   * @maxItems 100
   */
  batchIdentifiers?: string[];
  operatorPartyId?: string;
}
export interface ScsSufficiencyEvaluationFramework {
  frameworkId: string;
  frameworkVersion: string;
  evidenceRequirementSpecId: string;
}
export interface ScsSufficiencyEvaluationPeriodInput {
  /**
   * The due diligence date: after the cut-off, not in the future.
   */
  evaluationEndDate: string;
  assessmentType: "DEFORESTATION" | "FOREST_DEGRADATION" | "BOTH";
}
export interface ScsSufficiencyEvidenceScopeInput {
  /**
   * @maxItems 5000
   */
  admittedEvidenceIds?: string[];
  includeQuarantinedEvidence: false;
}

/**
 * SCS-CAP-06 ScsSufficiencyEvaluationResult (contract 0fd8c25, 876fc80). Advisory only: SUFFICIENT means sufficient under the evaluated specification, never legally compliant. A recorded result is never FAIL_CLOSED.
 */
export interface ScsSufficiencyEvaluationResult {
  evaluationId: string;
  requestId: string;
  evaluatedAt: string;
  evaluatorVersion: string;
  requestedBy: ActorReference;
  requestedAt: string;
  frameworkId: string;
  frameworkVersion: string;
  evidenceRequirementSpecId: string;
  /**
   * @maxItems 10000
   */
  plotIds: string[];
  commodityCode: string;
  /**
   * @maxItems 10000
   */
  batchIdentifiers: string[];
  operatorPartyId?: string;
  evaluationPeriod: ScsEvaluationPeriod;
  /**
   * @maxItems 7
   */
  requestedAnalysis: (
    | "TEMPORAL_COVERAGE"
    | "SPATIAL_COVERAGE"
    | "REQUIREMENT_BY_REQUIREMENT"
    | "CONFLICT_DETECTION"
    | "GAP_IDENTIFICATION"
    | "PROVENANCE_AND_AUTHORITY"
    | "CUSTODY_CHAIN"
  )[];
  evidenceCutoffAt: string;
  evaluatedEvidence: ScsEvaluatedEvidence;
  previousEvaluationId?: string;
  overallState: "SUFFICIENT" | "GAPS_REQUIRE_HUMAN_DECISION" | "INSUFFICIENT" | "CONFLICTING_EVIDENCE" | "FAIL_CLOSED";
  hasEvidenceGaps: boolean;
  hasMaterialUnresolvedConflicts: boolean;
  hasFailClosedConditions: boolean;
  /**
   * @maxItems 10000
   */
  requirementEvaluations: ScsRequirementEvaluation[];
  /**
   * @maxItems 10000
   */
  temporalCoverage: ScsTemporalCoverageEvaluation[];
  /**
   * @maxItems 10000
   */
  spatialCoverage: ScsSpatialCoverageEvaluation[];
  /**
   * @maxItems 10000
   */
  custodyChain?: ScsCustodyChainEvaluation[];
  /**
   * @maxItems 10000
   */
  allGaps: ScsEvidenceGap[];
  /**
   * @maxItems 10000
   */
  allConflicts: ScsEvidenceConflict[];
  /**
   * @maxItems 10000
   */
  evaluationExplanation: string[];
  /**
   * @maxItems 10000
   */
  nextSteps: ScsNextStep[];
  authorityBoundary: ScsSufficiencyAuthorityBoundary;
}
export interface ScsEvaluationPeriod {
  referenceDate: string;
  evaluationEndDate: string;
  assessmentType: "DEFORESTATION" | "FOREST_DEGRADATION" | "BOTH";
}
export interface ScsEvaluatedEvidence {
  /**
   * @maxItems 10000
   */
  deforestationEvidenceIds: string[];
  /**
   * @maxItems 10000
   */
  custodyEventIds: string[];
  /**
   * @maxItems 10000
   */
  manifest: ScsEvidenceManifestEntry[];
}
export interface ScsEvidenceManifestEntry {
  kind: "DEFORESTATION" | "CUSTODY";
  evidenceId: string;
  version: number;
  contentDigest: string;
  admittedAt: string;
}
export interface ScsRequirementEvaluation {
  requirementCode:
    | "DEF-TEMPORAL-COVERAGE"
    | "DEF-SPATIAL-COVERAGE"
    | "DEF-SOURCE-TYPE"
    | "DEF-RESOLUTION"
    | "DEF-RECENCY"
    | "DEF-INTEGRITY"
    | "DEF-AUTHORITY-CONFIRMATION"
    | "PLOT-REGISTERED"
    | "PLOT-GEOLOCATION"
    | "PLOT-LAND-REGISTRY"
    | "PLOT-OWNERSHIP-VERIFIED"
    | "PLOT-IDENTIFIER-TYPE"
    | "CUSTODY-CHAIN-CONTINUITY"
    | "CUSTODY-DOCUMENT-TYPES"
    | "CUSTODY-TRACEABILITY-DEPTH";
  evidenceRequirementSpecId: string;
  state:
    | "SATISFIED"
    | "PARTIALLY_SATISFIED"
    | "GAP_REQUIRES_HUMAN_DECISION"
    | "UNSATISFIED"
    | "CONFLICTING_EVIDENCE"
    | "NOT_APPLICABLE"
    | "FAIL_CLOSED";
  /**
   * @maxItems 10000
   */
  supportingEvidenceIds: string[];
  /**
   * @maxItems 10000
   */
  conflictingEvidenceIds: string[];
  /**
   * @maxItems 10000
   */
  gaps: ScsEvidenceGap[];
  /**
   * @maxItems 10000
   */
  conflicts: ScsEvidenceConflict[];
  evaluationExplanation: string;
  humanDecisionRequired: boolean;
  noComplianceDetermination: true;
}
export interface ScsEvidenceGap {
  gapId: string;
  requirementCode:
    | "DEF-TEMPORAL-COVERAGE"
    | "DEF-SPATIAL-COVERAGE"
    | "DEF-SOURCE-TYPE"
    | "DEF-RESOLUTION"
    | "DEF-RECENCY"
    | "DEF-INTEGRITY"
    | "DEF-AUTHORITY-CONFIRMATION"
    | "PLOT-REGISTERED"
    | "PLOT-GEOLOCATION"
    | "PLOT-LAND-REGISTRY"
    | "PLOT-OWNERSHIP-VERIFIED"
    | "PLOT-IDENTIFIER-TYPE"
    | "CUSTODY-CHAIN-CONTINUITY"
    | "CUSTODY-DOCUMENT-TYPES"
    | "CUSTODY-TRACEABILITY-DEPTH";
  gapType:
    | "TEMPORAL_INTERVAL_MISSING"
    | "SPATIAL_AREA_NOT_COVERED"
    | "REGISTRY_VERIFICATION_ABSENT"
    | "TENURE_VERIFICATION_ABSENT"
    | "ATTESTATION_ABSENT"
    | "ATTESTATION_WITHOUT_ANALYSIS"
    | "PROVENANCE_INCOMPLETE"
    | "EVIDENCE_TYPE_NOT_PROVIDED"
    | "AUTHORITY_CONFIRMATION_ABSENT"
    | "RESOLUTION_BELOW_REQUIREMENT"
    | "RECENCY_BELOW_REQUIREMENT"
    | "EVIDENCE_ABSENT"
    | "SPATIAL_COVERAGE_NOT_EVALUATED"
    | "OVERLAP_NOT_EVALUATED"
    | "COVERAGE_TYPE_NOT_EVALUATED"
    | "INTEGRITY_UNVERIFIED"
    | "PARTY_UNVERIFIED"
    | "PLOT_IDENTIFIER_TYPE_NOT_MET"
    | "PLOT_IDENTIFIER_TYPE_UNRECOGNISED"
    | "CUSTODY_CHAIN_BROKEN"
    | "CUSTODY_DOCUMENT_TYPE_MISSING"
    | "CUSTODY_STANDARD_NOT_EVALUATED"
    | "TRACEABILITY_DEPTH_NOT_EVALUATED"
    | "OTHER";
  subject: ScsEvidenceSubjectReference;
  uncoveredPeriod?: ScsUncoveredPeriod;
  uncoveredAreaReference?: string;
  uncoveredAreaPercent?: number;
  automaticFailure: boolean;
  humanDecisionRequired: boolean;
  explanation: string;
}
export interface ScsEvidenceSubjectReference {
  plotId?: string;
  subjectType: string;
  subjectReference?: string;
}
export interface ScsUncoveredPeriod {
  start: string;
  end: string;
  reason: string;
}
export interface ScsEvidenceConflict {
  conflictId: string;
  conflictKey: string;
  requirementCode:
    | "DEF-TEMPORAL-COVERAGE"
    | "DEF-SPATIAL-COVERAGE"
    | "DEF-SOURCE-TYPE"
    | "DEF-RESOLUTION"
    | "DEF-RECENCY"
    | "DEF-INTEGRITY"
    | "DEF-AUTHORITY-CONFIRMATION"
    | "PLOT-REGISTERED"
    | "PLOT-GEOLOCATION"
    | "PLOT-LAND-REGISTRY"
    | "PLOT-OWNERSHIP-VERIFIED"
    | "PLOT-IDENTIFIER-TYPE"
    | "CUSTODY-CHAIN-CONTINUITY"
    | "CUSTODY-DOCUMENT-TYPES"
    | "CUSTODY-TRACEABILITY-DEPTH";
  subject: ScsEvidenceSubjectReference;
  evidenceAId: string;
  evidenceBId: string;
  propositionA: string;
  propositionB: string;
  temporalOverlap?: ScsPeriod;
  spatialOverlapReference?: string;
  materiality: "NONE" | "APPARENT_BUT_COMPATIBLE" | "NON_MATERIAL" | "MATERIAL_RESOLVED" | "MATERIAL_UNRESOLVED";
  conflictType:
    | "OPPOSING_FINDINGS"
    | "INCOMPATIBLE_TEMPORAL_CLAIMS"
    | "INCOMPATIBLE_SPATIAL_CLAIMS"
    | "PROVENANCE_CONFLICT"
    | "METHOD_CONFLICT"
    | "AUTHORITY_CONFLICT"
    | "PLOT_VERSION_CONFLICT"
    | "QUANTITY_CONFLICT"
    | "OTHER";
  explanation: string;
  resolutionStatus: "UNRESOLVED" | "RESOLVED" | "REQUIRES_ADDITIONAL_EVIDENCE" | "REQUIRES_AUTHORITY_CONFIRMATION";
  resolutionDecisionId?: string;
}
export interface ScsPeriod {
  start: string;
  end: string;
}
export interface ScsTemporalCoverageEvaluation {
  plotId: string;
  requiredPeriod: ScsRequiredPeriod;
  /**
   * @maxItems 10000
   */
  supportedIntervals: ScsSupportedInterval[];
  /**
   * @maxItems 10000
   */
  uncoveredIntervals: ScsUncoveredInterval[];
  /**
   * @maxItems 10000
   */
  conflictingIntervals: ScsConflictingInterval[];
  /**
   * @maxItems 10000
   */
  attestationExceedingAnalysis: ScsAttestationExceedingAnalysis[];
  coverageNote: string;
}
export interface ScsRequiredPeriod {
  start: string;
  end: string;
  assessmentType: "DEFORESTATION" | "FOREST_DEGRADATION" | "BOTH";
}
export interface ScsSupportedInterval {
  start: string;
  end: string;
  /**
   * @maxItems 10000
   */
  evidenceIds: string[];
  coverageQuality: "HIGH" | "MEDIUM" | "LOW" | "UNASSESSED";
  supportType: string;
}
export interface ScsUncoveredInterval {
  start: string;
  end: string;
  reason: string;
  gapId: string;
}
export interface ScsConflictingInterval {
  start: string;
  end: string;
  conflictId: string;
  explanation: string;
}
export interface ScsAttestationExceedingAnalysis {
  evidenceId: string;
  attestedStart: string;
  attestedEnd: string;
  analysisStart: string;
  analysisEnd: string;
  explanation: string;
}
export interface ScsSpatialCoverageEvaluation {
  plotId: string;
  plotVersion: number;
  registeredGeometryReference: string;
  coveredAreaPercent?: number;
  uncoveredAreaPercent?: number;
  /**
   * @maxItems 10000
   */
  uncoveredAreaReferences: string[];
  /**
   * @maxItems 10000
   */
  excludedAreaReferences: string[];
  /**
   * @maxItems 10000
   */
  spatialConflictReferences: string[];
  coverageAssessment: "FULL" | "SUBSTANTIAL" | "PARTIAL" | "MINIMAL" | "NONE" | "NOT_EVALUATED";
  plotGeometryChangedSinceEvidence: boolean;
  geometryChangeNote?: string;
}
export interface ScsCustodyChainEvaluation {
  batchIdentifier: string;
  operatorPartyId: string;
  requiredDepth: "FIRST_SUPPLIER" | "FULL_CHAIN" | "RISK_PROPORTIONATE";
  /**
   * @maxItems 10000
   */
  eventIds: string[];
  chainAssessment: "CONTINUOUS" | "BROKEN" | "NOT_EVALUATED";
  /**
   * @maxItems 10000
   */
  breaks: ScsCustodyChainBreak[];
  /**
   * @maxItems 10000
   */
  documentTypesPresent: string[];
  /**
   * @maxItems 10000
   */
  documentTypesMissing: string[];
  /**
   * @maxItems 10000
   */
  conflictIds: string[];
}
export interface ScsCustodyChainBreak {
  afterEventId?: string;
  beforeEventId?: string;
  explanation: string;
  gapId: string;
}
export interface ScsNextStep {
  priority: "BLOCKING" | "SIGNIFICANT" | "ADVISORY";
  stepType:
    | "OBTAIN_TEMPORAL_EVIDENCE"
    | "OBTAIN_SPATIAL_EVIDENCE"
    | "RESOLVE_CONFLICT"
    | "HUMAN_DECISION_REQUIRED"
    | "OBTAIN_REGISTRY_VERIFICATION"
    | "CHALLENGE_ATTESTATION"
    | "OBTAIN_CUSTODY_EVIDENCE"
    | "OTHER";
  requirementCode:
    | "DEF-TEMPORAL-COVERAGE"
    | "DEF-SPATIAL-COVERAGE"
    | "DEF-SOURCE-TYPE"
    | "DEF-RESOLUTION"
    | "DEF-RECENCY"
    | "DEF-INTEGRITY"
    | "DEF-AUTHORITY-CONFIRMATION"
    | "PLOT-REGISTERED"
    | "PLOT-GEOLOCATION"
    | "PLOT-LAND-REGISTRY"
    | "PLOT-OWNERSHIP-VERIFIED"
    | "PLOT-IDENTIFIER-TYPE"
    | "CUSTODY-CHAIN-CONTINUITY"
    | "CUSTODY-DOCUMENT-TYPES"
    | "CUSTODY-TRACEABILITY-DEPTH";
  explanation: string;
}
export interface ScsSufficiencyAuthorityBoundary {
  advisoryOnly: true;
  noComplianceDetermination: true;
  noDueDiligenceStatementAuthority: true;
  noRegulatoryPromotionAuthority: true;
  sufficientMeansEvidenceSufficient: true;
  sufficientDoesNotMeanLegallyCompliant: true;
}

/**
 * Immutable receipt for an SCS-CAP-06 sufficiency evaluation, written in the same transaction as the evaluation (foundation/receipts.ts). Its SHA-256 over canonical JSON is returned alongside it as receiptDigest.
 */
export interface ScsSufficiencyEvaluationReceipt {
  receiptId: string;
  receiptVersion: "1";
  capabilityId: "SCS-CAP-06";
  decisionType: "SUFFICIENCY_EVALUATION";
  /**
   * evaluationId of the recorded evaluation.
   */
  subjectId: string;
  correlationId: string;
  /**
   * SHA-256 (hex) of the canonical request: method, route and body.
   */
  requestDigest: string;
  idempotencyKey: string | null;
  issuedAt: string;
  /**
   * The authenticated actor whose request produced this decision.
   */
  issuedFor: ActorReference;
  decision: ScsSufficiencyEvaluationResult;
}

/**
 * Body of a successful POST /scs/v1/sufficiency-evaluations (201): the evaluation result (as decision), the immutable receipt that records it, and the receipt's SHA-256 over canonical JSON.
 */
export interface ScsSufficiencyEvaluationResponse {
  decision: ScsSufficiencyEvaluationResult;
  receipt: ScsSufficiencyEvaluationReceipt;
  receiptDigest: string;
}

/**
 * Path parameters of GET /scs/v1/sufficiency-evaluations/:evaluationId.
 */
export interface ScsSufficiencyEvaluationPathParams {
  evaluationId: string;
}
