/* eslint-disable */
/**
 * GENERATED FILE — DO NOT EDIT BY HAND.
 * Generated by json-schema-to-typescript from:
 *   src/schemas/cap-01/framework-registration-request.schema.json
 *   src/schemas/cap-01/framework-registration-decision.schema.json
 *   src/schemas/cap-01/framework-registration-receipt.schema.json
 *   src/schemas/cap-01/framework-registration-response.schema.json
 * To change these types, edit the schema(s) above, then run:
 *   npm run generate:types
 * npm test fails if this file differs from what the schemas generate.
 */

import type { ActorReference } from "./shared.js";

export type NonBlankText = string;
/**
 * @maxItems 200
 */
export type TextList = NonBlankText[];

/**
 * SCS-CAP-01 registerFramework request: every ScsRegulatoryFramework field a submitter provides. Not in the request, because the system sets them: frameworkId, schemaVersion, registeredAt, registeredBy (from the authenticated actor), status (ACTIVE on registration), versionHistory (empty on registration), and the evidence specification's specId, generatedAt and generatedFromFrameworkVersion.
 */
export interface ScsFrameworkRegistrationRequest {
  /**
   * The registrant's attestation that the applicable national laws for this scope have been confirmed (SCS-CAP-01 RegisterFrameworkRequest). A declaration by the authorised registrant, not an independent confirmation. Required; registration proceeds only when it is true — false is refused with APPLICABLE_LAWS_UNCONFIRMED.
   */
  applicableLawsAttested: boolean;
  regulation: ScsFrameworkRegulationInput;
  scope: ScsFrameworkScopeInput;
  evidenceRequirements: ScsEvidenceRequirementSpecInput;
}
/**
 * What this framework governs (ScsRegulatoryFramework.regulation).
 */
export interface ScsFrameworkRegulationInput {
  regulationId: NonBlankText;
  regulationName: NonBlankText;
  regulationVersion: NonBlankText;
  regulationDate: string;
  regulatoryAuthority: NonBlankText;
  sourceReference: NonBlankText;
}
/**
 * Specific scope (ScsRegulatoryFramework.scope). effectiveTo, when given, must not be before effectiveFrom — enforced by the database.
 */
export interface ScsFrameworkScopeInput {
  commodityCode: NonBlankText;
  commodityName: NonBlankText;
  countryOfOrigin: NonBlankText;
  destinationMarket: NonBlankText;
  applicableNationalLaws: TextList;
  effectiveFrom: string;
  effectiveTo?: string;
}
/**
 * The ScsEvidenceRequirementSpec parameters, DECLARED by the authorised registrant. CAP-01 adds only the system-generated fields specId, generatedAt and generatedFromFrameworkVersion; the specification is immutable after registration. TODO(spec-derivation) — CONTRACT GAP: the SCS-CAP-01 canonical contract says the specification is generated at registration but defines no rules for deriving its values from the regulation, scope and commodity. Until those rules are specified in the contract, the values are declared, never derived; no derivation rules are invented here. The rules must be specified before a production implementation.
 */
export interface ScsEvidenceRequirementSpecInput {
  deforestationEvidence: ScsDeforestationEvidenceRequirementInput;
  custodyEvidence: ScsCustodyEvidenceRequirementInput;
  plotRequirements: ScsPlotRequirementInput;
  sufficiencyThreshold: ScsSufficiencyThresholdInput;
  specLimitations: TextList;
}
export interface ScsDeforestationEvidenceRequirementInput {
  referenceCutoffDate: string;
  requiredCoverageType: "FULL_PLOT_COVERAGE" | "REPRESENTATIVE_SAMPLE" | "RISK_BASED";
  acceptedSourceTypes: TextList;
  minimumResolutionMetres?: number;
  minimumRecencyDays?: number;
  integrityRequirement: "VERIFIED" | "VERIFIABLE";
  authorityConfirmationRequired: boolean;
}
export interface ScsCustodyEvidenceRequirementInput {
  requiredDocumentTypes: TextList;
  chainOfCustodyStandards: TextList;
  traceabilityDepth: "FIRST_SUPPLIER" | "FULL_CHAIN" | "RISK_PROPORTIONATE";
}
export interface ScsPlotRequirementInput {
  geolocationRequired: boolean;
  landRegistryRequired: boolean;
  minimumPlotIdentifierType: NonBlankText;
  ownershipVerificationRequired: boolean;
}
export interface ScsSufficiencyThresholdInput {
  allPlotsRegistered: boolean;
  allPlotsHaveDeforestationEvidence: boolean;
  custodyChainComplete: boolean;
  noUnresolvedGaps: boolean;
  humanReviewCompleted: boolean;
}

/**
 * SCS-CAP-01 ScsFrameworkRegistrationDecision, as defined in the canonical contract. Pilot rule: an eligibility check is true only if it was actually performed and passed; checks the contract gives no evaluation rule for are recorded false and named in decisionReasons as not evaluated.
 */
export interface ScsFrameworkRegistrationDecision {
  decisionId: string;
  /**
   * Identifier allocated to this registration attempt. When decision is REJECTED or REQUIRES_REVIEW no framework record exists under it.
   */
  frameworkId: string;
  decision: "REGISTERED" | "REJECTED" | "REQUIRES_REVIEW";
  eligibilityChecks: ScsFrameworkEligibilityChecks;
  /**
   * @maxItems 200
   */
  decisionReasons: string[];
  decidedBy: ActorReference;
  decidedAt: string;
}
export interface ScsFrameworkEligibilityChecks {
  regulationReferenceValid: boolean;
  commodityRecognised: boolean;
  countryOfOriginValid: boolean;
  destinationMarketValid: boolean;
  applicableLawsConfirmed: boolean;
  noConflictingFrameworkExists: boolean;
  registrantAuthorised: boolean;
}

/**
 * Immutable receipt for an SCS-CAP-01 framework registration decision, written in the same transaction as the decision (foundation/receipts.ts). Its SHA-256 over canonical JSON is returned alongside it as receiptDigest.
 */
export interface ScsFrameworkRegistrationReceipt {
  receiptId: string;
  receiptVersion: "1";
  capabilityId: "SCS-CAP-01";
  decisionType: "FRAMEWORK_REGISTRATION";
  /**
   * frameworkId of the registered framework; null when the decision registered nothing.
   */
  subjectId: string | null;
  correlationId: string;
  /**
   * SHA-256 (hex) of the canonical request: method, route and body.
   */
  requestDigest: string;
  idempotencyKey: string | null;
  issuedAt: string;
  /**
   * The authenticated actor whose request produced this decision.
   */
  issuedFor: ActorReference;
  decision: ScsFrameworkRegistrationDecision;
}

/**
 * Body of a successful POST /scs/v1/frameworks (201): the registration decision, the immutable receipt that records it, and the receipt's SHA-256 over canonical JSON.
 */
export interface ScsFrameworkRegistrationResponse {
  decision: ScsFrameworkRegistrationDecision;
  receipt: ScsFrameworkRegistrationReceipt;
  receiptDigest: string;
}
