/* eslint-disable */
/**
 * GENERATED FILE — DO NOT EDIT BY HAND.
 * Generated by json-schema-to-typescript from:
 *   src/schemas/cap-09/review-decision-request.schema.json
 *   src/schemas/cap-09/review-decision.schema.json
 *   src/schemas/cap-09/review-decision-receipt.schema.json
 *   src/schemas/cap-09/review-decision-response.schema.json
 *   src/schemas/cap-09/currency-assessment.schema.json
 *   src/schemas/cap-09/review-decision-params.schema.json
 *   src/schemas/cap-09/currency-assessment-request.schema.json
 *   src/schemas/cap-09/recorded-decision.schema.json
 * To change these types, edit the schema(s) above, then run:
 *   npm run generate:types
 * npm test fails if this file differs from what the schemas generate.
 */

import type { ActorReference } from "./shared.js";

/**
 * SCS-CAP-09 ScsReviewDecisionSubmission (contract ff6d3b8, a816101). The system sets decisionId, schemaVersion, decidedAt, the frozen context, reviewer.reviewerId, reviewer.authorityVerifiedAt, recordValidity, decisionReasons and authorityBoundary; currency is derived. Reasoning text may not be blank (checked by the capability: REASONING_INCOMPLETE).
 */
export interface ScsReviewDecisionSubmission {
  evaluationId: string;
  /**
   * SHA-256 of the canonical JSON of the evaluation result reviewed.
   */
  evaluationSnapshotDigest: string;
  frameworkId: string;
  frameworkVersion: string;
  commodityCode: string;
  operatorId: string;
  decisionOutcome:
    "PROCEED_TO_PACKAGE_COMPILATION" | "DO_NOT_PROCEED" | "REQUIRES_FURTHER_EVIDENCE" | "REQUIRES_SPECIALIST_REVIEW";
  reviewReasoning: ScsReviewReasoningInput;
  reviewer: ScsReviewerInput;
  supersedes?: ScsSupersedesInput;
}
export interface ScsReviewReasoningInput {
  evaluationSummaryAssessed: string;
  /**
   * @maxItems 1000
   */
  gapsConsidered: ScsReviewReasoningInputGap[];
  /**
   * @maxItems 1000
   */
  conflictsConsidered: ScsReviewReasoningInputConflict[];
  /**
   * @maxItems 200
   */
  limitationsAcknowledged: string[];
  basisForOutcome: string;
  /**
   * @maxItems 200
   */
  remainingConcerns?: string[];
  /**
   * @maxItems 200
   */
  conditionsIfAny?: string[];
}
export interface ScsReviewReasoningInputGap {
  gapId: string;
  assessment: string;
}
export interface ScsReviewReasoningInputConflict {
  conflictKey: string;
  assessment: string;
}
export interface ScsReviewerInput {
  reviewerName: string;
  reviewerOrganizationId: string;
  reviewerRoleReference: string;
  authorityBasis: string;
}
export interface ScsSupersedesInput {
  priorDecisionId: string;
  supersessionReason: string;
}

/**
 * SCS-CAP-09 ScsRegulatoryReviewDecision (contract ff6d3b8, a816101): a permanent, attributable human decision bound to the exact evaluation reviewed. It authorises a workflow step only. The currency fields are derived when the decision is read; the decision itself is never changed.
 */
export interface ScsRegulatoryReviewDecision {
  decisionId: string;
  schemaVersion: string;
  evaluationId: string;
  evaluationSnapshotDigest: string;
  frameworkId: string;
  frameworkVersion: string;
  evidenceRequirementSpecId: string;
  commodityCode: string;
  operatorId: string;
  /**
   * @maxItems 500
   */
  plotIds: string[];
  decisionOutcome:
    | "PROCEED_TO_PACKAGE_COMPILATION"
    | "DO_NOT_PROCEED"
    | "REQUIRES_FURTHER_EVIDENCE"
    | "REQUIRES_SPECIALIST_REVIEW"
    | "REVIEW_ABORTED_FAIL_CLOSED";
  reviewReasoning: ScsReviewReasoning;
  reviewer: ScsReviewer;
  decidedAt: string;
  recordValidity: "VALID" | "PROCEDURALLY_INVALID" | "UNDER_CHALLENGE" | "SUPERSEDED_BY_CORRECTION";
  currencyStatus: "CURRENT" | "POTENTIALLY_STALE" | "SUPERSEDED" | "FAIL_CLOSED";
  currencyLastAssessedAt: string;
  /**
   * @maxItems 1000
   */
  stalenessReasons?: ScsStalenessReason[];
  supersededByDecisionId?: string;
  supersededAt?: string;
  supersedes?: ScsSupersedes;
  /**
   * @maxItems 50
   */
  decisionReasons: string[];
  authorityBoundary: ScsReviewAuthorityBoundary;
}
export interface ScsReviewReasoning {
  evaluationSummaryAssessed: string;
  /**
   * @maxItems 1000
   */
  gapsConsidered: ScsReviewReasoningGap[];
  /**
   * @maxItems 1000
   */
  conflictsConsidered: ScsReviewReasoningConflict[];
  /**
   * @maxItems 200
   */
  limitationsAcknowledged: string[];
  basisForOutcome: string;
  /**
   * @maxItems 200
   */
  remainingConcerns?: string[];
  /**
   * @maxItems 200
   */
  conditionsIfAny?: string[];
}
export interface ScsReviewReasoningGap {
  gapId: string;
  assessment: string;
}
export interface ScsReviewReasoningConflict {
  conflictKey: string;
  assessment: string;
}
export interface ScsReviewer {
  reviewerId: string;
  reviewerName: string;
  reviewerOrganizationId: string;
  reviewerRoleReference: string;
  authorityBasis: string;
  authorityVerifiedAt: string;
}
export interface ScsStalenessReason {
  changeType: string;
  changedAt: string;
  changedEntityId: string;
  explanation: string;
}
export interface ScsSupersedes {
  priorDecisionId: string;
  priorEvaluationId: string;
  priorDecisionOutcome:
    | "PROCEED_TO_PACKAGE_COMPILATION"
    | "DO_NOT_PROCEED"
    | "REQUIRES_FURTHER_EVIDENCE"
    | "REQUIRES_SPECIALIST_REVIEW"
    | "REVIEW_ABORTED_FAIL_CLOSED";
  priorDecidedAt: string;
  supersessionReason: string;
}
export interface ScsReviewAuthorityBoundary {
  authorisesWorkflowStepOnly: true;
  noComplianceDetermination: true;
  noRegulatorySubmissionAuthority: true;
  doesNotSubstituteForRegulatoryAcceptance: true;
  legalResponsibilityRemainsWithOperator: true;
}

/**
 * Immutable receipt for an SCS-CAP-09 review decision, with its currency as derived when it was decided, written in the same transaction (foundation/receipts.ts). Its SHA-256 over canonical JSON is returned alongside it as receiptDigest.
 */
export interface ScsReviewDecisionReceipt {
  receiptId: string;
  receiptVersion: "1";
  capabilityId: "SCS-CAP-09";
  decisionType: "REGULATORY_REVIEW_DECISION";
  /**
   * decisionId of the recorded decision.
   */
  subjectId: string;
  correlationId: string;
  /**
   * SHA-256 (hex) of the canonical request: method, route and body.
   */
  requestDigest: string;
  idempotencyKey: string | null;
  issuedAt: string;
  /**
   * The authenticated actor whose request produced this decision.
   */
  issuedFor: ActorReference;
  decision: ScsRegulatoryReviewDecision;
}

/**
 * Body of a successful POST /scs/v1/review-decisions (201): the decision, the immutable receipt that records it, and the receipt's SHA-256 over canonical JSON.
 */
export interface ScsReviewDecisionResponse {
  decision: ScsRegulatoryReviewDecision;
  receipt: ScsReviewDecisionReceipt;
  receiptDigest: string;
}

/**
 * SCS-CAP-09 ScsDecisionCurrencyAssessment (contract ff6d3b8, a816101): a recorded, attributable assessment of a decision's currency. It is not a decision and has no receipt.
 */
export interface ScsDecisionCurrencyAssessment {
  assessmentId: string;
  decisionId: string;
  assessedAt: string;
  assessedBy: ActorReference;
  currencyStatus: "CURRENT" | "POTENTIALLY_STALE" | "SUPERSEDED" | "FAIL_CLOSED";
  supersededByDecisionId?: string;
  /**
   * @maxItems 50
   */
  checksPerformed: ScsCurrencyCheck[];
  /**
   * @maxItems 1000
   */
  materialChanges: ScsMaterialChange[];
}
export interface ScsCurrencyCheck {
  checkType:
    | "NEW_EVIDENCE_ADMITTED"
    | "EVIDENCE_WITHDRAWN_OR_QUARANTINED"
    | "EVIDENCE_RECLASSIFIED"
    | "PLOT_IDENTITY_CHANGED"
    | "PLOT_BOUNDARY_CHANGED"
    | "TENURE_RECORD_CHANGED"
    | "REGISTRY_VERIFICATION_CHANGED"
    | "CONFLICT_RESOLUTION_ADDED_OR_WITHDRAWN"
    | "FRAMEWORK_VERSION_CHANGED"
    | "CAP06_EVALUATION_SUPERSEDED"
    | "EVIDENCE_INTEGRITY_CHALLENGED"
    | "OTHER";
  checkResult: "UNCHANGED" | "CHANGED" | "UNAVAILABLE";
  detail?: string;
}
export interface ScsMaterialChange {
  changeType:
    | "NEW_EVIDENCE_ADMITTED"
    | "EVIDENCE_WITHDRAWN_OR_QUARANTINED"
    | "EVIDENCE_RECLASSIFIED"
    | "PLOT_IDENTITY_CHANGED"
    | "PLOT_BOUNDARY_CHANGED"
    | "TENURE_RECORD_CHANGED"
    | "REGISTRY_VERIFICATION_CHANGED"
    | "CONFLICT_RESOLUTION_ADDED_OR_WITHDRAWN"
    | "FRAMEWORK_VERSION_CHANGED"
    | "CAP06_EVALUATION_SUPERSEDED"
    | "EVIDENCE_INTEGRITY_CHALLENGED"
    | "OTHER";
  changedAt: string;
  changedEntityId: string;
  explanation: string;
}

/**
 * Path parameters of GET /scs/v1/review-decisions/:decisionId and POST /scs/v1/review-decisions/:decisionId/currency-assessments.
 */
export interface ScsReviewDecisionPathParams {
  decisionId: string;
}

/**
 * Body of POST /scs/v1/review-decisions/:decisionId/currency-assessments: empty. The assessment is derived by the system.
 */
export interface ScsCurrencyAssessmentRequest {}

/**
 * An SCS-CAP-09 decision as recorded: ScsRegulatoryReviewDecision without its derived currency fields (currencyStatus, currencyLastAssessedAt, stalenessReasons, supersededByDecisionId, supersededAt), which depend on when the decision is read. SCS-CAP-08 packages this form (contract 4b1f05b).
 */
export interface ScsRecordedReviewDecision {
  decisionId: string;
  schemaVersion: string;
  evaluationId: string;
  evaluationSnapshotDigest: string;
  frameworkId: string;
  frameworkVersion: string;
  evidenceRequirementSpecId: string;
  commodityCode: string;
  operatorId: string;
  /**
   * @maxItems 500
   */
  plotIds: string[];
  decisionOutcome:
    | "PROCEED_TO_PACKAGE_COMPILATION"
    | "DO_NOT_PROCEED"
    | "REQUIRES_FURTHER_EVIDENCE"
    | "REQUIRES_SPECIALIST_REVIEW"
    | "REVIEW_ABORTED_FAIL_CLOSED";
  reviewReasoning: ScsRecordedReviewReasoning;
  reviewer: ScsRecordedReviewer;
  decidedAt: string;
  recordValidity: "VALID" | "PROCEDURALLY_INVALID" | "UNDER_CHALLENGE" | "SUPERSEDED_BY_CORRECTION";
  supersedes?: ScsRecordedSupersedes;
  /**
   * @maxItems 50
   */
  decisionReasons: string[];
  authorityBoundary: ScsRecordedReviewAuthorityBoundary;
}
export interface ScsRecordedReviewReasoning {
  evaluationSummaryAssessed: string;
  /**
   * @maxItems 1000
   */
  gapsConsidered: ScsRecordedReviewReasoningGap[];
  /**
   * @maxItems 1000
   */
  conflictsConsidered: ScsRecordedReviewReasoningConflict[];
  /**
   * @maxItems 200
   */
  limitationsAcknowledged: string[];
  basisForOutcome: string;
  /**
   * @maxItems 200
   */
  remainingConcerns?: string[];
  /**
   * @maxItems 200
   */
  conditionsIfAny?: string[];
}
export interface ScsRecordedReviewReasoningGap {
  gapId: string;
  assessment: string;
}
export interface ScsRecordedReviewReasoningConflict {
  conflictKey: string;
  assessment: string;
}
export interface ScsRecordedReviewer {
  reviewerId: string;
  reviewerName: string;
  reviewerOrganizationId: string;
  reviewerRoleReference: string;
  authorityBasis: string;
  authorityVerifiedAt: string;
}
export interface ScsRecordedSupersedes {
  priorDecisionId: string;
  priorEvaluationId: string;
  priorDecisionOutcome:
    | "PROCEED_TO_PACKAGE_COMPILATION"
    | "DO_NOT_PROCEED"
    | "REQUIRES_FURTHER_EVIDENCE"
    | "REQUIRES_SPECIALIST_REVIEW"
    | "REVIEW_ABORTED_FAIL_CLOSED";
  priorDecidedAt: string;
  supersessionReason: string;
}
export interface ScsRecordedReviewAuthorityBoundary {
  authorisesWorkflowStepOnly: true;
  noComplianceDetermination: true;
  noRegulatorySubmissionAuthority: true;
  doesNotSubstituteForRegulatoryAcceptance: true;
  legalResponsibilityRemainsWithOperator: true;
}
