/* eslint-disable */
/**
 * GENERATED FILE — DO NOT EDIT BY HAND.
 * Generated by json-schema-to-typescript from:
 *   src/schemas/cap-08/package-compilation-request.schema.json
 *   src/schemas/cap-08/due-diligence-package.schema.json
 *   src/schemas/cap-08/package-envelope.schema.json
 *   src/schemas/cap-08/package-compilation-record.schema.json
 *   src/schemas/cap-08/package-compilation-receipt.schema.json
 *   src/schemas/cap-08/package-compilation-response.schema.json
 * To change these types, edit the schema(s) above, then run:
 *   npm run generate:types
 * npm test fails if this file differs from what the schemas generate.
 */

import type { ScsSufficiencyEvaluationResult } from "./cap-06.js";
import type { ScsRecordedReviewDecision } from "./cap-09.js";
import type { ActorReference } from "./shared.js";

/**
 * SCS-CAP-08 ScsPackageCompilationSubmission (contract 4b1f05b, 901a600). The scope fields confirm what the compiler means to package: each must equal the review decision's; the evidence ids must equal the evaluation's manifest, as sets. The system sets requestId, requestedBy and requestedAt.
 */
export interface ScsPackageCompilationSubmission {
  reviewDecisionId: string;
  operatorId: string;
  frameworkId: string;
  frameworkVersion: string;
  commodityCode: string;
  /**
   * @minItems 1
   * @maxItems 500
   */
  plotIds: string[];
  evaluationId: string;
  /**
   * @maxItems 5000
   */
  deforestationEvidenceIds: string[];
  /**
   * @maxItems 5000
   */
  custodyEvidenceIds: string[];
  packageTitle?: string;
}

/**
 * SCS-CAP-08 package content (contract 4b1f05b, 901a600): everything digested. packageDigest is "sha256:" + the SHA-256 of its canonical JSON, so identical content always has the same digest. Compilation metadata (packageId, compiledAt, requestedByActorId, compiledByServiceIdentity) is outside it, in the envelope. It is not a compliance certificate, a declaration or a submission.
 */
export interface ScsDueDiligencePackage {
  schemaVersion: string;
  packageTitle?: string;
  compilationBasis: ScsPackageCompilationBasis;
  regulatoryFramework: ScsPackageRegulatoryFramework;
  operator: ScsPackageOperator;
  /**
   * @minItems 1
   * @maxItems 500
   */
  plots: ScsPackagePlot[];
  /**
   * @maxItems 5000
   */
  deforestationEvidence: ScsPackageDeforestationEvidence[];
  /**
   * @maxItems 5000
   */
  custodyEvidence: ScsPackageCustodyEvent[];
  sufficiencyEvaluation: ScsPackageSufficiencyEvaluation;
  reviewDecision: ScsPackageReviewDecision;
  gapDisclosure: ScsPackageGapDisclosure;
  /**
   * @maxItems 1000
   */
  packageLimitations: string[];
  authorityBoundary: ScsPackageAuthorityBoundary;
  challengeResponseMetadata: ScsPackageChallengeResponseMetadata;
}
export interface ScsPackageCompilationBasis {
  reviewDecisionId: string;
  evaluationId: string;
  frameworkId: string;
  frameworkVersion: string;
  evidenceRequirementSpecId: string;
  compilationVersion: string;
}
export interface ScsPackageRegulatoryFramework {
  frameworkId: string;
  frameworkVersion: string;
  regulationName: string;
  regulationVersion: string;
  regulatoryAuthority: string;
  commodityCode: string;
  commodityName: string;
  countryOfOrigin: string;
  destinationMarket: string;
  /**
   * @maxItems 1000
   */
  applicableNationalLaws: string[];
  evidenceRequirementSpecId: string;
  frameworkRegisteredAt: string;
}
export interface ScsPackageOperator {
  operatorId: string;
  operatorName: string;
  operatorOrganizationType: string;
  countryOfRegistration: string;
  countryOfOperation?: string;
  authorisedRepresentativeId?: string;
}
export interface ScsPackagePlot {
  plotId: string;
  plotVersion: number;
  plotName?: string;
  countryCode: string;
  /**
   * @maxItems 1000
   */
  administrativeAreas?: string[];
  geometryCaptureMethod: string;
  positionalAccuracyMetres?: number;
  registryVerificationStatus: string;
  overlapState: string;
  /**
   * @maxItems 10000
   */
  tenureClaims: ScsPackageTenureClaim[];
  frameworkAssociationId: string;
  registrationStatus: string;
  /**
   * @maxItems 10000
   */
  plotGaps: ScsPackagePlotGap[];
}
export interface ScsPackageTenureClaim {
  tenureClaimId: string;
  claimantType: string;
  tenureBasis: string;
  verificationStatus: string;
  /**
   * @maxItems 1000
   */
  limitations: string[];
}
export interface ScsPackagePlotGap {
  gapType: string;
  explanation: string;
}
export interface ScsPackageDeforestationEvidence {
  evidenceId: string;
  evidenceVersion: number;
  evidenceType: string;
  plotId: string;
  source: ScsPackageEvidenceSource;
  provenance: ScsPackageEvidenceProvenance;
  temporalCoverage: ScsPackageTemporalCoverage;
  spatialCoverage: ScsPackageSpatialCoverage;
  evidenceClaim: ScsPackageEvidenceClaim;
  admissionStatus: string;
  /**
   * @maxItems 1000
   */
  admissionLimitations: string[];
}
export interface ScsPackageEvidenceSource {
  sourceOrganizationId: string;
  sourceTitle?: string;
  providerName?: string;
  sourceReference: string;
  issuingAuthority?: string;
}
export interface ScsPackageEvidenceProvenance {
  submittedBy: string;
  submittedAt: string;
  contentDigest: string;
  integrityStatus: string;
  chainOfCustodyComplete: boolean;
}
export interface ScsPackageTemporalCoverage {
  acquisitionInstant?: string;
  acquisitionStart?: string;
  acquisitionEnd?: string;
  analysisPeriodStart?: string;
  analysisPeriodEnd?: string;
  attestedPeriodStart?: string;
  attestedPeriodEnd?: string;
  coverageMode: string;
  /**
   * @maxItems 10000
   */
  knownGapPeriods: ScsPackageKnownGapPeriod[];
}
export interface ScsPackageKnownGapPeriod {
  start: string;
  end: string;
  reason: string;
}
export interface ScsPackageSpatialCoverage {
  intersectionWithPlot: string;
  plotCoveragePercent?: number;
  spatialResolutionMetres?: number;
  /**
   * @maxItems 10000
   */
  excludedAreaIds: string[];
}
export interface ScsPackageEvidenceClaim {
  claimType: string;
  claimSummary: string;
  claimedPeriodStart?: string;
  claimedPeriodEnd?: string;
  confidence: string;
  /**
   * @maxItems 1000
   */
  limitations: string[];
}
export interface ScsPackageCustodyEvent {
  eventId: string;
  eventVersion: number;
  eventType: string;
  batchIdentifier: string;
  commodityCode: string;
  sourcePartyId: string;
  destinationPartyId: string;
  eventDate: string;
  timePrecision: string;
  quantity?: ScsPackageCustodyQuantity;
  supportingDocument: ScsPackageSupportingDocument;
  provenance: ScsPackageCustodyProvenance;
  /**
   * @maxItems 10000
   */
  sourcePlotIds: string[];
  /**
   * @maxItems 10000
   */
  links: ScsPackageCustodyLink[];
  /**
   * @maxItems 1000
   */
  uncertainties: string[];
  /**
   * @maxItems 1000
   */
  contradictions: string[];
  admissionStatus: string;
  /**
   * @maxItems 1000
   */
  admissionLimitations: string[];
}
export interface ScsPackageCustodyQuantity {
  amount: number;
  unit: string;
  measurementMethod: string;
}
export interface ScsPackageSupportingDocument {
  documentType: string;
  documentReference: string;
  contentDigest: string;
}
export interface ScsPackageCustodyProvenance {
  submittedBy: string;
  submittedAt: string;
  integrityStatus: string;
  chainOfCustodyComplete: boolean;
}
export interface ScsPackageCustodyLink {
  linkType: string;
  citedEventId: string;
  linkedEventId?: string;
}
export interface ScsPackageSufficiencyEvaluation {
  evaluationId: string;
  evaluationSnapshotDigest: string;
  evaluationReceiptDigest: string;
  result: ScsSufficiencyEvaluationResult;
}
export interface ScsPackageReviewDecision {
  decisionId: string;
  decision: ScsRecordedReviewDecision;
  decisionReceiptDigest: string;
  currencyStatusAtCompilation: "CURRENT";
  recordValidityAtCompilation: "VALID";
}
export interface ScsPackageGapDisclosure {
  totalGapsIdentified: number;
  /**
   * @maxItems 10000
   */
  blockingGaps: ScsPackageBlockingGap[];
  /**
   * @maxItems 10000
   */
  nonBlockingGaps: ScsPackageNonBlockingGap[];
  gapDisclosureStatement: string;
}
export interface ScsPackageBlockingGap {
  gapId: string;
  requirementCode: string;
  gapType: string;
  explanation: string;
  humanDecisionMade: boolean;
  humanDecisionId?: string;
  reviewerAssessment: string;
}
export interface ScsPackageNonBlockingGap {
  gapId: string;
  requirementCode: string;
  gapType: string;
  explanation: string;
  reviewerAssessment: string;
}
export interface ScsPackageAuthorityBoundary {
  compiledNotSubmitted: true;
  operatorMustMakeDeclaration: true;
  noComplianceDetermination: true;
  doesNotGuaranteeRegulatoryAcceptance: true;
  legalResponsibilityRemainsWithOperator: true;
  sufficientEvidenceDoesNotMeanLegallyCompliant: true;
  gapsDisclosedNotResolved: true;
}
export interface ScsPackageChallengeResponseMetadata {
  /**
   * @maxItems 10000
   */
  allEvidenceIds: string[];
  /**
   * @maxItems 10000
   */
  allProvenanceChains: ScsPackageProvenanceChain[];
  retrievableViaCapability: "SCS-CAP-10";
}
export interface ScsPackageProvenanceChain {
  evidenceId: string;
  evidenceKind: "DEFORESTATION" | "CUSTODY";
  admissionReceiptId: string;
  contentDigest: string;
  fileSha256Verified: boolean;
}

/**
 * What is stored and distributed (contract 4b1f05b): the package content, its digest, and the compilation metadata, which is outside the digest.
 */
export interface ScsDueDiligencePackageEnvelope {
  package: ScsDueDiligencePackage;
  packageDigest: string;
  compilationMetadata: ScsPackageCompilationMetadata;
}
export interface ScsPackageCompilationMetadata {
  packageId: string;
  compiledAt: string;
  requestedByActorId: string;
  compiledByServiceIdentity: string;
}

/**
 * SCS-CAP-08 compilation record (contract 4b1f05b, 901a600): governance evidence that a package was compiled through the gate, from which request, by whom, by which service, with which rendition. Not a distributable artefact. Only COMPILED is ever recorded.
 */
export interface ScsPackageCompilationDecision {
  compilationId: string;
  packageId: string;
  requestId: string;
  decision: "COMPILED";
  gateChecks: ScsPackageGateChecks;
  compiledAt: string;
  compiledBy: ActorReference;
  compiledByServiceIdentity: string;
  packageDigest: string;
  rendition: ScsPackageRenditionReference;
}
export interface ScsPackageGateChecks {
  reviewDecisionFound: true;
  outcomePermitsCompilation: true;
  recordIsValid: true;
  currencyIsCurrent: true;
  evaluationIdMatches: true;
  frameworkVersionMatches: true;
  plotIdsMatch: true;
  operatorIdMatches: true;
  commodityCodeMatches: true;
}
export interface ScsPackageRenditionReference {
  renditionId: string;
  mediaType: "application/pdf";
  sha256: string;
  rendererVersion: string;
}

/**
 * Immutable receipt for an SCS-CAP-08 compilation, written in the same transaction as the package (foundation/receipts.ts). Its decision is the compilation record, which binds the package's digest and compilation metadata. Its SHA-256 over canonical JSON is returned alongside it as receiptDigest.
 */
export interface ScsPackageCompilationReceipt {
  receiptId: string;
  receiptVersion: "1";
  capabilityId: "SCS-CAP-08";
  decisionType: "PACKAGE_COMPILATION";
  /**
   * packageId of the compiled package.
   */
  subjectId: string;
  correlationId: string;
  /**
   * SHA-256 (hex) of the canonical request: method, route and body.
   */
  requestDigest: string;
  idempotencyKey: string | null;
  issuedAt: string;
  /**
   * The authenticated actor whose request produced this decision.
   */
  issuedFor: ActorReference;
  decision: ScsPackageCompilationDecision;
}

/**
 * Body of a successful POST /scs/v1/due-diligence-packages (201): the compilation record, the package envelope, the receipt and its digest (contract 901a600).
 */
export interface ScsPackageCompilationResponse {
  decision: ScsPackageCompilationDecision;
  package: ScsDueDiligencePackageEnvelope;
  receipt: ScsPackageCompilationReceipt;
  receiptDigest: string;
}
