/* eslint-disable */
/**
 * GENERATED FILE — DO NOT EDIT BY HAND.
 * Generated by json-schema-to-typescript from:
 *   src/schemas/platform/key-registry-issuer.schema.json
 *   src/schemas/platform/key-registry-actor.schema.json
 *   src/schemas/platform/key-possession-statement.schema.json
 *   src/schemas/platform/key-registration-statement.schema.json
 *   src/schemas/platform/key-event-statement.schema.json
 *   src/schemas/platform/key-bootstrap-ceremony-statement.schema.json
 *   src/schemas/platform/key-registration-view.schema.json
 *   src/schemas/platform/key-verification-evidence.schema.json
 *   src/schemas/platform/key-bootstrap-request.schema.json
 *   src/schemas/platform/key-challenge-request.schema.json
 *   src/schemas/platform/key-registration-request.schema.json
 *   src/schemas/platform/key-event-request.schema.json
 *   src/schemas/platform/key-params.schema.json
 *   src/schemas/platform/key-signature-acceptance.schema.json
 *   src/schemas/platform/key-bootstrap-decision.schema.json
 *   src/schemas/platform/key-challenge-decision.schema.json
 *   src/schemas/platform/key-registration-decision.schema.json
 *   src/schemas/platform/key-event-decision.schema.json
 *   src/schemas/platform/key-bootstrap-receipt.schema.json
 *   src/schemas/platform/key-bootstrap-response.schema.json
 *   src/schemas/platform/key-challenge-receipt.schema.json
 *   src/schemas/platform/key-challenge-response.schema.json
 *   src/schemas/platform/key-registration-receipt.schema.json
 *   src/schemas/platform/key-registration-response.schema.json
 *   src/schemas/platform/key-event-receipt.schema.json
 *   src/schemas/platform/key-event-response.schema.json
 *   src/schemas/platform/key-read.schema.json
 * To change these types, edit the schema(s) above, then run:
 *   npm run generate:types
 * npm test fails if this file differs from what the schemas generate.
 */

import type { ActorReference } from "./shared.js";

/**
 * AAB-PLATFORM-09: an identity issuer, whose registry holds its own actors' keys (AAB-PLATFORM-03 issuer).
 */
export interface KeyRegistryIssuer {
  issuerType: "PLATFORM_CONTROL_PLANE" | "COUNTRY_TENANCY";
  /**
   * ISO 3166-1 alpha-2. Required for COUNTRY_TENANCY, absent for PLATFORM_CONTROL_PLANE.
   */
  countryCode?: string;
}

/**
 * AAB-PLATFORM-09: an actor as a signed statement names it, the pair (issuer, actorId) of AAB-PLATFORM-03.
 */
export interface KeyRegistryActor {
  issuer: KeyRegistryIssuer;
  actorId: string;
}

/**
 * AAB-PLATFORM-09 section 3: the proof of possession. Signed with the private key being registered, over the registry's single-use challenge.
 */
export interface KeyPossessionStatement {
  statementType: "SIGNING_KEY_POSSESSION";
  /**
   * Lowercase UUID.
   */
  keyId: string;
  actorId: string;
  issuer: KeyRegistryIssuer;
  publicKeyDigest: string;
  /**
   * Lowercase UUID.
   */
  challengeId: string;
  nonce: string;
}

/**
 * AAB-PLATFORM-09 section 3: what the registration authority signs. For a registry's first key (section 3a) the holder signs it with the key being registered.
 */
export interface KeyRegistrationStatement {
  statementType: "SIGNING_KEY_REGISTRATION";
  /**
   * Lowercase UUID.
   */
  keyId: string;
  actorId: string;
  issuer: KeyRegistryIssuer;
  publicKeyDigest: string;
  algorithm: "Ed25519";
  /**
   * Lowercase UUID.
   */
  challengeId: string;
  /**
   * Lowercase UUID.
   */
  signingKeyId: string;
  /**
   * Lowercase UUID.
   */
  replacesKeyId?: string;
  registrationAuthority: KeyRegistryActor;
}

/**
 * AAB-PLATFORM-09 section 4: a suspension, reinstatement or retirement, signed by the recorder with their own registered, active key.
 */
export interface KeyEventStatement {
  statementType: "SIGNING_KEY_EVENT";
  /**
   * Lowercase UUID.
   */
  keyId: string;
  eventType: "SUSPENDED" | "REINSTATED" | "RETIRED";
  reason: string;
  /**
   * Lowercase UUID.
   */
  signingKeyId: string;
  recordedBy: KeyRegistryActor;
}

/**
 * AAB-PLATFORM-09 section 3a and its amendments: the record of how a registry's first key is registered, signed by its holder with that key. The Platform Owner's ceremony declares the control plane's attestation key; a country's pins it and names the Platform Owner, who co-signs.
 */
export interface KeyBootstrapCeremonyStatement {
  statementType: "KEY_BOOTSTRAP_CEREMONY";
  registry: KeyRegistryIssuer;
  holder: KeyRegistryActor;
  /**
   * Lowercase UUID.
   */
  keyId: string;
  /**
   * Lowercase UUID.
   */
  challengeId: string;
  publicKeyDigest: string;
  record: {
    /**
     * @minItems 1
     */
    present: string[];
    procedure: string;
    performedAt: string;
  };
  declaredAttestationKey?: {
    /**
     * A key identifier in its issuer's registry.
     */
    attestationKeyId: string;
    /**
     * An Ed25519 public key, SPKI DER, standard base64.
     */
    publicKey: string;
  };
  pinnedAttestationKey?: {
    /**
     * A key identifier in its issuer's registry.
     */
    attestationKeyId: string;
    /**
     * An Ed25519 public key, SPKI DER, standard base64.
     */
    publicKey: string;
  };
  cosigner?: {
    actor: KeyRegistryActor;
    /**
     * The Platform Owner's accountable name, as they sign it in this statement: the only way it enters the country's record.
     */
    accountableName: string;
    /**
     * A key identifier in its issuer's registry.
     */
    signingKeyId: string;
  };
}

/**
 * AAB-PLATFORM-09 section 3: a key's registration as its registry holds it, as exported in verification evidence.
 */
export interface KeyRegistrationView {
  /**
   * A key identifier in its issuer's registry.
   */
  keyId: string;
  issuer: KeyRegistryIssuer;
  actorId: string;
  algorithm: "Ed25519";
  /**
   * An Ed25519 public key, SPKI DER, standard base64.
   */
  publicKey: string;
  publicKeyDigest: string;
  activeFrom: string;
  registeredAt: string;
  /**
   * A key identifier in its issuer's registry.
   */
  replacesKeyId?: string;
  registrationDigest: string;
}

/**
 * AAB-PLATFORM-09 section 9: another issuer's key, attested by its registry, carried with the record that needs it, so the record verifies with no call across the boundary. Attested at or before acceptance, at most 60 minutes before it.
 */
export interface KeyVerificationEvidence {
  issuer: KeyRegistryIssuer;
  /**
   * A key identifier in its issuer's registry.
   */
  keyId: string;
  registration: KeyRegistrationView;
  eventsAtAcceptance: {
    eventType: "SUSPENDED" | "REINSTATED" | "RETIRED";
    effectiveAt: string;
    recordedAt: string;
  }[];
  compromisedAtAcceptance: false;
  attestedAt: string;
  /**
   * Ed25519 signature over the statement's canonical JSON: 64 bytes, standard base64, made outside the server.
   */
  attestation: string;
  /**
   * A key identifier in its issuer's registry.
   */
  attestationKeyId: string;
}

/**
 * POST /aab/v1/key-bootstrap-ceremonies: a registry's first key (AAB-PLATFORM-09 section 3a). Three statements, each signed with the key being registered; for a country, the Platform Owner's co-signature and the attested evidence for their key.
 */
export interface KeyBootstrapRequest {
  /**
   * An Ed25519 public key, SPKI DER, standard base64.
   */
  publicKey: string;
  possessionStatement: KeyPossessionStatement;
  /**
   * Ed25519 signature over the statement's canonical JSON: 64 bytes, standard base64, made outside the server.
   */
  possessionSignature: string;
  registrationStatement: KeyRegistrationStatement;
  /**
   * Ed25519 signature over the statement's canonical JSON: 64 bytes, standard base64, made outside the server.
   */
  registrationSignature: string;
  ceremonyStatement: KeyBootstrapCeremonyStatement;
  /**
   * Ed25519 signature over the statement's canonical JSON: 64 bytes, standard base64, made outside the server.
   */
  holderSignature: string;
  /**
   * Ed25519 signature over the statement's canonical JSON: 64 bytes, standard base64, made outside the server.
   */
  cosignature?: string;
  cosignerKeyEvidence?: KeyVerificationEvidence;
}

/**
 * POST /aab/v1/key-registration-challenges: a single-use challenge, valid for 30 minutes, reserving the keyId for one actor's key (AAB-PLATFORM-09 section 3, second amendment).
 */
export interface KeyChallengeRequest {
  purpose: "BOOTSTRAP" | "REGISTRATION";
  actorId: string;
}

/**
 * POST /aab/v1/signing-keys: register a key (AAB-PLATFORM-09 section 3). The holder's proof of possession, and the registration authority's signed registration.
 */
export interface KeyRegistrationRequest {
  /**
   * An Ed25519 public key, SPKI DER, standard base64.
   */
  publicKey: string;
  possessionStatement: KeyPossessionStatement;
  /**
   * Ed25519 signature over the statement's canonical JSON: 64 bytes, standard base64, made outside the server.
   */
  possessionSignature: string;
  registrationStatement: KeyRegistrationStatement;
  /**
   * Ed25519 signature over the statement's canonical JSON: 64 bytes, standard base64, made outside the server.
   */
  registrationSignature: string;
}

/**
 * POST /aab/v1/signing-keys/:keyId/events: suspend, reinstate or retire a key (AAB-PLATFORM-09 section 4).
 */
export interface KeyEventRequest {
  eventStatement: KeyEventStatement;
  /**
   * Ed25519 signature over the statement's canonical JSON: 64 bytes, standard base64, made outside the server.
   */
  statementSignature: string;
}

/**
 * Path parameters of /aab/v1/signing-keys/:keyId.
 */
export interface KeyPathParams {
  keyId: string;
}

/**
 * AAB-PLATFORM-09 section 6: the signature a decision accepted: the server's own acceptedAt, the key it was verified with, and that key's digests.
 */
export interface KeySignatureAcceptance {
  acceptedAt: string;
  /**
   * Lowercase UUID.
   */
  signingKeyId: string;
  publicKeyDigest: string;
  registrationDigest: string;
}

/**
 * AAB-PLATFORM-09 section 3a: a registry's first key registered, in a recorded ceremony. Every check passed; a failed check refuses and writes nothing.
 */
export interface KeyBootstrapDecision {
  decisionId: string;
  decision: "BOOTSTRAPPED";
  ceremonyId: string;
  keyId: string;
  registry: KeyRegistryIssuer;
  ceremonyDigest: string;
  registrationDigest: string;
  publicKeyDigest: string;
  activeFrom: string;
  /**
   * A key identifier in its issuer's registry.
   */
  pinnedAttestationKeyId?: string;
  cosignatureAcceptance?: {
    acceptedAt: string;
    /**
     * A key identifier in its issuer's registry.
     */
    signingKeyId: string;
    publicKeyDigest: string;
    registrationDigest: string;
    evidenceDigest: string;
  };
  /**
   * @minItems 1
   */
  decisionReasons: string[];
  decidedBy: ActorReference;
  decidedAt: string;
}

/**
 * AAB-PLATFORM-09 section 3: a registration challenge issued.
 */
export interface KeyChallengeDecision {
  decisionId: string;
  decision: "ISSUED";
  challengeId: string;
  keyId: string;
  purpose: "BOOTSTRAP" | "REGISTRATION";
  issuer: KeyRegistryIssuer;
  actorId: string;
  nonce: string;
  issuedAt: string;
  expiresAt: string;
  /**
   * @minItems 1
   */
  decisionReasons: string[];
  decidedBy: ActorReference;
  decidedAt: string;
}

/**
 * AAB-PLATFORM-09 section 3: a key registered by a registration authority who is not its holder.
 */
export interface KeyRegistrationDecision {
  decisionId: string;
  decision: "REGISTERED";
  keyId: string;
  issuer: KeyRegistryIssuer;
  actorId: string;
  publicKeyDigest: string;
  activeFrom: string;
  replacesKeyId?: string;
  registrationDigest: string;
  signatureAcceptance: KeySignatureAcceptance;
  /**
   * @minItems 1
   */
  decisionReasons: string[];
  decidedBy: ActorReference;
  decidedAt: string;
}

/**
 * AAB-PLATFORM-09 section 4: a key event recorded.
 */
export interface KeyEventDecision {
  decisionId: string;
  decision: "RECORDED";
  eventId: string;
  keyId: string;
  eventType: "SUSPENDED" | "REINSTATED" | "RETIRED";
  effectiveAt: string;
  resultingState: "PENDING" | "ACTIVE" | "SUSPENDED" | "RETIRED";
  eventDigest: string;
  signatureAcceptance: KeySignatureAcceptance;
  /**
   * @minItems 1
   */
  decisionReasons: string[];
  decidedBy: ActorReference;
  decidedAt: string;
}

/**
 * Immutable receipt for an AAB-PLATFORM-09 KEY_BOOTSTRAP decision, written in the same transaction as the decision (foundation/receipts.ts); the registry record names it by receiptId.
 */
export interface KeyBootstrapReceipt {
  receiptId: string;
  receiptVersion: "1";
  capabilityId: "AAB-PLATFORM-09";
  decisionType: "KEY_BOOTSTRAP";
  /**
   * ceremonyId of the recorded ceremony.
   */
  subjectId: string;
  correlationId: string;
  /**
   * SHA-256 (hex) of the canonical request: method, concrete path and body.
   */
  requestDigest: string;
  idempotencyKey: string | null;
  issuedAt: string;
  /**
   * The authenticated actor whose request produced this decision.
   */
  issuedFor: ActorReference;
  decision: KeyBootstrapDecision;
}

/**
 * Body of a successful POST /aab/v1/key-bootstrap-ceremonies (201): the decision, its immutable receipt, and the receipt's SHA-256 over canonical JSON.
 */
export interface KeyBootstrapResponse {
  decision: KeyBootstrapDecision;
  receipt: KeyBootstrapReceipt;
  receiptDigest: string;
}

/**
 * Immutable receipt for an AAB-PLATFORM-09 KEY_REGISTRATION_CHALLENGE decision, written in the same transaction as the decision (foundation/receipts.ts); the registry record names it by receiptId.
 */
export interface KeyChallengeReceipt {
  receiptId: string;
  receiptVersion: "1";
  capabilityId: "AAB-PLATFORM-09";
  decisionType: "KEY_REGISTRATION_CHALLENGE";
  /**
   * challengeId of the issued challenge.
   */
  subjectId: string;
  correlationId: string;
  /**
   * SHA-256 (hex) of the canonical request: method, concrete path and body.
   */
  requestDigest: string;
  idempotencyKey: string | null;
  issuedAt: string;
  /**
   * The authenticated actor whose request produced this decision.
   */
  issuedFor: ActorReference;
  decision: KeyChallengeDecision;
}

/**
 * Body of a successful POST /aab/v1/key-registration-challenges (201): the decision, its immutable receipt, and the receipt's SHA-256 over canonical JSON.
 */
export interface KeyChallengeResponse {
  decision: KeyChallengeDecision;
  receipt: KeyChallengeReceipt;
  receiptDigest: string;
}

/**
 * Immutable receipt for an AAB-PLATFORM-09 KEY_REGISTRATION decision, written in the same transaction as the decision (foundation/receipts.ts); the registry record names it by receiptId.
 */
export interface KeyRegistrationReceipt {
  receiptId: string;
  receiptVersion: "1";
  capabilityId: "AAB-PLATFORM-09";
  decisionType: "KEY_REGISTRATION";
  /**
   * keyId of the registered key.
   */
  subjectId: string;
  correlationId: string;
  /**
   * SHA-256 (hex) of the canonical request: method, concrete path and body.
   */
  requestDigest: string;
  idempotencyKey: string | null;
  issuedAt: string;
  /**
   * The authenticated actor whose request produced this decision.
   */
  issuedFor: ActorReference;
  decision: KeyRegistrationDecision;
}

/**
 * Body of a successful POST /aab/v1/signing-keys (201): the decision, its immutable receipt, and the receipt's SHA-256 over canonical JSON.
 */
export interface KeyRegistrationResponse {
  decision: KeyRegistrationDecision;
  receipt: KeyRegistrationReceipt;
  receiptDigest: string;
}

/**
 * Immutable receipt for an AAB-PLATFORM-09 KEY_EVENT decision, written in the same transaction as the decision (foundation/receipts.ts); the registry record names it by receiptId.
 */
export interface KeyEventReceipt {
  receiptId: string;
  receiptVersion: "1";
  capabilityId: "AAB-PLATFORM-09";
  decisionType: "KEY_EVENT";
  /**
   * eventId of the recorded event.
   */
  subjectId: string;
  correlationId: string;
  /**
   * SHA-256 (hex) of the canonical request: method, concrete path and body.
   */
  requestDigest: string;
  idempotencyKey: string | null;
  issuedAt: string;
  /**
   * The authenticated actor whose request produced this decision.
   */
  issuedFor: ActorReference;
  decision: KeyEventDecision;
}

/**
 * Body of a successful POST /aab/v1/signing-keys/:keyId/events (201): the decision, its immutable receipt, and the receipt's SHA-256 over canonical JSON.
 */
export interface KeyEventResponse {
  decision: KeyEventDecision;
  receipt: KeyEventReceipt;
  receiptDigest: string;
}

/**
 * GET /aab/v1/signing-keys/:keyId (200): a key as registered, with its events and compromises, and its state derived now (AAB-PLATFORM-09 sections 4 and 8). Nothing is stored about its state.
 */
export interface KeyRead {
  registration: KeyRegistrationView;
  events: {
    eventType: "SUSPENDED" | "REINSTATED" | "RETIRED";
    effectiveAt: string;
    recordedAt: string;
  }[];
  compromises: {
    suspectedExposureFrom: string;
    recordedAt: string;
  }[];
  currentState: "PENDING" | "ACTIVE" | "SUSPENDED" | "RETIRED" | "COMPROMISED";
  retiredAt?: string;
  exposureWindow?: {
    from: string;
    until: string;
  };
  readAt: string;
}
