/* eslint-disable */
/**
 * GENERATED FILE — DO NOT EDIT BY HAND.
 * Generated by json-schema-to-typescript from:
 *   src/schemas/platform/evidence-object.schema.json
 *   src/schemas/platform/rendition-params.schema.json
 * To change these types, edit the schema(s) above, then run:
 *   npm run generate:types
 * npm test fails if this file differs from what the schemas generate.
 */

import type { ActorReference } from "./shared.js";

/**
 * SCS-PLATFORM-01 ScsEvidenceObject (contract 288bfd7): a stored evidence file, identified by the SHA-256 SCS computed over its bytes. Storing a file does not admit it as evidence.
 */
export interface ScsEvidenceObject {
  /**
   * Lowercase hexadecimal SHA-256 of the stored bytes, computed by SCS.
   */
  objectId: string;
  /**
   * The reference a capability cites: scs-object:sha256:<objectId>.
   */
  objectReference: string;
  contentDigest: ScsEvidenceObjectDigest;
  sizeBytes: number;
  /**
   * As declared at the first upload; not confirmed from the bytes.
   */
  mediaType:
    "image/tiff" | "image/png" | "image/jpeg" | "application/pdf" | "application/zip" | "application/octet-stream";
  storedAt: string;
  storedBy: ActorReference;
}
export interface ScsEvidenceObjectDigest {
  algorithm: "SHA-256";
  value: string;
}

/**
 * Path parameters of GET /scs/v1/renditions/:renditionId (SCS-PLATFORM-02).
 */
export interface ScsRenditionPathParams {
  renditionId: string;
}
