/* eslint-disable */
/**
 * GENERATED FILE — DO NOT EDIT BY HAND.
 * Generated by json-schema-to-typescript from:
 *   src/schemas/platform/evidence-object.schema.json
 *   src/schemas/platform/rendition-params.schema.json
 *   src/schemas/platform/subject-key.schema.json
 *   src/schemas/platform/actor-subject-link-actor.schema.json
 *   src/schemas/platform/actor-subject-link-statement.schema.json
 *   src/schemas/platform/actor-subject-link-statement-v2.schema.json
 *   src/schemas/platform/actor-subject-link.schema.json
 *   src/schemas/platform/actor-subject-link-status-statement.schema.json
 *   src/schemas/platform/actor-subject-link-status-statement-v2.schema.json
 *   src/schemas/platform/actor-subject-link-status-record.schema.json
 * To change these types, edit the schema(s) above, then run:
 *   npm run generate:types
 * npm test fails if this file differs from what the schemas generate.
 */

import type { ActorReference } from "./shared.js";

/**
 * AAB-PLATFORM-01 ScsEvidenceObject (contract 288bfd7): a stored evidence file, identified by the SHA-256 SCS computed over its bytes. Storing a file does not admit it as evidence.
 */
export interface ScsEvidenceObject {
  /**
   * Lowercase hexadecimal SHA-256 of the stored bytes, computed by SCS.
   */
  objectId: string;
  /**
   * The reference a capability cites: scs-object:sha256:<objectId>.
   */
  objectReference: string;
  contentDigest: ScsEvidenceObjectDigest;
  sizeBytes: number;
  /**
   * As declared at the first upload; not confirmed from the bytes.
   */
  mediaType:
    "image/tiff" | "image/png" | "image/jpeg" | "application/pdf" | "application/zip" | "application/octet-stream";
  storedAt: string;
  storedBy: ActorReference;
}
export interface ScsEvidenceObjectDigest {
  algorithm: "SHA-256";
  value: string;
}

/**
 * Path parameters of GET /scs/v1/renditions/:renditionId (AAB-PLATFORM-02).
 */
export interface ScsRenditionPathParams {
  renditionId: string;
}

/**
 * AAB-PLATFORM-04: a domain subject, named generically. The platform never reads what the identifiers mean; the domain's subject resolver does.
 */
export interface SubjectKey {
  domain: string;
  subjectType: string;
  subjectId: string;
}

/**
 * AAB-PLATFORM-04: an actor as a link names it, the pair (issuer, actorId) of AAB-PLATFORM-03. Used for the linked actor, a link's creator and a status record's writer.
 */
export interface ActorSubjectLinkActor {
  issuer: {
    issuerType: "PLATFORM_CONTROL_PLANE" | "COUNTRY_TENANCY";
    /**
     * ISO 3166-1 alpha-2. Required for COUNTRY_TENANCY, absent for PLATFORM_CONTROL_PLANE.
     */
    countryCode?: string;
  };
  actorId: string;
}

/**
 * AAB-PLATFORM-04 ActorSubjectLinkStatement: what a link's creator decides, and signs, before submitting. Every field is known before submission. The signed bytes are its canonical JSON.
 */
export interface ActorSubjectLinkStatement {
  statementType: "ACTOR_SUBJECT_LINK";
  actor: ActorSubjectLinkActor;
  subject: SubjectKey;
  relation: "IS_SUBJECT" | "ACTS_FOR_SUBJECT";
  validFrom: string;
  validUntil: string;
  /**
   * Evidence that the subject authorised the relationship: at least one AAB-PLATFORM-01 stored object.
   *
   * @minItems 1
   * @maxItems 20
   */
  authorisationEvidence: {
    /**
     * The AAB-PLATFORM-01 objectId: lowercase hex SHA-256 of the stored bytes.
     */
    evidenceObjectSha256: string;
    description: string;
  }[];
  supersedesLinkId?: string;
  creator: ActorSubjectLinkActor;
}

/**
 * AAB-PLATFORM-04 ActorSubjectLinkStatement: what a link's creator decides, and signs, before submitting. Every field is known before submission. The signed bytes are its canonical JSON. Version 2 (AAB-PLATFORM-04, third amendment of 2026-09-28): names the key the creator signs with, registered in the public-key registry (AAB-PLATFORM-09). A new version 1 statement is refused.
 */
export interface ActorSubjectLinkStatementV2 {
  statementType: "ACTOR_SUBJECT_LINK";
  actor: ActorSubjectLinkActor;
  subject: SubjectKey;
  relation: "IS_SUBJECT" | "ACTS_FOR_SUBJECT";
  validFrom: string;
  validUntil: string;
  /**
   * Evidence that the subject authorised the relationship: at least one AAB-PLATFORM-01 stored object.
   *
   * @minItems 1
   * @maxItems 20
   */
  authorisationEvidence: {
    /**
     * The AAB-PLATFORM-01 objectId: lowercase hex SHA-256 of the stored bytes.
     */
    evidenceObjectSha256: string;
    description: string;
  }[];
  supersedesLinkId?: string;
  creator: ActorSubjectLinkActor;
  statementVersion: "2";
  /**
   * The creator's key in the public-key registry, lowercase.
   */
  signingKeyId: string;
}

/**
 * AAB-PLATFORM-04 ActorSubjectLink: a write-once record binding one actor to one domain subject, as it (IS_SUBJECT) or for it (ACTS_FOR_SUBJECT). Its fields are the signed statement's; the server sets linkId, createdAt and createdBy, then linkDigest over everything else. It grants no authority. Its state is derived when read.
 */
export interface ActorSubjectLink {
  linkId: string;
  schemaVersion: "1";
  actor: ActorSubjectLinkActor;
  subject: SubjectKey;
  relation: "IS_SUBJECT" | "ACTS_FOR_SUBJECT";
  validFrom: string;
  validUntil: string;
  /**
   * Evidence that the subject authorised the relationship: at least one AAB-PLATFORM-01 stored object.
   *
   * @minItems 1
   * @maxItems 20
   */
  authorisationEvidence: {
    /**
     * The AAB-PLATFORM-01 objectId: lowercase hex SHA-256 of the stored bytes.
     */
    evidenceObjectSha256: string;
    description: string;
  }[];
  supersedesLinkId?: string;
  createdAt: string;
  /**
   * The creator: HUMAN, with accountableName (a governance decision); never the linked actor.
   */
  createdBy: ActorReference;
  /**
   * As signed: version 2, or version 1 for a record stored before the switch-over (read, never accepted again).
   */
  linkStatement: ActorSubjectLinkStatementV2 | ActorSubjectLinkStatement;
  /**
   * Ed25519 signature over the statement's canonical JSON: 64 bytes, standard base64.
   */
  statementSignature: string;
  /**
   * "sha256:" and the SHA-256 of the canonical JSON of every other field of the record.
   */
  linkDigest: string;
}

/**
 * AAB-PLATFORM-04 ActorSubjectLinkStatusStatement: what a status record's writer decides, and signs. It names the link's own linkDigest, so it binds the exact link it acts on.
 */
export interface ActorSubjectLinkStatusStatement {
  statementType: "ACTOR_SUBJECT_LINK_STATUS";
  linkId: string;
  linkDigest: string;
  action: "SUSPEND" | "REINSTATE" | "REVOKE";
  reason: string;
  writer: ActorSubjectLinkActor;
}

/**
 * AAB-PLATFORM-04 ActorSubjectLinkStatusStatement: what a status record's writer decides, and signs. It names the link's own linkDigest, so it binds the exact link it acts on. Version 2 (AAB-PLATFORM-04, third amendment of 2026-09-28): names the key the writer signs with, registered in the public-key registry (AAB-PLATFORM-09). A new version 1 statement is refused.
 */
export interface ActorSubjectLinkStatusStatementV2 {
  statementType: "ACTOR_SUBJECT_LINK_STATUS";
  linkId: string;
  linkDigest: string;
  action: "SUSPEND" | "REINSTATE" | "REVOKE";
  reason: string;
  writer: ActorSubjectLinkActor;
  statementVersion: "2";
  /**
   * The writer's key in the public-key registry, lowercase.
   */
  signingKeyId: string;
}

/**
 * AAB-PLATFORM-04 ActorSubjectLinkStatusRecord: SUSPEND, REINSTATE or REVOKE, written once against a link and never changed. Signed by the named human who writes it, never the linked actor.
 */
export interface ActorSubjectLinkStatusRecord {
  statusRecordId: string;
  linkId: string;
  schemaVersion: "1";
  /**
   * As signed: version 2, or version 1 for a record stored before the switch-over (read, never accepted again).
   */
  statusStatement: ActorSubjectLinkStatusStatementV2 | ActorSubjectLinkStatusStatement;
  /**
   * Ed25519 signature over the statement's canonical JSON: 64 bytes, standard base64.
   */
  statementSignature: string;
  writerCapacity: "CREATING_ROLE" | "SUBJECT_AUTHORITY";
  recordedAt: string;
  /**
   * HUMAN, with accountableName; never the linked actor.
   */
  writtenBy: ActorReference;
  /**
   * "sha256:" and the SHA-256 of the canonical JSON of every other field of the record.
   */
  recordDigest: string;
}
