/* eslint-disable */
/**
 * GENERATED FILE — DO NOT EDIT BY HAND.
 * Generated by json-schema-to-typescript from:
 *   src/schemas/shared/actor-reference.schema.json
 * To change these types, edit the schema(s) above, then run:
 *   npm run generate:types
 * npm test fails if this file differs from what the schemas generate.
 */

/**
 * PILOT DEFINITION. Every SCS canonical contract references ActorReference but none defines it (TODO(actor-reference)). This is the shape the pilot records wherever a contract says ActorReference; it must be confirmed in a shared contract before admission.
 */
export interface ActorReference {
  /**
   * Stable identifier of the person or service. Unique within the deployment.
   */
  actorId: string;
  /**
   * Whether the actor is a person or an automated service.
   */
  actorType: "HUMAN" | "SERVICE";
  /**
   * Roles held by the actor, e.g. COMPLIANCE_OFFICER. Capabilities decide which roles they accept.
   *
   * @maxItems 32
   */
  roles: string[];
  /**
   * Organisation the actor acts for, if any.
   */
  organizationId?: string;
  /**
   * How the actor was authenticated for this request. When OIDC replaces the pilot's static tokens, the shape of ActorReference does not change — only this value changes, from STATIC_TOKEN to OIDC.
   */
  authenticationMethod: "STATIC_TOKEN" | "OIDC";
}
