/* eslint-disable */
/**
 * GENERATED FILE — DO NOT EDIT BY HAND.
 * Generated by json-schema-to-typescript from:
 *   src/schemas/shared/actor-reference.schema.json
 *   src/schemas/shared/actor-reference-v1.schema.json
 *   src/schemas/shared/actor-reference-v2.schema.json
 * To change these types, edit the schema(s) above, then run:
 *   npm run generate:types
 * npm test fails if this file differs from what the schemas generate.
 */

/**
 * AAB-PLATFORM-03 ActorReference, as stored and read: version 1 (the pilot definition, no referenceVersion) or version 2. Every schema that records an actor references this one, so records of either version stay readable. New records are written as version 2 only.
 */
export type ActorReference = ActorReferenceV1 | ActorReferenceV2;

/**
 * ActorReference version 1: the SCS pilot's definition, with no referenceVersion field (AAB-PLATFORM-03, 'The pilot definition'). Every record stored before version 2 keeps it, unchanged, and it stays readable. New records are written as version 2. A reader treats roles as grants with scopeType DEPLOYMENT, organizationId as unverified, and the issuer as the deployment's own.
 */
export interface ActorReferenceV1 {
  /**
   * Stable identifier of the person or service. Unique within the deployment.
   */
  actorId: string;
  /**
   * Whether the actor is a person or an automated service.
   */
  actorType: "HUMAN" | "SERVICE";
  /**
   * Roles held by the actor, e.g. COMPLIANCE_OFFICER, unscoped. Capabilities decide which roles they accept.
   *
   * @maxItems 32
   */
  roles: string[];
  /**
   * Organisation the actor declared it acts for, if any. Unverified.
   */
  organizationId?: string;
  /**
   * How the actor was authenticated for this request.
   */
  authenticationMethod: "STATIC_TOKEN" | "OIDC";
}

/**
 * ActorReference version 2 (AAB-PLATFORM-03, section 1): who performed an act, which identity domain issued them, how they were authenticated, the authority grants resolved when the act was accepted, and, when present, the subject they acted for. Recorded with the act and never changed. The pair (issuer, actorId) identifies an actor across the platform.
 */
export interface ActorReferenceV2 {
  /**
   * Always "2". A reference without this field is version 1.
   */
  referenceVersion: "2";
  /**
   * Stable identifier of the person or service, unique within its issuer.
   */
  actorId: string;
  /**
   * The identity domain that authenticated the actor.
   */
  issuer: {
    issuerType: "PLATFORM_CONTROL_PLANE" | "COUNTRY_TENANCY";
    /**
     * ISO 3166-1 alpha-2. Required for COUNTRY_TENANCY, absent for PLATFORM_CONTROL_PLANE.
     */
    countryCode?: string;
  };
  /**
   * Whether the actor is a person or an automated service. A service never makes a governance decision.
   */
  actorType: "HUMAN" | "SERVICE";
  /**
   * How the actor was authenticated for this request.
   */
  authenticationMethod: "STATIC_TOKEN" | "OIDC";
  /**
   * The actor's name as the issuer records it. Present only for acts that require a named, accountable person (governance decisions); personal data otherwise left out.
   */
  accountableName?: string;
  /**
   * The authority grants resolved by the server when the act was accepted. Never taken from the client.
   *
   * @maxItems 64
   */
  authorityBasis: {
    role: string;
    scopeType: "PLATFORM" | "COUNTRY" | "INSTITUTION" | "DOMAIN" | "DEPLOYMENT" | "SUBJECT";
    /**
     * For SUBJECT: <domain>:<subjectType>:<subjectId>, for example SCS:PARTY:<partyId>.
     */
    scopeId: string;
    /**
     * The membership or grant record, where one exists. None in the pilot.
     */
    grantId?: string;
  }[];
  /**
   * Present only when the actor acts for a domain subject, under a basis the capability verified in the same transaction (AAB-PLATFORM-03, section 3).
   */
  representation?: {
    domain: string;
    subjectType: string;
    subjectId: string;
    actorLinkId: string;
    basis?: {
      basisType: string;
      basisId: string;
      onBehalfOfSubjectId: string;
    };
  };
}
