const STAC="https://planetarycomputer.microsoft.com/api/stac/v1/search";
const STATS="https://planetarycomputer.microsoft.com/api/data/v1/item/statistics";
const sr=(band:string)=>`(${band}*0.0000275-0.2)`,nir=sr("nir08"),red=sr("red"),green=sr("green"),blue=sr("blue"),swir=sr("swir16"),clear="((qa_pixel%64)==0)";
const CHANGE_EXPRESSIONS={ndvi:`where(${clear},(${nir}-${red})/(${nir}+${red}),0)`,ndmi:`where(${clear},(${nir}-${swir})/(${nir}+${swir}),0)`,ndwi:`where(${clear},(${green}-${nir})/(${green}+${nir}),0)`,bare_soil:`where(${clear},((${swir}+${red})-(${nir}+${blue}))/(${swir}+${red}+${nir}+${blue}),0)`} as const;
const crop=(id:string,bbox:number[],assets:string[])=>`https://planetarycomputer.microsoft.com/api/data/v1/item/bbox/${bbox.join(",")}/768x768.png?collection=landsat-c2-l2&item=${encodeURIComponent(id)}&${assets.map(asset=>`assets=${asset}`).join("&")}&rescale=7000%2C22000&color_formula=gamma+RGB+1.45%2C+saturation+1.25%2C+sigmoidal+RGB+6+0.4&return_mask=true&format=png`;
const cloudMask=(id:string,bbox:number[])=>{const query=new URLSearchParams({collection:"landsat-c2-l2",item:id,expression:"where((qa_pixel%64)==0,1,0)",asset_as_band:"true",colormap:JSON.stringify({"0":[0,0,0,0],"1":[255,255,255,255]}),format:"png"});query.append("assets","qa_pixel");return `https://planetarycomputer.microsoft.com/api/data/v1/item/bbox/${bbox.join(",")}/768x768.png?${query}`};
const overlap=(sceneBbox:number[],target:number[])=>{const width=Math.max(0,Math.min(sceneBbox[2],target[2])-Math.max(sceneBbox[0],target[0])),height=Math.max(0,Math.min(sceneBbox[3],target[3])-Math.max(sceneBbox[1],target[1])),area=Math.max(.0000001,(target[2]-target[0])*(target[3]-target[1]));return Math.min(100,width*height/area*100)};
const mosaicScenes=(features:any[],bbox:number[])=>{
  const cells=24,covered=new Set<number>(),selected=[] as any[],remaining=[...features];
  const cellCovered=(scene:any,index:number)=>{const x=index%cells,y=Math.floor(index/cells),cx=bbox[0]+(x+.5)*(bbox[2]-bbox[0])/cells,cy=bbox[1]+(y+.5)*(bbox[3]-bbox[1])/cells,b=scene.bbox??[];return b.length===4&&cx>=b[0]&&cx<=b[2]&&cy>=b[1]&&cy<=b[3]};
  while(remaining.length&&covered.size<cells*cells){let best=-1,gain=0;remaining.forEach((scene,sceneIndex)=>{let next=0;for(let cell=0;cell<cells*cells;cell++)if(!covered.has(cell)&&cellCovered(scene,cell))next++;if(next>gain){gain=next;best=sceneIndex}});if(best<0||gain===0)break;const [scene]=remaining.splice(best,1);selected.push(scene);for(let cell=0;cell<cells*cells;cell++)if(cellCovered(scene,cell))covered.add(cell)}
  // Spatial coverage alone can select one cloudy scene for a small governed
  // polygon. Retain additional low-cloud observations so QA_PIXEL masking can
  // reveal clear pixels from neighbouring acquisitions in the same window.
  for(const scene of remaining){
    if(selected.length>=12)break;
    if(overlap(scene.bbox??[],bbox)>0)selected.push(scene);
  }
  return {scenes:selected,coverage:covered.size/(cells*cells)*100};
};
const sceneView=(scenes:any[],bbox:number[],coverage:number)=>{const layers=(assets:string[])=>scenes.map(scene=>({image:crop(scene.id,bbox,assets),mask:cloudMask(scene.id,bbox),scene_id:scene.id,acquired_at:scene.properties?.datetime??null,cloud_cover_percent:Number(scene.properties?.["eo:cloud_cover"]??100)})),dates=scenes.map(scene=>scene.properties?.datetime).filter(Boolean).sort(),clouds=scenes.map(scene=>Number(scene.properties?.["eo:cloud_cover"])).filter(Number.isFinite),meanCloud=clouds.length?clouds.reduce((sum,value)=>sum+value,0)/clouds.length:null;return {scene_id:scenes.map(scene=>scene.id).join(" + "),scene_count:scenes.length,acquired_at:dates[0]??null,acquired_through:dates.at(-1)??null,cloud_cover_percent:meanCloud,clear_pixel_estimate:meanCloud==null?null:Math.max(0,coverage*(1-meanCloud/100)),cloud_mask:"LANDSAT_QA_PIXEL_BITS_0_TO_5_EXCLUDED",sensor:"Landsat mosaic",coverage_percent:coverage,render_bbox:bbox,alignment:"PIXEL_GRID_LOCKED_MOSAIC_TO_GOVERNED_TILE",preview_url:crop(scenes[0].id,bbox,["red","green","blue"]),image_layers:{natural:layers(["red","green","blue"]),vegetation:layers(["nir08","red","green"]),moisture:layers(["swir16","nir08","red"]),disturbance:layers(["swir22","swir16","red"])}}};
const validDay=(value:unknown,fallback:string)=>/^\d{2}-\d{2}$/.test(String(value))?String(value):fallback;

async function scenesFor(bbox:number[],datetime:string,limit:number){
  const response=await fetch(STAC,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({collections:["landsat-c2-l2"],bbox,datetime,limit,query:{"eo:cloud_cover":{lte:35}},sortby:[{field:"properties.eo:cloud_cover",direction:"asc"}]})});
  if(!response.ok)throw new Error(`Imagery catalogue returned HTTP ${response.status}`);
  return ((await response.json()) as any).features??[];
}

type ChangeMetric={ndvi:number|null;ndmi:number|null;ndwi:number|null;bare_soil:number|null};
async function measuredScene(sceneId:string,geometry:object){const url=new URL(STATS);url.searchParams.set("collection","landsat-c2-l2");url.searchParams.set("item",sceneId);url.searchParams.set("asset_as_band","true");url.searchParams.set("expression",Object.values(CHANGE_EXPRESSIONS).join(";"));url.searchParams.set("nodata","0");url.searchParams.set("max_size","256");const response=await fetch(url,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({type:"Feature",properties:{},geometry})});if(!response.ok)return null;const stats=((await response.json()) as any).properties?.statistics??{},first=stats[CHANGE_EXPRESSIONS.ndvi];if(!first?.valid_pixels||first.valid_pixels<25||typeof first.valid_percent!=="number")return null;const mean=(expression:string)=>typeof stats[expression]?.mean==="number"?stats[expression].mean:null;return{scene_id:sceneId,clear_pixels:first.valid_pixels,qa_clear_fraction:first.valid_percent/100,metrics:{ndvi:mean(CHANGE_EXPRESSIONS.ndvi),ndmi:mean(CHANGE_EXPRESSIONS.ndmi),ndwi:mean(CHANGE_EXPRESSIONS.ndwi),bare_soil:mean(CHANGE_EXPRESSIONS.bare_soil)} as ChangeMetric}}
const aggregateScenes=(observations:NonNullable<Awaited<ReturnType<typeof measuredScene>>>[])=>{if(!observations.length)return null;const total=observations.reduce((sum,item)=>sum+item.clear_pixels,0),mean=(key:keyof ChangeMetric)=>{const valid=observations.filter(item=>item.metrics[key]!=null),weight=valid.reduce((sum,item)=>sum+item.clear_pixels,0);return weight?valid.reduce((sum,item)=>sum+(item.metrics[key] as number)*item.clear_pixels,0)/weight:null};return{scene_id:observations.map(item=>item.scene_id).join(" + "),scene_count:observations.length,clear_pixels:total,qa_clear_fraction:observations.reduce((sum,item)=>sum+item.qa_clear_fraction*item.clear_pixels,0)/Math.max(1,total),metrics:{ndvi:mean("ndvi"),ndmi:mean("ndmi"),ndwi:mean("ndwi"),bare_soil:mean("bare_soil")} as ChangeMetric}};
const score=(metrics:ChangeMetric)=>{const values=[metrics.ndvi,metrics.ndmi,metrics.ndwi,metrics.bare_soil==null?null:-metrics.bare_soil].filter((value):value is number=>value!=null);return values.length?values.reduce((sum,value)=>sum+value,0)/values.length:null};
const metricDelta=(to:ChangeMetric,from:ChangeMetric):ChangeMetric=>({ndvi:to.ndvi==null||from.ndvi==null?null:to.ndvi-from.ndvi,ndmi:to.ndmi==null||from.ndmi==null?null:to.ndmi-from.ndmi,ndwi:to.ndwi==null||from.ndwi==null?null:to.ndwi-from.ndwi,bare_soil:to.bare_soil==null||from.bare_soil==null?null:to.bare_soil-from.bare_soil});

export async function POST(request:Request){
  const origin=request.headers.get("origin"),host=request.headers.get("host");
  if(origin&&host&&new URL(origin).host!==host)return Response.json({error:"Cross-origin request rejected."},{status:403});
  try{
    const body=await request.json() as {bbox?:number[];year?:number;mode?:string;start_year?:number;end_year?:number;window_start?:string;window_end?:string;baseline_date?:string;current_date?:string;geometry_geojson?:{type:"Polygon";coordinates:number[][][]};timeline?:{year:number;scene_ids:string[]}[]};
    const bbox=body.bbox,year=Math.max(1982,Math.min(new Date().getUTCFullYear(),Number(body.year)||new Date().getUTCFullYear()));
    if(!Array.isArray(bbox)||bbox.length!==4||!bbox.every(Number.isFinite))return Response.json({error:"Valid tile bounds required."},{status:400});
    if(bbox[0]<112.5||bbox[2]>129.1||bbox[1]<-35.3||bbox[3]>-13.2)return Response.json({error:"Time Travel is locked to Western Australia."},{status:400});
    if(body.mode==="change-analysis"){
      const geometry=body.geometry_geojson?.type==="Polygon"?body.geometry_geojson:{type:"Polygon",coordinates:[[[bbox[0],bbox[1]],[bbox[2],bbox[1]],[bbox[2],bbox[3]],[bbox[0],bbox[3]],[bbox[0],bbox[1]]]]};
      const requested=(body.timeline??[]).filter(point=>Number.isInteger(point.year)&&point.year>=1982&&point.year<=year).slice(0,45),points=[] as {year:number;scene_id:string;clear_pixels:number;qa_clear_fraction:number;metrics:ChangeMetric;score:number|null}[];
      for(let index=0;index<requested.length;index+=3){const batch=requested.slice(index,index+3);const measured=await Promise.all(batch.map(async point=>{const sceneIds=point.scene_ids.filter(id=>/^[A-Za-z0-9._-]{8,180}$/.test(id)).slice(0,6),observations=(await Promise.all(sceneIds.map(sceneId=>measuredScene(sceneId,geometry)))).filter((item):item is NonNullable<typeof item>=>Boolean(item)),observation=aggregateScenes(observations);return observation?{year:point.year,...observation,score:score(observation.metrics)}:null}));points.push(...measured.filter((point):point is NonNullable<typeof point>=>Boolean(point)))}
      if(points.length<2)return Response.json({analysis_available:false,evidence_status:"INSUFFICIENT_QA_SCREENED_OBSERVATIONS",observations_requested:requested.length,observations_computed:points.length,error:"At least two QA-screened yearly observations are required in the selected comparison interval."});
      points.sort((a,b)=>a.year-b.year);const first=points[0],last=points.at(-1)!,deltas=metricDelta(last.metrics,first.metrics),transitions=points.slice(1).map((point,index)=>{const previous=points[index],changes=[point.metrics.ndvi==null||previous.metrics.ndvi==null?null:point.metrics.ndvi-previous.metrics.ndvi,point.metrics.ndmi==null||previous.metrics.ndmi==null?null:point.metrics.ndmi-previous.metrics.ndmi,point.metrics.ndwi==null||previous.metrics.ndwi==null?null:point.metrics.ndwi-previous.metrics.ndwi,point.metrics.bare_soil==null||previous.metrics.bare_soil==null?null:point.metrics.bare_soil-previous.metrics.bare_soil].filter((value):value is number=>value!=null);return{from:previous.year,to:point.year,change:changes.length?changes.reduce((sum,value)=>sum+Math.abs(value),0)/changes.length:0}}),strongest=transitions.reduce((a,b)=>b.change>a.change?b:a),moisture=[deltas.ndmi,deltas.ndwi].filter((value):value is number=>value!=null),moistureDelta=moisture.length?moisture.reduce((sum,value)=>sum+value,0)/moisture.length:null,declining=(deltas.ndvi??0)<-.03&&((moistureDelta??0)<-.03||(deltas.bare_soil??0)>.03),improving=(deltas.ndvi??0)>.03&&((moistureDelta??0)>.03||(deltas.bare_soil??0)<-.03),pattern=declining?"ALIGNED DECLINING SPECTRAL SIGNAL":improving?"ALIGNED IMPROVING SPECTRAL SIGNAL":"MIXED OR VARIABLE SPECTRAL EVIDENCE",headline=`${pattern} between ${first.year} and ${last.year}.`;
      const possibilities=[] as string[];if((deltas.ndmi??0)<-.03||(deltas.ndwi??0)<-.03)possibilities.push("Reduced moisture, rainfall differences, drainage, drought or water-management change.");if((deltas.ndvi??0)<-.03)possibilities.push("Reduced vegetation cover or vigour, harvest, grazing, fire, land clearing or crop-cycle change.");if((deltas.bare_soil??0)>.03)possibilities.push("Greater exposed ground, disturbance, cultivation, excavation or reduced cover.");if(!possibilities.length)possibilities.push("Subtle seasonal, atmospheric, sensor or land-surface differences requiring further testing.");
      return Response.json({method_version:"AAB-LANDSAT-CHANGE-EVENT-2.0",evidence_status:"COMPUTED_UNVALIDATED",comparison_rule:"SCALED_SURFACE_REFLECTANCE_PER_PIXEL_QA_MASK_MULTI_SCENE_YEARLY_COMPOSITE",start_year:first.year,end_year:last.year,observations_requested:requested.length,observations_computed:points.length,points,deltas,pattern,headline,strongest_transition:strongest,possibilities,context_checks:[{name:"WA fire history",status:"NOT_CONNECTED",finding:"No fire attribution made. An official fire-boundary intersection must be checked before fire appears as an explanation."},{name:"Rainfall and drought",status:"NOT_CONNECTED",finding:"No climate attribution made. Comparable seasonal rainfall must be checked."},{name:"Land use and clearing",status:"NOT_CONNECTED",finding:"No land-use attribution made. A mapped boundary may explain a sharp persistent line."}],contradictions:["Vegetation, moisture and exposed-ground indices are interpreted separately; disagreement is reported as mixed evidence.","Different Landsat sensor generations may contribute residual spectral differences.","Every retained index pixel passed the QA_PIXEL fill, cloud, cirrus, shadow and snow screen.","Each yearly value combines up to six qualifying scenes; a visible line that moves between scenes is likely a mosaic seam.","A broad visual colour shift does not by itself establish environmental deterioration.","Missing years can conceal shorter recovery or disturbance events."],unknowns:["Causation is not established.","Rainfall, drought, fire and land-use records are not yet connected.","Field observations are required before condition or material claims."],confidence_percent:Math.min(82,28+points.length*1.1)},{headers:{"cache-control":"no-store"}});
    }
    if(body.mode==="comparison"){
      const parseDate=(value:unknown)=>{const parsed=new Date(String(value));return Number.isFinite(parsed.getTime())?parsed:null};
      const baseline=parseDate(body.baseline_date),current=parseDate(body.current_date);
      if(!baseline||!current)return Response.json({error:"Valid baseline and current observation dates required."},{status:400});
      const windowFor=(anchor:Date)=>{const end=new Date(anchor),start=new Date(anchor);start.setUTCDate(start.getUTCDate()-45);return `${start.toISOString()}/${end.toISOString()}`};
      const build=async(anchor:Date)=>{const found=await scenesFor(bbox,windowFor(anchor),100),mosaic=mosaicScenes(found,bbox);return mosaic.scenes.length>0&&mosaic.coverage>=98?sceneView(mosaic.scenes,bbox,mosaic.coverage):null};
      const [baselineScene,currentScene]=await Promise.all([build(baseline),build(current)]);
      return Response.json({comparison_rule:"SAME_GOVERNED_POLYGON_PIXEL_GRID_AND_QA_MASK",baseline:baselineScene,current:currentScene,imagery_available:Boolean(baselineScene&&currentScene),unavailable_reason:baselineScene&&currentScene?null:"Insufficient clear-pixel spatial coverage for a defensible governed mosaic."},{headers:{"cache-control":"public, max-age=3600"}});
    }
    if(body.mode==="timeline"){
      const start=Math.max(1982,Math.min(year,Number(body.start_year)||1982)),end=Math.max(start,Math.min(year,Number(body.end_year)||year));
      if(end-start>44)return Response.json({error:"Choose a period of 45 years or less."},{status:400});
      const windowStart=validDay(body.window_start,"06-01"),windowEnd=validDay(body.window_end,"07-31");
      const years=Array.from({length:end-start+1},(_,index)=>start+index);
      const timeline=[] as any[];
      for(let index=0;index<years.length;index+=5){
        const batch=years.slice(index,index+5);
        const results=await Promise.all(batch.map(async itemYear=>{const found=await scenesFor(bbox,`${itemYear}-${windowStart}T00:00:00Z/${itemYear}-${windowEnd}T23:59:59Z`,100),mosaic=mosaicScenes(found,bbox),complete=mosaic.scenes.length>0&&mosaic.coverage>=98;return {year:itemYear,scene:complete?sceneView(mosaic.scenes,bbox,mosaic.coverage):null,comparability:complete?"SEASONALLY_MATCHED_AND_SPATIALLY_ALIGNED":"MISSING_OR_PARTIAL_EVIDENCE"}}));
        timeline.push(...results);
      }
      return Response.json({start_year:start,end_year:end,window_start:windowStart,window_end:windowEnd,comparison_rule:"SAME_DATE_WINDOW_EACH_YEAR",timeline},{headers:{"cache-control":"public, max-age=3600"}});
    }
    const features=await scenesFor(bbox,`${year}-01-01T00:00:00Z/${year}-12-31T23:59:59Z`,100),mosaic=mosaicScenes(features,bbox);
    return Response.json({year,comparable_archive_start:1982,archive_imagery_start:1972,scenes:mosaic.coverage>=98?[sceneView(mosaic.scenes,bbox,mosaic.coverage)]:[]},{headers:{"cache-control":"public, max-age=3600"}});
  }catch(error){return Response.json({error:error instanceof Error?error.message:"Historical imagery search failed"},{status:500})}
}
