// JSON Schema validation (Ajv, draft 2020-12).
//
// validate(capabilityId, schema, value) returns either the value, typed as T,
// or a failure in the canonical error format (errors.ts):
//   error: "REQUEST_VALIDATION_FAILED", HTTP 400, one reason per problem.
//
// Fail-closed configuration — nothing is silently fixed up:
//   * strict mode: a schema with unknown keywords or loose typing does not compile
//   * allErrors: every problem is reported, not just the first
//   * no type coercion ("5" is not 5), no defaults inserted, no additional
//     properties removed — unknown fields are rejected by the schemas
//     (additionalProperties: false), never stripped
//   * formats are enforced (date, date-time, uuid, …)
//
// T must be the type generated from the same schema (types/ is generated by
// json-schema-to-typescript, never hand-written), so the static type and the
// runtime check describe the same shape.

import { Ajv2020 } from "ajv/dist/2020.js";
import type { ErrorObject, ValidateFunction } from "ajv";
import { createRequire } from "node:module";

import { capabilityPlatformFailure, toEnvelope, type CapabilityId, type FailureEnvelope, type ScsFailure } from "./errors.js";
import { requireCorrelationId } from "./correlation.js";

// ajv-formats is CommonJS with a `default` export; createRequire gives its
// real module value without ESM-interop guesswork.
const addFormats = createRequire(import.meta.url)("ajv-formats") as (ajv: Ajv2020, formats: readonly string[]) => Ajv2020;

/** Every schema must carry a unique $id — it is the compile-cache key. */
export type JsonSchema = Readonly<{ $id: string } & Record<string, unknown>>;

export type ValidationResult<T, C extends CapabilityId> =
  | { readonly ok: true; readonly value: T }
  | {
      readonly ok: false;
      readonly failure: ScsFailure<C, "REQUEST_VALIDATION_FAILED">;
      readonly envelope: FailureEnvelope<C, "REQUEST_VALIDATION_FAILED">;
    };

const MAX_REASONS = 50;

const ajv = new Ajv2020({
  strict: true,
  allErrors: true,
  coerceTypes: false,
  useDefaults: false,
  removeAdditional: false,
  validateFormats: true,
});
addFormats(ajv, ["date", "date-time", "uuid", "uri", "email"]);

const compiled = new Map<string, { source: string; fn: ValidateFunction }>();

function getValidator(schema: JsonSchema): ValidateFunction {
  const source = JSON.stringify(schema);
  const cached = compiled.get(schema.$id);
  if (cached) {
    if (cached.source !== source) {
      throw new Error(`Schema $id ${schema.$id} was already compiled with different content`);
    }
    return cached.fn;
  }
  const fn = ajv.compile(schema);
  compiled.set(schema.$id, { source, fn });
  return fn;
}

function describe(e: ErrorObject): string {
  const at = e.instancePath === "" ? "(root)" : e.instancePath;
  switch (e.keyword) {
    case "required":
      return `${at}: missing required property "${String(e.params["missingProperty"])}"`;
    case "additionalProperties":
      return `${at}: unknown property "${String(e.params["additionalProperty"])}" is not allowed`;
    case "enum":
      return `${at}: must be one of ${JSON.stringify(e.params["allowedValues"])}`;
    case "const":
      return `${at}: must be ${JSON.stringify(e.params["allowedValue"])}`;
    default:
      return `${at}: ${e.message ?? `failed ${e.keyword}`}`;
  }
}

export function validate<T, C extends CapabilityId>(capabilityId: C, schema: JsonSchema, value: unknown): ValidationResult<T, C> {
  const check = getValidator(schema);
  if (check(value)) return { ok: true, value: value as T };

  const all = (check.errors ?? []).map(describe);
  const reasons = all.length > MAX_REASONS
    ? [...all.slice(0, MAX_REASONS), `…and ${all.length - MAX_REASONS} more validation errors`]
    : all.length > 0 ? all : ["(root): value does not match the schema"];

  const failure = capabilityPlatformFailure(capabilityId, "REQUEST_VALIDATION_FAILED", reasons) as ScsFailure<C, "REQUEST_VALIDATION_FAILED">;
  return { ok: false, failure, envelope: toEnvelope(failure, requireCorrelationId()) };
}
