-- Source B. Live rehearsal database kdpcfbaeklkffozryjah, read through the Supabase connector on 2026-09-28. Schema only, no rows.
-- Read at 2026-09-28 07:30:53.092006+00 (UTC), PostgreSQL 17.6. Generated from the system catalogs, read only.
-- Schema: public. Grants: schema, table, column and function privileges, and default privileges.
-- Catalog counts for public: functions 35, tables 3, views 0, rls_enabled_tables 3, constraints 23, triggers 1, policies 0, indexes 10.
-- Evidence of what exists, not governed code. Never edited after commit.

-- schema public owner: pg_database_owner
GRANT USAGE ON SCHEMA public TO PUBLIC;
GRANT USAGE ON SCHEMA public TO anon;
GRANT USAGE ON SCHEMA public TO authenticated;
GRANT CREATE ON SCHEMA public TO pg_database_owner;
GRANT USAGE ON SCHEMA public TO pg_database_owner;
GRANT USAGE ON SCHEMA public TO postgres;
GRANT USAGE ON SCHEMA public TO service_role;
GRANT DELETE ON TABLE public.aab_country_participation_requests TO postgres;
GRANT INSERT ON TABLE public.aab_country_participation_requests TO postgres;
GRANT MAINTAIN ON TABLE public.aab_country_participation_requests TO postgres;
GRANT REFERENCES ON TABLE public.aab_country_participation_requests TO postgres;
GRANT SELECT ON TABLE public.aab_country_participation_requests TO postgres;
GRANT TRIGGER ON TABLE public.aab_country_participation_requests TO postgres;
GRANT TRUNCATE ON TABLE public.aab_country_participation_requests TO postgres;
GRANT UPDATE ON TABLE public.aab_country_participation_requests TO postgres;
GRANT DELETE ON TABLE public.aab_country_participation_requests TO service_role;
GRANT INSERT ON TABLE public.aab_country_participation_requests TO service_role;
GRANT MAINTAIN ON TABLE public.aab_country_participation_requests TO service_role;
GRANT REFERENCES ON TABLE public.aab_country_participation_requests TO service_role;
GRANT SELECT ON TABLE public.aab_country_participation_requests TO service_role;
GRANT TRIGGER ON TABLE public.aab_country_participation_requests TO service_role;
GRANT TRUNCATE ON TABLE public.aab_country_participation_requests TO service_role;
GRANT UPDATE ON TABLE public.aab_country_participation_requests TO service_role;
GRANT DELETE ON TABLE public.aab_spatial_investigation_area TO postgres;
GRANT INSERT ON TABLE public.aab_spatial_investigation_area TO postgres;
GRANT MAINTAIN ON TABLE public.aab_spatial_investigation_area TO postgres;
GRANT REFERENCES ON TABLE public.aab_spatial_investigation_area TO postgres;
GRANT SELECT ON TABLE public.aab_spatial_investigation_area TO postgres;
GRANT TRIGGER ON TABLE public.aab_spatial_investigation_area TO postgres;
GRANT TRUNCATE ON TABLE public.aab_spatial_investigation_area TO postgres;
GRANT UPDATE ON TABLE public.aab_spatial_investigation_area TO postgres;
GRANT DELETE ON TABLE public.aab_spatial_investigation_area TO service_role;
GRANT INSERT ON TABLE public.aab_spatial_investigation_area TO service_role;
GRANT MAINTAIN ON TABLE public.aab_spatial_investigation_area TO service_role;
GRANT REFERENCES ON TABLE public.aab_spatial_investigation_area TO service_role;
GRANT SELECT ON TABLE public.aab_spatial_investigation_area TO service_role;
GRANT TRIGGER ON TABLE public.aab_spatial_investigation_area TO service_role;
GRANT TRUNCATE ON TABLE public.aab_spatial_investigation_area TO service_role;
GRANT UPDATE ON TABLE public.aab_spatial_investigation_area TO service_role;
GRANT DELETE ON TABLE public.aab_spatial_investigation_run TO postgres;
GRANT INSERT ON TABLE public.aab_spatial_investigation_run TO postgres;
GRANT MAINTAIN ON TABLE public.aab_spatial_investigation_run TO postgres;
GRANT REFERENCES ON TABLE public.aab_spatial_investigation_run TO postgres;
GRANT SELECT ON TABLE public.aab_spatial_investigation_run TO postgres;
GRANT TRIGGER ON TABLE public.aab_spatial_investigation_run TO postgres;
GRANT TRUNCATE ON TABLE public.aab_spatial_investigation_run TO postgres;
GRANT UPDATE ON TABLE public.aab_spatial_investigation_run TO postgres;
GRANT DELETE ON TABLE public.aab_spatial_investigation_run TO service_role;
GRANT INSERT ON TABLE public.aab_spatial_investigation_run TO service_role;
GRANT MAINTAIN ON TABLE public.aab_spatial_investigation_run TO service_role;
GRANT REFERENCES ON TABLE public.aab_spatial_investigation_run TO service_role;
GRANT SELECT ON TABLE public.aab_spatial_investigation_run TO service_role;
GRANT TRIGGER ON TABLE public.aab_spatial_investigation_run TO service_role;
GRANT TRUNCATE ON TABLE public.aab_spatial_investigation_run TO service_role;
GRANT UPDATE ON TABLE public.aab_spatial_investigation_run TO service_role;
GRANT EXECUTE ON FUNCTION public.aab_accept_invitation(p_invitation_token text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.aab_accept_invitation(p_invitation_token text) TO postgres;
GRANT EXECUTE ON FUNCTION public.aab_accept_invitation(p_invitation_token text) TO service_role;
GRANT EXECUTE ON FUNCTION public.aab_accept_legal_document(p_document_version_id uuid, p_acceptance_statement text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.aab_accept_legal_document(p_document_version_id uuid, p_acceptance_statement text) TO postgres;
GRANT EXECUTE ON FUNCTION public.aab_accept_legal_document(p_document_version_id uuid, p_acceptance_statement text) TO service_role;
GRANT EXECUTE ON FUNCTION public.aab_acknowledge_rehearsal_document(p_acknowledgement_statement text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.aab_acknowledge_rehearsal_document(p_acknowledgement_statement text) TO postgres;
GRANT EXECUTE ON FUNCTION public.aab_acknowledge_rehearsal_document(p_acknowledgement_statement text) TO service_role;
GRANT EXECUTE ON FUNCTION public.aab_acknowledge_rehearsal_participant(p_invitation_token text, p_acknowledgement_statement text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.aab_acknowledge_rehearsal_participant(p_invitation_token text, p_acknowledgement_statement text) TO postgres;
GRANT EXECUTE ON FUNCTION public.aab_acknowledge_rehearsal_participant(p_invitation_token text, p_acknowledgement_statement text) TO service_role;
GRANT EXECUTE ON FUNCTION public.aab_admin_dashboard_snapshot() TO authenticated;
GRANT EXECUTE ON FUNCTION public.aab_admin_dashboard_snapshot() TO postgres;
GRANT EXECUTE ON FUNCTION public.aab_admin_dashboard_snapshot() TO service_role;
GRANT EXECUTE ON FUNCTION public.aab_admin_review_participation_request(p_request_id uuid, p_decision text, p_rationale text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.aab_admin_review_participation_request(p_request_id uuid, p_decision text, p_rationale text) TO postgres;
GRANT EXECUTE ON FUNCTION public.aab_admin_review_participation_request(p_request_id uuid, p_decision text, p_rationale text) TO service_role;
GRANT EXECUTE ON FUNCTION public.aab_admin_review_security_alert(p_alert_id uuid, p_status text, p_rationale text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.aab_admin_review_security_alert(p_alert_id uuid, p_status text, p_rationale text) TO postgres;
GRANT EXECUTE ON FUNCTION public.aab_admin_review_security_alert(p_alert_id uuid, p_status text, p_rationale text) TO service_role;
GRANT EXECUTE ON FUNCTION public.aab_admin_run_security_brain() TO authenticated;
GRANT EXECUTE ON FUNCTION public.aab_admin_run_security_brain() TO postgres;
GRANT EXECUTE ON FUNCTION public.aab_admin_run_security_brain() TO service_role;
GRANT EXECUTE ON FUNCTION public.aab_admin_security_snapshot() TO authenticated;
GRANT EXECUTE ON FUNCTION public.aab_admin_security_snapshot() TO postgres;
GRANT EXECUTE ON FUNCTION public.aab_admin_security_snapshot() TO service_role;
GRANT EXECUTE ON FUNCTION public.aab_apply_personal_wa_rehearsal_handoff(p_handoff_correlation_id uuid, p_source_request_id uuid, p_source_decision_id uuid, p_nominated_email text, p_document_sha256 text, p_storage_path text, p_plain_activation_code text, p_expires_at timestamp with time zone) TO postgres;
GRANT EXECUTE ON FUNCTION public.aab_apply_personal_wa_rehearsal_handoff(p_handoff_correlation_id uuid, p_source_request_id uuid, p_source_decision_id uuid, p_nominated_email text, p_document_sha256 text, p_storage_path text, p_plain_activation_code text, p_expires_at timestamp with time zone) TO service_role;
GRANT EXECUTE ON FUNCTION public.aab_apply_personal_wa_rehearsal_handoff(p_handoff_correlation_id uuid, p_source_request_id uuid, p_source_internal_nomination_id uuid, p_source_decision_id uuid, p_nominated_email text, p_document_sha256 text, p_storage_path text, p_plain_activation_code text, p_expires_at timestamp with time zone) TO postgres;
GRANT EXECUTE ON FUNCTION public.aab_apply_personal_wa_rehearsal_handoff(p_handoff_correlation_id uuid, p_source_request_id uuid, p_source_internal_nomination_id uuid, p_source_decision_id uuid, p_nominated_email text, p_document_sha256 text, p_storage_path text, p_plain_activation_code text, p_expires_at timestamp with time zone) TO service_role;
GRANT EXECUTE ON FUNCTION public.aab_claim_country_activation(p_activation_code text, p_workspace_name text, p_default_language text, p_timezone_name text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.aab_claim_country_activation(p_activation_code text, p_workspace_name text, p_default_language text, p_timezone_name text) TO postgres;
GRANT EXECUTE ON FUNCTION public.aab_claim_country_activation(p_activation_code text, p_workspace_name text, p_default_language text, p_timezone_name text) TO service_role;
GRANT EXECUTE ON FUNCTION public.aab_claim_rehearsal_participant_invitation(p_invitation_token text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.aab_claim_rehearsal_participant_invitation(p_invitation_token text) TO postgres;
GRANT EXECUTE ON FUNCTION public.aab_claim_rehearsal_participant_invitation(p_invitation_token text) TO service_role;
GRANT EXECUTE ON FUNCTION public.aab_finalize_country_activation(p_activation_code text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.aab_finalize_country_activation(p_activation_code text) TO postgres;
GRANT EXECUTE ON FUNCTION public.aab_finalize_country_activation(p_activation_code text) TO service_role;
GRANT EXECUTE ON FUNCTION public.aab_finalize_invited_membership() TO authenticated;
GRANT EXECUTE ON FUNCTION public.aab_finalize_invited_membership() TO postgres;
GRANT EXECUTE ON FUNCTION public.aab_finalize_invited_membership() TO service_role;
GRANT EXECUTE ON FUNCTION public.aab_finalize_rehearsal_participant(p_invitation_token text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.aab_finalize_rehearsal_participant(p_invitation_token text) TO postgres;
GRANT EXECUTE ON FUNCTION public.aab_finalize_rehearsal_participant(p_invitation_token text) TO service_role;
GRANT EXECUTE ON FUNCTION public.aab_issue_country_invitation(p_country_workspace_id uuid, p_organization_id uuid, p_invitee_name text, p_invite_email text, p_official_position text, p_proposed_role text, p_plain_token text, p_expires_at timestamp with time zone) TO authenticated;
GRANT EXECUTE ON FUNCTION public.aab_issue_country_invitation(p_country_workspace_id uuid, p_organization_id uuid, p_invitee_name text, p_invite_email text, p_official_position text, p_proposed_role text, p_plain_token text, p_expires_at timestamp with time zone) TO postgres;
GRANT EXECUTE ON FUNCTION public.aab_issue_country_invitation(p_country_workspace_id uuid, p_organization_id uuid, p_invitee_name text, p_invite_email text, p_official_position text, p_proposed_role text, p_plain_token text, p_expires_at timestamp with time zone) TO service_role;
GRANT EXECUTE ON FUNCTION public.aab_issue_rehearsal_institution_invitation(p_institution_name text, p_institution_type text, p_invitee_name text, p_invite_email text, p_official_position text, p_plain_token text, p_expires_at timestamp with time zone) TO authenticated;
GRANT EXECUTE ON FUNCTION public.aab_issue_rehearsal_institution_invitation(p_institution_name text, p_institution_type text, p_invitee_name text, p_invite_email text, p_official_position text, p_plain_token text, p_expires_at timestamp with time zone) TO postgres;
GRANT EXECUTE ON FUNCTION public.aab_issue_rehearsal_institution_invitation(p_institution_name text, p_institution_type text, p_invitee_name text, p_invite_email text, p_official_position text, p_plain_token text, p_expires_at timestamp with time zone) TO service_role;
GRANT EXECUTE ON FUNCTION public.aab_issue_rehearsal_team_invitation(p_invitee_name text, p_invite_email text, p_official_position text, p_role_code text, p_plain_token text, p_expires_at timestamp with time zone) TO authenticated;
GRANT EXECUTE ON FUNCTION public.aab_issue_rehearsal_team_invitation(p_invitee_name text, p_invite_email text, p_official_position text, p_role_code text, p_plain_token text, p_expires_at timestamp with time zone) TO postgres;
GRANT EXECUTE ON FUNCTION public.aab_issue_rehearsal_team_invitation(p_invitee_name text, p_invite_email text, p_official_position text, p_role_code text, p_plain_token text, p_expires_at timestamp with time zone) TO service_role;
GRANT EXECUTE ON FUNCTION public.aab_legal_onboarding_state() TO authenticated;
GRANT EXECUTE ON FUNCTION public.aab_legal_onboarding_state() TO postgres;
GRANT EXECUTE ON FUNCTION public.aab_legal_onboarding_state() TO service_role;
GRANT EXECUTE ON FUNCTION public.aab_publish_country_terms(p_country_workspace_id uuid, p_title text, p_version_label text, p_language_code text, p_storage_bucket text, p_storage_path text, p_document_sha256 text, p_effective_at timestamp with time zone, p_certification_statement text, p_material_change boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.aab_publish_country_terms(p_country_workspace_id uuid, p_title text, p_version_label text, p_language_code text, p_storage_bucket text, p_storage_path text, p_document_sha256 text, p_effective_at timestamp with time zone, p_certification_statement text, p_material_change boolean) TO postgres;
GRANT EXECUTE ON FUNCTION public.aab_publish_country_terms(p_country_workspace_id uuid, p_title text, p_version_label text, p_language_code text, p_storage_bucket text, p_storage_path text, p_document_sha256 text, p_effective_at timestamp with time zone, p_certification_statement text, p_material_change boolean) TO service_role;
GRANT EXECUTE ON FUNCTION public.aab_rehearsal_document_locator() TO authenticated;
GRANT EXECUTE ON FUNCTION public.aab_rehearsal_document_locator() TO postgres;
GRANT EXECUTE ON FUNCTION public.aab_rehearsal_document_locator() TO service_role;
GRANT EXECUTE ON FUNCTION public.aab_rehearsal_head_admin_authority() TO authenticated;
GRANT EXECUTE ON FUNCTION public.aab_rehearsal_head_admin_authority() TO postgres;
GRANT EXECUTE ON FUNCTION public.aab_rehearsal_head_admin_authority() TO service_role;
GRANT EXECUTE ON FUNCTION public.aab_rehearsal_institution_authority() TO authenticated;
GRANT EXECUTE ON FUNCTION public.aab_rehearsal_institution_authority() TO postgres;
GRANT EXECUTE ON FUNCTION public.aab_rehearsal_institution_authority() TO service_role;
GRANT EXECUTE ON FUNCTION public.aab_rehearsal_institution_dashboard() TO authenticated;
GRANT EXECUTE ON FUNCTION public.aab_rehearsal_institution_dashboard() TO postgres;
GRANT EXECUTE ON FUNCTION public.aab_rehearsal_institution_dashboard() TO service_role;
GRANT EXECUTE ON FUNCTION public.aab_rehearsal_onboarding_state() TO authenticated;
GRANT EXECUTE ON FUNCTION public.aab_rehearsal_onboarding_state() TO postgres;
GRANT EXECUTE ON FUNCTION public.aab_rehearsal_onboarding_state() TO service_role;
GRANT EXECUTE ON FUNCTION public.aab_rehearsal_participant_invitation_preview(p_invitation_token text) TO anon;
GRANT EXECUTE ON FUNCTION public.aab_rehearsal_participant_invitation_preview(p_invitation_token text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.aab_rehearsal_participant_invitation_preview(p_invitation_token text) TO postgres;
GRANT EXECUTE ON FUNCTION public.aab_rehearsal_participant_invitation_preview(p_invitation_token text) TO service_role;
GRANT EXECUTE ON FUNCTION public.aab_rehearsal_participant_state(p_invitation_token text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.aab_rehearsal_participant_state(p_invitation_token text) TO postgres;
GRANT EXECUTE ON FUNCTION public.aab_rehearsal_participant_state(p_invitation_token text) TO service_role;
GRANT EXECUTE ON FUNCTION public.aab_rehearsal_team_authority() TO authenticated;
GRANT EXECUTE ON FUNCTION public.aab_rehearsal_team_authority() TO postgres;
GRANT EXECUTE ON FUNCTION public.aab_rehearsal_team_authority() TO service_role;
GRANT EXECUTE ON FUNCTION public.aab_replace_pending_rehearsal_institution_invitation(p_invite_email text, p_plain_token text, p_expires_at timestamp with time zone) TO authenticated;
GRANT EXECUTE ON FUNCTION public.aab_replace_pending_rehearsal_institution_invitation(p_invite_email text, p_plain_token text, p_expires_at timestamp with time zone) TO postgres;
GRANT EXECUTE ON FUNCTION public.aab_replace_pending_rehearsal_institution_invitation(p_invite_email text, p_plain_token text, p_expires_at timestamp with time zone) TO service_role;
GRANT EXECUTE ON FUNCTION public.aab_resolve_entry() TO authenticated;
GRANT EXECUTE ON FUNCTION public.aab_resolve_entry() TO postgres;
GRANT EXECUTE ON FUNCTION public.aab_resolve_entry() TO service_role;
GRANT EXECUTE ON FUNCTION public.aab_save_onboarding_profile(p_full_name text, p_official_position text, p_institution_name text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.aab_save_onboarding_profile(p_full_name text, p_official_position text, p_institution_name text) TO postgres;
GRANT EXECUTE ON FUNCTION public.aab_save_onboarding_profile(p_full_name text, p_official_position text, p_institution_name text) TO service_role;
GRANT EXECUTE ON FUNCTION public.aab_submit_country_participation_request(p_request jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.aab_submit_country_participation_request(p_request jsonb) TO postgres;
GRANT EXECUTE ON FUNCTION public.aab_submit_country_participation_request(p_request jsonb) TO service_role;
GRANT EXECUTE ON FUNCTION public.aab_verify_rehearsal_handoff_secret(p_supplied_sha256 text) TO postgres;
GRANT EXECUTE ON FUNCTION public.aab_verify_rehearsal_handoff_secret(p_supplied_sha256 text) TO service_role;
GRANT EXECUTE ON FUNCTION public.rls_auto_enable() TO postgres;
GRANT EXECUTE ON FUNCTION public.rls_auto_enable() TO service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT SELECT ON SEQUENCES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT UPDATE ON SEQUENCES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT USAGE ON SEQUENCES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT SELECT ON SEQUENCES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT UPDATE ON SEQUENCES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT USAGE ON SEQUENCES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT SELECT ON SEQUENCES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT ON SEQUENCES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT UPDATE ON SEQUENCES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT UPDATE ON SEQUENCES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT USAGE ON SEQUENCES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT USAGE ON SEQUENCES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT ON SEQUENCES TO service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT SELECT ON SEQUENCES TO service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT UPDATE ON SEQUENCES TO service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT UPDATE ON SEQUENCES TO service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT USAGE ON SEQUENCES TO service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT USAGE ON SEQUENCES TO service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT DELETE ON TABLES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT INSERT ON TABLES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT MAINTAIN ON TABLES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT REFERENCES ON TABLES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT SELECT ON TABLES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT TRIGGER ON TABLES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT TRUNCATE ON TABLES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT UPDATE ON TABLES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT DELETE ON TABLES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT INSERT ON TABLES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT MAINTAIN ON TABLES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT REFERENCES ON TABLES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT SELECT ON TABLES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT TRIGGER ON TABLES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT TRUNCATE ON TABLES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT UPDATE ON TABLES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT DELETE ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT DELETE ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT INSERT ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT INSERT ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT MAINTAIN ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT MAINTAIN ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT REFERENCES ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT REFERENCES ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT SELECT ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT TRIGGER ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT TRIGGER ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT TRUNCATE ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT TRUNCATE ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT UPDATE ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT UPDATE ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT DELETE ON TABLES TO service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT DELETE ON TABLES TO service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT INSERT ON TABLES TO service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT INSERT ON TABLES TO service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT MAINTAIN ON TABLES TO service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT MAINTAIN ON TABLES TO service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT REFERENCES ON TABLES TO service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT REFERENCES ON TABLES TO service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT ON TABLES TO service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT SELECT ON TABLES TO service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT TRIGGER ON TABLES TO service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT TRIGGER ON TABLES TO service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT TRUNCATE ON TABLES TO service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT TRUNCATE ON TABLES TO service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT UPDATE ON TABLES TO service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT UPDATE ON TABLES TO service_role;
