(() => {
  'use strict';
  const $ = id => document.getElementById(id);
  const ACK = 'I acknowledge this test-only document for the sole purpose of rehearsing the AAB WA onboarding workflow.';
  const state = { config:null, client:null, session:null, captcha:'', widget:null, activationCode:'', onboarding:null };
  const show = (message='', error='') => { $('message').textContent=message; $('error').textContent=error; };
  const reveal = id => { for (const el of document.querySelectorAll('.panel > section')) el.hidden=true; $(id).hidden=false; };
  async function request(url, options={}) { const response=await fetch(url,options); let body=null; try{body=await response.json()}catch{} if(!response.ok) throw new Error(body?.message||body?.error_description||body?.error||`Request failed (${response.status})`); return body; }
  function saveSession(session){ if(!session?.access_token||!session?.refresh_token)throw new Error('Verification did not create a valid session.'); localStorage.setItem(`sb-${state.config.projectRef}-auth-token`,JSON.stringify(session)); state.session=session; }
  function loadSession(){ try{return JSON.parse(localStorage.getItem(`sb-${state.config.projectRef}-auth-token`)||'null')}catch{return null} }
  async function rpc(name,args={}){ const {data,error}=await state.client.rpc(name,args); if(error)throw error; return data; }
  async function route(){
    const s=await rpc('aab_rehearsal_onboarding_state'); state.onboarding=s;
    if(!s?.eligible) throw new Error('This verified account has no current controlled WA rehearsal activation.');
    if(!s.claimed){ reveal('claim'); $('activation-code').value=state.activationCode; show('Identity verified. Claim the pending activation.'); return; }
    if(!s.profile_complete){ reveal('profile'); show('Activation claimed. Complete the accountable profile.'); return; }
    if(!s.acknowledged){ reveal('document'); $('document-details').textContent=`${s.document.title} · ${s.document.version} · ${s.document.environment} · ${s.document.legal_effect}`; show('Profile recorded. Review and acknowledge the exact test document.'); return; }
    reveal('finalize'); show('All preliminary gates passed. Final server validation is ready.');
  }
  async function authenticated(){ state.session=loadSession(); if(!state.session?.access_token)return false; const {data,error}=await state.client.auth.setSession(state.session); if(error||!data?.session){localStorage.removeItem(`sb-${state.config.projectRef}-auth-token`);return false} state.session=data.session; await route(); return true; }
  async function setupIdentity(){ reveal('identity'); for(let i=0;i<50&&typeof window.turnstile?.render!=='function';i++)await new Promise(r=>setTimeout(r,100)); if(typeof window.turnstile?.render!=='function')throw new Error('Human verification service is unavailable.'); state.widget=window.turnstile.render('#turnstile-widget',{sitekey:state.config.turnstileSiteKey,theme:'dark',callback:t=>{state.captcha=t;$('send').disabled=false},'expired-callback':()=>{state.captcha='';$('send').disabled=true}}); show('Verify the nominated email address.'); }
  $('email-form').addEventListener('submit',async e=>{e.preventDefault();$('send').disabled=true;show('Sending the newest verification code…');try{await request(`${state.config.supabaseUrl}/auth/v1/otp`,{method:'POST',headers:{apikey:state.config.publishableKey,'Content-Type':'application/json'},body:JSON.stringify({email:$('email').value.trim().toLowerCase(),create_user:true,gotrue_meta_security:{captcha_token:state.captcha}})});$('email-form').hidden=true;$('code-form').hidden=false;show('Verification code sent. Keep this page open.')}catch(error){show('',error.message);window.turnstile?.reset(state.widget)}});
  $('code-form').addEventListener('submit',async e=>{e.preventDefault();show('Verifying the nominated identity…');try{const data=await request(`${state.config.supabaseUrl}/auth/v1/verify`,{method:'POST',headers:{apikey:state.config.publishableKey,'Content-Type':'application/json'},body:JSON.stringify({email:$('email').value.trim().toLowerCase(),token:$('code').value.trim(),type:'email'})});saveSession(data);await state.client.auth.setSession(data);await route()}catch(error){show('',error.message)}});
  $('claim-button').addEventListener('click',async()=>{state.activationCode=$('activation-code').value.trim();show('Claiming the single-use activation…');try{await rpc('aab_claim_country_activation',{p_activation_code:state.activationCode,p_workspace_name:$('workspace-name').value.trim(),p_default_language:$('language').value,p_timezone_name:$('timezone').value.trim()});location.hash='';await route()}catch(error){show('',error.message)}});
  $('profile-button').addEventListener('click',async()=>{show('Saving the accountable profile…');try{await rpc('aab_save_onboarding_profile',{p_full_name:$('full-name').value.trim(),p_official_position:$('position').value.trim(),p_institution_name:$('institution').value.trim()});await route()}catch(error){show('',error.message)}});
  $('open-document').addEventListener('click',async()=>{show('Retrieving the server-verified rehearsal document…');try{const response=await fetch(`${state.config.supabaseUrl}/functions/v1/wa-rehearsal-document`,{headers:{apikey:state.config.publishableKey,Authorization:`Bearer ${state.session.access_token}`}});if(!response.ok)throw new Error('The verified document could not be retrieved.');const blob=await response.blob();window.open(URL.createObjectURL(blob),'_blank','noopener,noreferrer');show('Document opened. Review it before acknowledging.')}catch(error){show('',error.message)}});
  $('ack-check').addEventListener('change',()=>{$('ack-button').disabled=!$('ack-check').checked});
  $('ack-button').addEventListener('click',async()=>{show('Recording the privacy-minimised acknowledgement receipt…');try{await rpc('aab_acknowledge_rehearsal_document',{p_acknowledgement_statement:ACK});await route()}catch(error){show('',error.message)}});
  $('finalize-button').addEventListener('click',async()=>{if(!state.activationCode){state.activationCode=prompt('Re-enter the single-use activation code to finalize:')?.trim()||''}if(!state.activationCode)return;show('Running the final server-controlled activation checks…');try{const result=await rpc('aab_finalize_country_activation',{p_activation_code:state.activationCode});if(!result?.ok||result.classification!=='PERSONAL_WA_REHEARSAL')throw new Error('Final response did not match the rehearsal contract.');location.replace('/aab-local/app/_rebuild/country-admin.html')}catch(error){show('',error.message)}});
  async function init(){try{state.activationCode=new URLSearchParams(location.hash.slice(1)).get('code')||'';state.config=await request('/api/aab-config/',{cache:'no-store'});state.client=window.supabase.createClient(state.config.supabaseUrl,state.config.publishableKey,{auth:{persistSession:false,autoRefreshToken:true,detectSessionInUrl:false}});if(!await authenticated())await setupIdentity()}catch(error){show('',error.message||'Controlled activation is unavailable.')}}
  init();
})();
