<?php
declare(strict_types=1);

header('X-Content-Type-Options: nosniff');
header('Referrer-Policy: strict-origin-when-cross-origin');
$path = trim((string)(parse_url($_SERVER['REQUEST_URI'] ?? '/', PHP_URL_PATH) ?? '/'), '/');

// Hostinger may expose the front controller as /index.php. Treat that explicit
// address exactly like the public root so both entry URLs render the homepage.
if ($path === 'index.php') {
    $path = '';
}

if ($path === 'api/aab-config') {
    header('Content-Type: application/json; charset=utf-8');
    header('Cache-Control: no-store');
    echo json_encode([
        'ok' => true,
        'url' => 'https://epjhsrflzeuqzastevtz.supabase.co',
        'publishableKey' => 'sb_publishable_kYiKij8nK0bJrI-xm3ylkg_mNQm7epA'
    ], JSON_UNESCAPED_SLASHES);
    exit;
}

if ($path === 'private-preview') {
    header('Location: /about/', true, 301);
    exit;
}

if ($path === 'about') {
    require __DIR__.'/about/index.php';
    exit;
}

$pages = [
    'what-is-aab' => ['The AAB platform','Scientific memory that remains understandable, challengeable and useful.','AAB helps countries preserve the reasoning around scientific work, not merely its final reports.','A country should never lose what its scientists learn.','Knowledge is often fragmented across institutions, projects, people and reporting cycles. AAB connects evidence, decisions, failures, contradictions, mechanisms and unresolved questions while protecting the authority of scientists and participating institutions.',[['Memory before certainty','AAB records what is known, why it is believed, what supports it, what challenges it and what remains unknown.'],['Reasoning with boundaries','The platform can organise evidence and expose relationships without silently turning possibility into scientific truth.'],['Country-owned participation','Countries can coordinate many trusted institutions inside defined authority, privacy and governance boundaries.'],['Human authority preserved','Scientists and authorised people remain responsible for review, approval and real-world decisions.']]],
    'how-aab-works' => ['The governed learning chain','From activity to evidence, from evidence to durable understanding.','AAB connects each step without erasing uncertainty or the people responsible for scientific judgement.','Every learning keeps its lineage.','Work begins inside an authorised country and institutional context. Evidence is collected, reviewed and connected to its source. Outcomes, failures and contradictions remain visible so later reasoning can be traced and challenged.',[['1. Define','Record the question, purpose, expected outcome, responsibilities and applicable governance before work begins.'],['2. Observe','Capture field reality, measurements, context and source material without silently rewriting prior records.'],['3. Review','Authorised scientists assess evidence quality, uncertainty, contradictions and whether an outcome is established.'],['4. Preserve','Store the reasoning chain so future teams can understand what happened, why and what still needs investigation.']]],
    'agriculture' => ['First proving domain','Agriculture turns field activity into governed scientific learning.','AAB connects formulation lineage, trials, plots, observations, outcomes and scientist review.','Learning continues beyond a successful result.','Agriculture is AAB’s first proving ground. Failed results remain visible. Contradictions become investigable. Missing evidence becomes an explicit knowledge gap, not false confidence.',[['Formulation lineage','Every derived version keeps its parent, change type, rationale, expected outcomes and ingredient-level WHY.'],['Trials and plots','Assigned work is tied to controlled trial context, plots, observation requirements and accountable participants.'],['Field reality','Observations capture what happened, including negative results, environmental context and unexpected outcomes.'],['Scientist review','Learning is promoted only through governed review. AAB supports reasoning but does not claim execution authority.']]],
    'countries' => ['National participation','One national workspace. Many trusted institutions. Clear authority.','Country participation begins with governance and an authorised relationship, not a generic account form.','A controlled country pathway.','An authorised representative first explores AAB and its responsibilities. Agreements, country data boundaries, official authority and nominated administrators are reviewed before a workspace is activated.',[['Explore and discuss','Decision-makers can request a private preview and assess fit before beginning a formal participation process.'],['Review responsibilities','Country agreements, governance obligations, permitted use and data boundaries are made explicit.'],['Nominate authority','Official country authority and administrators are verified and approved separately from account creation.'],['Configure and activate','The workspace remains in setup until required checks, institutions and governance controls are ready.']]],
    'institutions-researchers' => ['Institutions and researchers','Trusted participation is invitation-led and institution-bound.','Universities, research institutions, laboratories, regulators and approved partners participate as governed entities.','People do not forward profiles to create authority.','A country administrator invites an institution’s nominated official. Once verified and approved, its administrator can invite scientists and teams into defined roles, projects and workspaces.',[['Verified institution','The organisation is represented by a governed record with its type, country relationship, status and accountable officials.'],['Controlled invitations','Every invitation carries its country, institution, proposed role, inviter, scope and expiry.'],['Professional profiles','Qualifications and affiliations can be reviewed where a role requires professional or scientific trust.'],['Role-specific access','Administrators, scientists, field teams, reviewers and regulators receive only the access their responsibilities require.']]],
    'community-observations' => ['Community observation','A photograph can begin an investigation. It does not become a fact.','Public, farmer, student and teacher contributions enter a separate governed intake pathway.','Evidence candidate first.','A submission begins as a visual evidence candidate only. Consent, context, moderation and authorised scientific review determine whether it may support future evidence.',[['Email-verified contributor','Contributors verify their account by email. Phone numbers may be stored for contact, never as proof of identity.'],['Consent and context','The contributor confirms ownership, permitted use, relevant location privacy and requested context.'],['Governed moderation','Submissions may be accepted for review, quarantined or rejected without becoming scientific evidence.'],['Evidence eligibility','A separate authorised review is required before a contribution can support a scientific evidence pathway.']]],
    'governance-trust' => ['Governance and trust','Extremely intelligent. Never falsely certain.','AAB is designed to increase understanding while keeping evidence, uncertainty and authority visible.','Governance is part of the reasoning architecture.','AAB may identify contradictions, expose missing knowledge, connect mechanisms and support scientific reasoning. It does not silently convert a scenario into a fact, an AI output into human authority or an incomplete record into confidence.',[['Facts are not scenarios','Simulations, hypotheses and recommendations remain visibly distinct from validated observations and established outcomes.'],['No silent overwrite','Versions, reviews, acceptance records, changes and outcomes retain an auditable lineage.'],['Unknown remains unknown','Zero evidence is not confidence. Missing information becomes a named knowledge gap.'],['Authority is explicit','Accounts, roles and execution authority are separate. Scientists and authorised administrators retain responsibility.']]],
];

function mark(): string { return '<span class="brand-mark" aria-hidden="true"><i></i><i></i><i></i></span>'; }
function header_html(): string { return '<header class="site-header inner-header"><a class="brand" href="/" aria-label="AAB home">'.mark().'<span>AAB</span></a><button class="menu-toggle" data-menu-toggle aria-expanded="false">Menu</button><nav data-nav aria-label="Primary navigation"><a href="/about/">About AAB</a><a href="/how-aab-works">How AAB Works</a><a href="/agriculture">Agriculture</a><a href="/countries">Countries</a><a href="/institutions-researchers">Institutions</a><a href="/community-observations">Community</a><a href="/governance-trust">Governance</a></nav><a class="header-action" href="/enter-aab">Enter AAB <span>↗</span></a></header>'; }
function footer_html(): string { return '<footer><div class="footer-brand">'.mark().'<div><strong>AAB</strong><p>Governed Scientific Intelligence Infrastructure</p></div></div><div class="footer-links"><a href="/about/">About</a><a href="/agriculture">Agriculture</a><a href="/governance-trust">Governance</a><a href="/enter-aab">Access</a></div><p class="copyright">© 2026 AAB. Research and systems development stage.</p></footer>'; }
function esc(string $value): string { return htmlspecialchars($value, ENT_QUOTES, 'UTF-8'); }

$title = $path === '' ? 'AAB — Governed Scientific Intelligence' : 'AAB — '.ucwords(str_replace('-', ' ', $path));
$known = $path === '' || $path === 'enter-aab' || isset($pages[$path]);
if (!$known) http_response_code(404);
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=esc($title)?></title><meta name="description" content="AAB governed scientific intelligence infrastructure"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/site.css"><script src="/site.js" defer></script></head><body><main>
<?php if ($path === ''): ?>
<header class="site-header"><a class="brand" href="#top" aria-label="AAB home"><?=mark()?><span>AAB</span></a><button class="menu-toggle" data-menu-toggle aria-expanded="false">Menu</button><nav data-nav><a href="/about/">About AAB</a><a href="/how-aab-works">How AAB Works</a><a href="/agriculture">Agriculture</a><a href="/countries">Countries</a><a href="/governance-trust">Governance</a></nav><a class="header-action" href="/enter-aab">Enter AAB <span>↗</span></a></header>
<section class="hero" id="top"><div class="hero-glow"></div><div class="hero-copy"><p class="eyebrow"><span></span> Governed scientific intelligence</p><h1>A country should never lose what its scientists learn.</h1><p class="hero-lead">AAB helps countries connect scientific work, evidence, resources, failures and unresolved questions, while preserving human authority, institutional ownership and scientific uncertainty.</p><div class="hero-actions"><a class="button primary" href="/about/">About AAB ↗</a><a class="button secondary" href="/enter-aab">Choose your pathway</a></div><p class="assurance"><span>✓</span> Human-governed · Evidence-traceable · Uncertainty-preserving</p></div><div class="memory-orbit"><div class="orbit orbit-one"></div><div class="orbit orbit-two"></div><div class="memory-core"><span>National</span><strong>Scientific<br>Memory</strong><small>Continuously governed</small></div><span class="node node-a">Evidence</span><span class="node node-b">Unknowns</span><span class="node node-c">Outcomes</span><span class="node node-d">Mechanisms</span></div></section>
<section class="principle-bar"><span>Facts ≠ scenarios</span><span>Missing data → knowledge gap</span><span>No silent overwrite</span><span>Human authority preserved</span></section>
<section class="section intro"><div class="section-label">01, The platform</div><div class="intro-copy"><p class="eyebrow dark"><span></span> More than answers</p><h2>Infrastructure for what science learns, and what it still needs to learn.</h2><p class="large-copy">Scientific knowledge is often fragmented. AAB preserves the full reasoning chain so evidence remains understandable, challengeable and useful over time.</p></div><div class="question-grid"><?php foreach (['What is known?','Why is it believed?','What evidence supports it?','What contradicts it?','What failed?','What remains unknown?'] as $i=>$q): ?><article><span>0<?=$i+1?></span><p><?=esc($q)?></p></article><?php endforeach; ?></div></section>
<section class="dark-section"><div class="agri-copy"><p class="eyebrow"><span></span> First proving domain</p><h2>Agriculture turns field activity into governed scientific learning.</h2><p>AAB connects formulation lineage, trials, plots, observations, outcomes and scientist review. Failed results remain visible and missing evidence becomes an explicit knowledge gap.</p><a class="text-link" href="/how-aab-works">See how AAB works ↗</a></div><div class="loop-card"><?php foreach ([['01','Formulate','WHY recorded'],['02','Test','Trials & plots'],['03','Observe','Field reality'],['04','Review','Scientist authority'],['05','Learn','Memory preserved']] as $s): ?><div><span><?=$s[0]?></span><strong><?=$s[1]?></strong><small><?=$s[2]?></small></div><?php endforeach; ?></div></section>
<section class="pathways"><div class="pathways-heading"><p class="eyebrow"><span></span> One trusted front door</p><h2>Enter AAB through the pathway that matches your responsibility.</h2><p>Identity is verified first. Role, country, institution, onboarding and dashboard routing are resolved from protected server records.</p></div><div class="pathway-grid"><a class="pathway-card" href="/countries"><span>01</span><h3>Country participation</h3><p>For authorised national representatives exploring a governed country workspace.</p><strong>Understand the pathway ↗</strong></a><a class="pathway-card" href="/institutions-researchers"><span>02</span><h3>Accept an invitation</h3><p>For institution leaders, scientists, reviewers and approved team members.</p><strong>How invitations work ↗</strong></a><a class="pathway-card" href="/community-observations"><span>03</span><h3>Contribute an observation</h3><p>For participation in approved programs.</p><strong>See evidence safeguards ↗</strong></a><a class="pathway-card" href="/enter-aab"><span>04</span><h3>Existing user sign in</h3><p>For verified participants returning to their authorised AAB workspace.</p><strong>Sign-in pathway ↗</strong></a></div></section>
<?=footer_html()?>
<?php elseif ($path === 'enter-aab'): ?>
<?=header_html()?><section class="page-hero"><p class="eyebrow"><span></span>One trusted front door</p><h1>Enter AAB through the pathway that matches your responsibility.</h1><p>AAB verifies identity first, then resolves authority, onboarding and dashboard access from protected server records.</p></section>
<section class="page-section entry-page"><div class="entry-gateway" id="entry-gateway"><div class="entry-mode-list" role="tablist"><?php foreach ([['signin','Existing user','Return to your server-approved dashboard.'],['country','Head of Country','Claim an authorised country unlock code.'],['invitation','Accept invitation','Join your approved university or team.']] as $m): ?><button type="button" data-entry-mode="<?=$m[0]?>"><strong><?=$m[1]?></strong><span><?=$m[2]?></span></button><?php endforeach; ?></div><div class="entry-panel"><p class="entry-security">Server-resolved identity · No browser-assigned roles</p><form class="entry-form" id="entry-auth"><h2>Verify your identity</h2><p>Use the same email address that received your AAB unlock code or invitation.</p><label>Email address<input id="entry-email" type="email" autocomplete="email" required></label><label>Password<input id="entry-password" type="password" autocomplete="current-password" minlength="8" required></label><div class="entry-actions"><button class="entry-primary">Sign in securely</button><button type="button" class="entry-secondary" id="register-account">Create invited account</button></div></form><div id="entry-session-area" hidden><div class="entry-session"><div><small>Signed in as</small><strong id="signed-email"></strong></div><button type="button" id="sign-out">Sign out</button></div><div class="entry-alert" id="unverified-note">Verify this email before continuing.</div><div data-entry-panel="signin" class="entry-action-card"><h2>Continue to your dashboard</h2><p>AAB will derive your role, country, institution, onboarding state and destination from protected records.</p><button class="entry-primary" id="resolve-entry" data-governed-action>Resolve my entry path</button></div><form data-entry-panel="country" id="country-form" class="entry-form entry-action-card"><h2>Activate your country workspace</h2><label>Authorised unlock code<input id="country-code" minlength="8" required></label><label>Workspace name (optional)<input id="workspace-name"></label><button class="entry-primary" data-governed-action>Verify and continue to settings</button></form><form data-entry-panel="invitation" id="invitation-form" class="entry-form entry-action-card"><h2>Accept your invitation</h2><label>Secure invitation token<input id="invitation-token" required></label><button class="entry-primary" data-governed-action>Accept and resolve dashboard</button></form></div><p class="entry-message" id="entry-message" aria-live="polite">Preparing the secure entry service…</p><p class="entry-error" id="entry-error" role="alert"></p></div></div><div class="entry-governance-note"><strong>Authority remains protected</strong><p>Your browser cannot choose a role, country, university or dashboard. Invalid, expired, mismatched or unassigned access fails closed.</p></div></section><?=footer_html()?><script type="module" src="/entry.js"></script>
<?php elseif (isset($pages[$path])): $p=$pages[$path]; ?>
<?=header_html()?><section class="page-hero"><p class="eyebrow"><span></span><?=esc($p[0])?></p><h1><?=esc($p[1])?></h1><p><?=esc($p[2])?></p></section><section class="page-section"><div class="page-intro"><p class="eyebrow dark"><span></span>The essential idea</p><h2><?=esc($p[3])?></h2><p><?=esc($p[4])?></p></div><div class="content-grid"><?php foreach ($p[5] as $i=>$b): ?><article><span>0<?=$i+1?></span><h3><?=esc($b[0])?></h3><p><?=esc($b[1])?></p></article><?php endforeach; ?></div><div class="page-next"><p>Continue exploring AAB</p><a href="/about/">About AAB ↗</a><a href="/enter-aab">Choose your pathway ↗</a></div></section><?=footer_html()?>
<?php else: ?>
<?=header_html()?><section class="page-hero"><p class="eyebrow"><span></span>Page not found</p><h1>This AAB page is not available.</h1><p>Return to the public front door to continue.</p></section><section class="page-section"><a class="button dark-button" href="/">Return home</a></section><?=footer_html()?>
<?php endif; ?></main></body></html>
