<?php
declare(strict_types=1);
namespace AAB\Agriculture\Services;
use AAB\Agriculture\Database\TransactionManager; use AAB\Agriculture\Repositories\ActorRepository; use AAB\Agriculture\Repositories\AuditRepository; use AAB\Agriculture\Repositories\IngredientRepository; use RuntimeException;
final class IngredientService {
 private const MATERIAL=['PLANT_DERIVED','ANIMAL_DERIVED','MICROBIAL','FERMENTATION_DERIVED','MARINE_DERIVED','NATURALLY_OCCURRING_MINERAL','GEOLOGICAL_MATERIAL','NATURAL_WASTE_OR_BYPRODUCT','RECOVERED_MINERAL_MATERIAL','OTHER_NATURAL_OR_BIOLOGICAL'];
 private const PREP=['UNPROCESSED','PHYSICALLY_PROCESSED','DRIED','GROUND','FILTERED','FERMENTED','WATER_EXTRACTED','OTHER_LOW_TRANSFORMATION'];
 public function __construct(private readonly TransactionManager $tx,private readonly ActorRepository $actors,private readonly AuditRepository $audit,private readonly IngredientRepository $repo){}
 public function list(array $filters=[],int $limit=100,int $offset=0):array{return $this->repo->list($filters,$limit,$offset);}
 public function createDraft(array $d,string $actor,string $why):array{$this->validate($d);if(trim($why)==='')throw new RuntimeException('WHY_REQUIRED');return $this->tx->run(function()use($d,$actor,$why){$this->actors->requireActiveActor($actor,['USER','SCIENTIST','ADMIN']);$d['amendment_rationale']=$why;$r=$this->repo->createDraft($d,$actor);$this->audit->append('INGREDIENT_DRAFT_CREATED','ingredient',$r['ingredient_id'],$actor,'CREATE_DRAFT',$why,null,$r);return $r;});}
 public function amend(string $id,array $d,string $actor,string $why):array{if(trim($why)==='')throw new RuntimeException('WHY_REQUIRED');return $this->tx->run(function()use($id,$d,$actor,$why){$this->actors->requireActiveActor($actor,['SCIENTIST','ADMIN']);$before=$this->repo->get($id,true)??throw new RuntimeException('INGREDIENT_NOT_FOUND');$this->validate(array_merge($before,$d));$after=$this->repo->createAmendment($id,$d,$actor,$why);$this->audit->append('INGREDIENT_AMENDED','ingredient',$id,$actor,'SCIENTIST_OR_ADMIN_AMENDMENT',$why,$before,$after);return $after;});}
 public function transition(string $id,string $status,string $actor,string $why):array{if(!in_array($status,['UNDER_REVIEW','ACTIVE','SUSPENDED','RETIRED','QUARANTINED'],true))throw new RuntimeException('UNSUPPORTED_LIFECYCLE_TRANSITION');if(trim($why)==='')throw new RuntimeException('WHY_REQUIRED');return $this->tx->run(function()use($id,$status,$actor,$why){$this->actors->requireActiveActor($actor,['SCIENTIST','ADMIN']);$before=$this->repo->get($id,true)??throw new RuntimeException('INGREDIENT_NOT_FOUND');$after=$this->repo->setLifecycleStatus($id,$status);$this->audit->append('INGREDIENT_STATUS_CHANGED','ingredient',$id,$actor,'SCIENTIST_OR_ADMIN_STATUS_CHANGE',$why,$before,$after);return $after;});}
 public function hardDeleteDraft(string $id,string $actor,string $why):void{if(trim($why)==='')throw new RuntimeException('WHY_REQUIRED');$this->tx->run(function()use($id,$actor,$why){$this->actors->requireActiveActor($actor,['ADMIN']);$before=$this->repo->get($id,true)??throw new RuntimeException('INGREDIENT_NOT_FOUND');$counts=$this->repo->dependencyCounts($id);if($before['lifecycle_status']!=='DRAFT'||array_sum(array_map('intval',$counts))!==0)throw new RuntimeException('REFERENCED_RECORD_MUST_BE_RETIRED');$this->audit->append('INGREDIENT_HARD_DELETE_AUTHORISED','ingredient',$id,$actor,'ADMIN_ERROR_CORRECTION',$why,$before,['deleted'=>true]);$this->repo->hardDeleteUnreferencedDraft($id);});}
 private function validate(array $d):void{foreach(['ingredient_code','ingredient_name','material_class']as$k)if(trim((string)($d[$k]??''))==='')throw new RuntimeException(strtoupper($k).'_REQUIRED');if(!preg_match('/^[A-Z0-9][A-Z0-9_-]{2,79}$/',(string)$d['ingredient_code']))throw new RuntimeException('INGREDIENT_CODE_INVALID');if(!in_array($d['material_class'],self::MATERIAL,true))throw new RuntimeException('NATURAL_MATERIAL_BOUNDARY_VIOLATION');if(!empty($d['preparation_class'])&&!in_array($d['preparation_class'],self::PREP,true))throw new RuntimeException('PREPARATION_BOUNDARY_VIOLATION');}
}
