-- PH2-WP04 restore-test instance remediation only.
-- Preconditions: comparator reports exactly 23 execute_roles mismatches and no other mismatch kind.
-- Do not add this file to canonical migration replay; reconstruction root cause remains open.
BEGIN;
REVOKE EXECUTE ON FUNCTION public.aab_accept_invitation(p_invitation_token text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.aab_accept_invitation(p_invitation_token text) TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION public.aab_accept_legal_document(p_document_version_id uuid, p_acceptance_statement text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.aab_accept_legal_document(p_document_version_id uuid, p_acceptance_statement text) TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION public.aab_admin_dashboard_snapshot() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.aab_admin_dashboard_snapshot() TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION public.aab_admin_review_participation_request(p_request_id uuid, p_decision text, p_rationale text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.aab_admin_review_participation_request(p_request_id uuid, p_decision text, p_rationale text) TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION public.aab_admin_review_security_alert(p_alert_id uuid, p_status text, p_rationale text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.aab_admin_review_security_alert(p_alert_id uuid, p_status text, p_rationale text) TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION public.aab_admin_run_security_brain() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.aab_admin_run_security_brain() TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION public.aab_admin_security_snapshot() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.aab_admin_security_snapshot() TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION public.aab_authorize_internal_wa_rehearsal_handoff(p_decision_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.aab_authorize_internal_wa_rehearsal_handoff(p_decision_id uuid) TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION public.aab_claim_country_activation(p_activation_code text, p_workspace_name text, p_default_language text, p_timezone_name text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.aab_claim_country_activation(p_activation_code text, p_workspace_name text, p_default_language text, p_timezone_name text) TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION public.aab_complete_rehearsal_handoff(p_decision_id uuid, p_receipt jsonb) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.aab_complete_rehearsal_handoff(p_decision_id uuid, p_receipt jsonb) TO service_role;
REVOKE EXECUTE ON FUNCTION public.aab_create_internal_wa_rehearsal_nomination(p_nominated_email text, p_document_sha256 text, p_rationale text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.aab_create_internal_wa_rehearsal_nomination(p_nominated_email text, p_document_sha256 text, p_rationale text) TO service_role;
REVOKE EXECUTE ON FUNCTION public.aab_create_internal_wa_rehearsal_nomination_v2(p_nominated_email text, p_purpose_code text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.aab_create_internal_wa_rehearsal_nomination_v2(p_nominated_email text, p_purpose_code text) TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION public.aab_create_personal_wa_rehearsal_decision(p_request_id uuid, p_nominated_email text, p_document_sha256 text, p_rationale text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.aab_create_personal_wa_rehearsal_decision(p_request_id uuid, p_nominated_email text, p_document_sha256 text, p_rationale text) TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION public.aab_finalize_country_activation(p_activation_code text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.aab_finalize_country_activation(p_activation_code text) TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION public.aab_finalize_invited_membership() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.aab_finalize_invited_membership() TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION public.aab_get_rehearsal_handoff_payload(p_decision_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.aab_get_rehearsal_handoff_payload(p_decision_id uuid) TO service_role;
REVOKE EXECUTE ON FUNCTION public.aab_internal_wa_rehearsal_nomination_context() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.aab_internal_wa_rehearsal_nomination_context() TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION public.aab_issue_country_invitation(p_country_workspace_id uuid, p_organization_id uuid, p_invitee_name text, p_invite_email text, p_official_position text, p_proposed_role text, p_plain_token text, p_expires_at timestamp with time zone) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.aab_issue_country_invitation(p_country_workspace_id uuid, p_organization_id uuid, p_invitee_name text, p_invite_email text, p_official_position text, p_proposed_role text, p_plain_token text, p_expires_at timestamp with time zone) TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION public.aab_legal_onboarding_state() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.aab_legal_onboarding_state() TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION public.aab_publish_country_terms(p_country_workspace_id uuid, p_title text, p_version_label text, p_language_code text, p_storage_bucket text, p_storage_path text, p_document_sha256 text, p_effective_at timestamp with time zone, p_certification_statement text, p_material_change boolean) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.aab_publish_country_terms(p_country_workspace_id uuid, p_title text, p_version_label text, p_language_code text, p_storage_bucket text, p_storage_path text, p_document_sha256 text, p_effective_at timestamp with time zone, p_certification_statement text, p_material_change boolean) TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION public.aab_resolve_entry() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.aab_resolve_entry() TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION public.aab_save_onboarding_profile(p_full_name text, p_official_position text, p_institution_name text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.aab_save_onboarding_profile(p_full_name text, p_official_position text, p_institution_name text) TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION public.aab_submit_country_participation_request(p_request jsonb) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.aab_submit_country_participation_request(p_request jsonb) TO authenticated, service_role;
COMMIT;
