"use client";

import {useMemo,useState,type MouseEvent} from "react";
import EnvironmentalHistory from "./EnvironmentalHistory";

type ImageLayer={image:string;mask:string;scene_id:string;acquired_at:string|null;cloud_cover_percent:number};
type Scene={scene_id:string;scene_count?:number;acquired_at:string|null;acquired_through?:string|null;cloud_cover_percent:number|null;clear_pixel_estimate?:number|null;cloud_mask?:string;gap_policy?:string;sensor:string;preview_url:string;image_layers?:Record<string,ImageLayer[]>;coverage_percent?:number;render_bbox?:number[];alignment?:string};
type TimelinePoint={year:number;scene:Scene|null;comparability:"SEASONALLY_MATCHED_AND_SPATIALLY_ALIGNED"|"MISSING_OR_PARTIAL_EVIDENCE"};
type Tile={tile_id:string;bbox:number[];measurement_bbox?:number[];display_context?:boolean;geometry_geojson?:{type:"Polygon";coordinates:number[][][]};change?:{classification?:string;metrics?:Record<string,number|null>}};
type ViewMode="natural"|"vegetation"|"moisture"|"disturbance";
type Workbench="summary"|"evidence"|"field";
type TrendMetric="ndvi"|"ndmi"|"ndwi"|"bare_soil";
type ChangeAnalysis={method_version:string;evidence_status:string;start_year:number;end_year:number;observations_requested:number;observations_computed:number;points:{year:number;scene_id:string;scene_count?:number;clear_pixels:number;qa_clear_fraction:number;metrics:{ndvi:number|null;ndmi:number|null;ndwi:number|null;bare_soil:number|null};score:number|null}[];deltas:{ndvi:number|null;ndmi:number|null;ndwi:number|null;bare_soil:number|null};pattern:string;headline:string;strongest_transition:{from:number;to:number;change:number};possibilities:string[];context_checks?:{name:string;status:string;finding:string}[];contradictions:string[];unknowns:string[];confidence_percent:number};

const views:[ViewMode,string,string][]=[
  ["natural","Natural colour","Visible landscape context"],
  ["vegetation","Vegetation","Near-infrared vegetation contrast"],
  ["moisture","Moisture","Short-wave infrared moisture contrast"],
  ["disturbance","Disturbance","Soil, burn and surface-change contrast"],
];
const hypotheses=["Seasonal vegetation response","Rainfall or drought influence","Fire or recovery sequence","Land-use or earthworks","Water movement or salinity","Unexplained spatial signal"];

export default function ForensicExplorer({tile,onClose}:{tile:Tile;onClose:()=>void}){
  const currentYear=new Date().getUTCFullYear();
  const [startYear,setStartYear]=useState(1982),[endYear,setEndYear]=useState(2006),[windowStart,setWindowStart]=useState("06-01"),[windowEnd,setWindowEnd]=useState("07-31"),[refreshCadence,setRefreshCadence]=useState<3|6|12>(6);
  const [timeline,setTimeline]=useState<TimelinePoint[]>([]),[status,setStatus]=useState<"idle"|"loading"|"done"|"error">("idle"),[error,setError]=useState("");
  const [activeScene,setActiveScene]=useState<Scene|null>(null),[baselineScene,setBaselineScene]=useState<Scene|null>(null),[viewMode,setViewMode]=useState<ViewMode>("natural"),[workbench,setWorkbench]=useState<Workbench>("summary");
  const [selectionStep,setSelectionStep]=useState<"baseline"|"comparison">("baseline");
  const [activeHypotheses,setActiveHypotheses]=useState<string[]>([]),[investigationNote,setInvestigationNote]=useState("");
  const [changeAnalysis,setChangeAnalysis]=useState<ChangeAnalysis|null>(null),[changeState,setChangeState]=useState<"idle"|"loading"|"done"|"error">("idle"),[changeError,setChangeError]=useState("");
  const [trendMetric,setTrendMetric]=useState<TrendMetric>("ndvi");
  const [imageryZoom,setImageryZoom]=useState(1),[imageryFocus,setImageryFocus]=useState({x:50,y:50});
  const available=useMemo(()=>timeline.filter(point=>point.scene),[timeline]);
  const timelineGroups=useMemo(()=>Object.entries(timeline.reduce<Record<string,TimelinePoint[]>>((groups,point)=>{const first=Math.floor(point.year/5)*5,key=`${first}–${first+4}`;(groups[key]??=[]).push(point);return groups},{})),[timeline]);
  const baselinePoint=useMemo(()=>timeline.find(point=>point.scene?.scene_id===baselineScene?.scene_id),[timeline,baselineScene]);
  const activePoint=useMemo(()=>timeline.find(point=>point.scene?.scene_id===activeScene?.scene_id),[timeline,activeScene]);
  const comparisonStart=Math.min(baselinePoint?.year??startYear,activePoint?.year??endYear),comparisonEnd=Math.max(baselinePoint?.year??startYear,activePoint?.year??endYear);
  const missing=timeline.length-available.length;
  const confidence=Math.min(72,20+available.length*2);
  const layers=(scene:Scene|null)=>scene?.image_layers?.[viewMode]??[];
  const clipPath=useMemo(()=>{if(tile.display_context)return undefined;const points=tile.geometry_geojson?.coordinates?.[0];if(!points?.length)return undefined;const [w,s,e,n]=tile.bbox;return `polygon(${points.map(([x,y])=>`${((x-w)/(e-w))*100}% ${((n-y)/(n-s))*100}%`).join(",")})`},[tile]);
  const outlinePoints=useMemo(()=>{if(!tile.display_context)return"";const points=tile.geometry_geojson?.coordinates?.[0];if(!points?.length)return"";const [w,s,e,n]=tile.bbox;return points.map(([x,y])=>`${((x-w)/(e-w))*1000},${((n-y)/(n-s))*1000}`).join(" ")},[tile]);
  const focusImagery=(event:MouseEvent<HTMLDivElement>)=>{const box=event.currentTarget.getBoundingClientRect();setImageryFocus({x:Math.max(0,Math.min(100,(event.clientX-box.left)/box.width*100)),y:Math.max(0,Math.min(100,(event.clientY-box.top)/box.height*100))})};
  const imagery=(scene:Scene,label:string)=><div className={`alignedImage governedPolygon zoomableImagery ${tile.display_context?"contextImagery":""}`} onClick={focusImagery} onWheel={event=>setImageryZoom(value=>Math.max(1,Math.min(8,Number((value+(event.deltaY<0?.5:-.5)).toFixed(1)))))}>{layers(scene).map((layer,index)=><img src={layer.image} key={layer.scene_id} style={{clipPath,maskImage:`url(${layer.mask})`,WebkitMaskImage:`url(${layer.mask})`,transform:`scale(${imageryZoom})`,transformOrigin:`${imageryFocus.x}% ${imageryFocus.y}%`}} alt={index===0?`${viewMode} ${label} cloud-masked mosaic from ${scene.acquired_at} to ${scene.acquired_through}`:""} aria-hidden={index>0}/>) }{outlinePoints&&<svg className="candidateBoundaryOutline" viewBox="0 0 1000 1000" preserveAspectRatio="none" aria-label="Exact governed candidate measurement boundary"><polygon points={outlinePoints}/></svg>}<span>{tile.tile_id} · {tile.display_context?"SITE OUTLINED · CONTEXT DISPLAY":"EXACT GOVERNED POLYGON"} · {scene.scene_count??1} SCENE{(scene.scene_count??1)===1?"":"S"}</span><i>N</i></div>;
  const metricRange=useMemo(()=>{const values=changeAnalysis?.points.map(point=>point.metrics[trendMetric]).filter((value):value is number=>value!=null)??[];return{min:values.length?Math.min(...values):0,max:values.length?Math.max(...values):1}},[changeAnalysis,trendMetric]);

  async function run(){setStatus("loading");setError("");setTimeline([]);setChangeAnalysis(null);setChangeState("idle");setActiveScene(null);setBaselineScene(null);setSelectionStep("baseline");try{const response=await fetch("/api/spatial-history",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({mode:"timeline",bbox:tile.bbox,start_year:startYear,end_year:endYear,window_start:windowStart,window_end:windowEnd})});const payload=await response.json();if(!response.ok)throw new Error(payload.error||"Historical search failed");const result:TimelinePoint[]=payload.timeline??[];setTimeline(result);const scenes=result.filter(point=>point.scene).map(point=>point.scene as Scene);setBaselineScene(scenes[0]??null);setActiveScene(scenes.at(-1)??null);setStatus("done")}catch(caught){setError(caught instanceof Error?caught.message:"Historical search failed");setStatus("error")}}
  function selectComparison(point:TimelinePoint){if(!point.scene)return;setChangeAnalysis(null);setChangeState("idle");if(selectionStep==="baseline"){setBaselineScene(point.scene);setActiveScene(null);setSelectionStep("comparison")}else{const baselineYear=timeline.find(item=>item.scene?.scene_id===baselineScene?.scene_id)?.year;if(baselineYear!=null&&point.year<baselineYear){setActiveScene(baselineScene);setBaselineScene(point.scene)}else setActiveScene(point.scene);setSelectionStep("baseline")}}
  async function analyseChange(){setChangeState("loading");setChangeError("");setChangeAnalysis(null);try{const evidence=timeline.filter(point=>point.scene&&point.year>=comparisonStart&&point.year<=comparisonEnd).map(point=>({year:point.year,scene_ids:(point.scene?.image_layers?.natural??[]).map(layer=>layer.scene_id)}));const response=await fetch("/api/spatial-history",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({mode:"change-analysis",bbox:tile.bbox,year:comparisonEnd,geometry_geojson:tile.geometry_geojson,timeline:evidence})});const payload=await response.json();if(!response.ok)throw new Error(payload.error||"Change-event analysis failed");if(payload.analysis_available===false){setChangeError(payload.error||"At least two QA-screened yearly observations are required.");setChangeState("error");return}setChangeAnalysis(payload);setChangeState("done")}catch(caught){setChangeError(caught instanceof Error?caught.message:"Change-event analysis failed");setChangeState("error")}}
  function toggleHypothesis(value:string){setActiveHypotheses(current=>current.includes(value)?current.filter(item=>item!==value):[...current,value])}

  return <div className="timeExplorer forensicExplorer" role="dialog" aria-modal="true" aria-label="Forensic Spatial Investigation">
    <header><div><small>AAB FORENSIC SPATIAL INVESTIGATION · {tile.tile_id}</small><h3>Review what was recorded at this place through time.</h3><p>Seasonally matched imagery and dated environmental records are aligned in one factual timeline. AAB does not assign cause, influence, correlation or meaning.</p></div><button onClick={onClose} aria-label="Close forensic investigation">×</button></header>
    <div className="forensicStatusRail"><span><b>01</b> Preserve evidence</span><span><b>02</b> Reconstruct baseline</span><span><b>03</b> Align dated records</span><span><b>04</b> Display measurements</span><span><b>05</b> User interprets</span></div>
    <div className="timeControls"><label>From year<input type="number" min="1982" max={endYear} value={startYear} onChange={event=>setStartYear(Number(event.target.value))}/></label><label>To year<input type="number" min={startYear} max={currentYear} value={endYear} onChange={event=>setEndYear(Number(event.target.value))}/></label><label>Window begins<input value={windowStart} onChange={event=>setWindowStart(event.target.value)} aria-label="Comparison window begins, month and day"/></label><label>Window ends<input value={windowEnd} onChange={event=>setWindowEnd(event.target.value)} aria-label="Comparison window ends, month and day"/></label><label>Review cycle<select value={refreshCadence} onChange={event=>setRefreshCadence(Number(event.target.value) as 3|6|12)}><option value="3">Every 3 months</option><option value="6">Every 6 months</option><option value="12">Every 12 months</option></select></label><button onClick={run} disabled={status==="loading"}>{status==="loading"?"Searching preserved archive…":"Run forensic timeline"}</button></div>
    <div className="timeEvidenceRule"><b>FORENSIC COMPARABILITY RULE</b><span>{windowStart}–{windowEnd} in every year · {tile.display_context?"the same standardised locality is displayed and the outlined candidate polygon alone is measured":"both images are cropped to the identical governed boundary"} · fixed 768 × 768 grid and colour scale · native sensor resolution is unchanged · absent evidence is never silently filled</span></div>
    {status==="idle"&&<div className="explorerEmpty"><div><strong>Ready to reconstruct {tile.tile_id}</strong><span>Run the timeline to retrieve the strongest available scene for the same seasonal window in every year.</span></div></div>}
    {status==="error"&&<div className="explorerEmpty"><div><strong>No result claimed</strong><span>{error}</span></div></div>}
    {timeline.length>0&&<>
      <div className="comparisonPicker"><b>{selectionStep==="baseline"?"1 · SELECT BASELINE YEAR":"2 · SELECT COMPARISON YEAR"}</b><span>{selectionStep==="baseline"?"Choose the first year. Your next click chooses the year to compare against it.":`Baseline ${baselinePoint?.year??"selected"}. Now choose the second year.`}</span></div>
      <div className="forensicPeriods">{timelineGroups.map(([period,points])=><section key={period}><header><b>{period}</b><span>{points.filter(point=>point.scene).length} of {points.length} years available</span></header><div className="yearFilmstrip forensicFilmstrip">{points.map(point=><button className={`${point.scene?.scene_id===activeScene?.scene_id?"active":""} ${point.scene?.scene_id===baselineScene?.scene_id?"baseline":""} ${!point.scene?"missing":""}`} key={point.year} disabled={!point.scene} onClick={()=>selectComparison(point)}><b>{point.year}</b><span>{point.scene?.acquired_at?new Date(point.scene.acquired_at).toLocaleDateString("en-AU",{day:"2-digit",month:"short"}):"Missing evidence"}</span><i>{point.scene?.scene_id===baselineScene?.scene_id?"BASELINE":point.scene?.scene_id===activeScene?.scene_id?"COMPARISON":point.scene?.cloud_cover_percent==null?"":`${point.scene.cloud_cover_percent.toFixed(1)}% cloud`}</i></button>)}</div></section>)}</div><EnvironmentalHistory bbox={tile.bbox} startYear={startYear} endYear={endYear} windowStart={windowStart} windowEnd={windowEnd} enabled={timeline.length>0}/>
      <div className="viewModeRail">{views.map(([id,label,description])=><button className={viewMode===id?"active":""} key={id} onClick={()=>setViewMode(id)}><b>{label}</b><span>{description}</span></button>)}</div>
      <div className="linkedZoom"><div><b>LINKED IMAGE INSPECTION · {imageryZoom.toFixed(1)}×</b><span>Scroll over either image to zoom continuously, then click the point you want centred in both dates.</span></div><nav>{[1,2,4,8].map(level=><button className={imageryZoom===level?"active":""} key={level} onClick={()=>setImageryZoom(level)}>{level}×</button>)}<button onClick={()=>{setImageryZoom(1);setImageryFocus({x:50,y:50})}}>Reset</button></nav></div>
      <div className="forensicImagery">
        <figure>{baselineScene?imagery(baselineScene,"baseline"):<div>Baseline unavailable</div>}<figcaption><b>BASELINE MOSAIC · CLOUD-MASKED</b><span>{baselineScene?.acquired_at?`${new Date(baselineScene.acquired_at).toLocaleDateString("en-AU")}–${new Date(baselineScene.acquired_through??baselineScene.acquired_at).toLocaleDateString("en-AU")}`:"No qualifying scene"}</span></figcaption></figure>
        <div className="comparisonAxis"><span>→</span><b>PIXEL-GRID LOCKED COMPARISON</b></div>
        <figure>{activeScene?imagery(activeScene,"comparison"):<div>Select a year</div>}<figcaption><b>SELECTED MOSAIC · CLOUD-MASKED</b><span>{activeScene?.acquired_at?`${new Date(activeScene.acquired_at).toLocaleDateString("en-AU")}–${new Date(activeScene.acquired_through??activeScene.acquired_at).toLocaleDateString("en-AU")}`:"No qualifying scene"}</span></figcaption></figure>
      </div>
      <div className="alignmentProof"><b>ALIGNMENT + QUALITY PROOF</b><span>Measurement boundary {(tile.measurement_bbox??tile.bbox).map(value=>value.toFixed(5)).join(" · ")}</span>{tile.display_context&&<span>Standardised candidate display scale · context excluded from metrics</span>}<span>Output grid 768 × 768</span><span>Native Landsat resolution retained</span><span>Fixed colour scaling</span><span>Spatial coverage {Math.min(baselineScene?.coverage_percent??0,activeScene?.coverage_percent??0).toFixed(1)}%</span><span>Estimated clear coverage {Math.min(baselineScene?.clear_pixel_estimate??0,activeScene?.clear_pixel_estimate??0).toFixed(1)}%</span><span>Cloud, shadow, snow, fill and invalid pixels excluded by QA_PIXEL</span></div>
      <section className="changeEventLab" aria-label="Change Event Analysis">
        <header><div><small>GOVERNED CHANGE EVENT ANALYSIS</small><h4>Measure what changed between {comparisonStart} and {comparisonEnd}</h4><p>AAB computes QA-screened yearly spectral measurements only for the selected comparison interval inside the exact governed polygon.</p></div><button onClick={analyseChange} disabled={changeState==="loading"||!baselineScene||!activeScene||comparisonStart===comparisonEnd}>{changeState==="loading"?"Computing selected interval…":changeAnalysis?`Re-run ${comparisonStart}–${comparisonEnd} analysis`:`Analyse ${comparisonStart}–${comparisonEnd}`}</button></header>
        {changeState==="error"&&<div className="changeEventError"><b>No change claim created</b><span>{changeError}</span></div>}
        {changeAnalysis&&<>
          <div className="changeEventHeadline"><div><small>COMPUTED · UNVALIDATED</small><strong>{changeAnalysis.headline}</strong><span>{changeAnalysis.observations_computed} of {changeAnalysis.observations_requested} available years produced QA-screened measurements.</span></div><b>{Math.round(changeAnalysis.confidence_percent)}%<small>SCREENING CONFIDENCE</small></b></div>
          <div className="changeMetricGrid">{[["NDVI",changeAnalysis.deltas.ndvi],["NDMI",changeAnalysis.deltas.ndmi],["NDWI",changeAnalysis.deltas.ndwi],["Bare soil",changeAnalysis.deltas.bare_soil]].map(([label,value])=><article key={String(label)}><small>{label} NET CHANGE</small><strong>{typeof value==="number"?`${value>=0?"+":""}${value.toFixed(3)}`:"—"}</strong><span>{label==="Bare soil"?(Number(value)>0?"More exposed-ground signal":"Less exposed-ground signal"):(Number(value)<0?"Lower end-period signal":"Higher end-period signal")}</span></article>)}</div>
          <div className="changeTrend"><div className="changeTrendTitle"><b>YEAR-BY-YEAR MEASURED HISTORY</b><span>{trendMetric==="ndvi"?"NDVI: vegetation vigour—not visible greenness":trendMetric==="ndmi"?"NDMI: vegetation moisture":trendMetric==="ndwi"?"NDWI: surface-water signal":"Bare-soil index: higher means more exposed-ground signal"} · each index is shown separately</span></div><nav aria-label="Choose timeline measurement">{([['ndvi','NDVI · vegetation'],['ndmi','NDMI · moisture'],['ndwi','NDWI · water'],['bare_soil','Bare soil']] as [TrendMetric,string][]).map(([metric,label])=><button className={trendMetric===metric?"active":""} key={metric} onClick={()=>setTrendMetric(metric)}>{label}</button>)}</nav><div>{changeAnalysis.points.map(point=>{const value=point.metrics[trendMetric],level=value==null?0:18+82*(value-metricRange.min)/Math.max(.0001,metricRange.max-metricRange.min);return <span key={point.year} title={`${point.year}: ${value?.toFixed(3)??"unavailable"}`}><i style={{height:`${level}%`}}/><b>{point.year}</b></span>})}</div></div>
          <div className="changeEventInterpretation"><article><small>STRONGEST MEASURED TRANSITION</small><strong>{changeAnalysis.strongest_transition.from} → {changeAnalysis.strongest_transition.to}</strong><span>Mean absolute multi-index difference {changeAnalysis.strongest_transition.change.toFixed(3)}. This is a measured difference between observations.</span></article><article><small>MEASURED NET VALUES</small><span>NDVI {changeAnalysis.deltas.ndvi?.toFixed(3)??"—"}</span><span>NDMI {changeAnalysis.deltas.ndmi?.toFixed(3)??"—"}</span><span>NDWI {changeAnalysis.deltas.ndwi?.toFixed(3)??"—"}</span><span>Bare soil {changeAnalysis.deltas.bare_soil?.toFixed(3)??"—"}</span></article><article><small>DATA LIMITATIONS</small>{changeAnalysis.contradictions.map(item=><span key={item}>• {item}</span>)}</article><article className="unknown"><small>NOT ESTABLISHED BY THESE RECORDS</small><span>Cause, influence and correlation are not asserted.</span><span>Material identity and land condition are not established.</span></article></div>

          <footer><b>CAUSATION NOT CLAIMED</b><span>This analysis detects persistent spectral evidence. It cannot call the land degraded, identify a material or explain why it changed until contextual and field evidence is connected.</span></footer>
        </>}
      </section>
      <div className="forensicWorkbenchTabs">{(["summary","evidence","field"] as Workbench[]).map(tab=><button className={workbench===tab?"active":""} onClick={()=>setWorkbench(tab)} key={tab}>{tab==="summary"?"Period summary":tab==="evidence"?"Evidence ledger":"Field verification"}</button>)}</div>
      {workbench==="summary"&&<section className="forensicReport"><div className="reportLead"><small>RECORDED FACTS ONLY</small><h4>{startYear}–{endYear} spatial history summary</h4><p>{changeAnalysis?`${changeAnalysis.observations_computed} QA-screened yearly measurements were computed inside the exact governed polygon.`:`${available.length} seasonally matched archive observations were located for ${tile.tile_id}; ${missing} years contain no qualifying scene.`}</p></div><div className="reportGrid"><article><b>Imagery records</b><span>{available.length} comparable annual mosaics preserved with exact timestamps and scene identifiers.</span></article><article><b>Measured interval</b><span>{changeAnalysis?`${changeAnalysis.strongest_transition.from}–${changeAnalysis.strongest_transition.to} has the largest mean absolute multi-index difference: ${changeAnalysis.strongest_transition.change.toFixed(3)}.`:"Run the governed pixel measurement to calculate annual index values."}</span></article><article><b>Seasonal window</b><span>{windowStart}–{windowEnd} applied consistently to each selected year.</span></article><article><b>Environmental records</b><span>Rainfall, temperature and frost-temperature thresholds are available in the Environmental records tab.</span></article><article><b>Fire and flood</b><span>Not displayed until authoritative dated spatial records are connected.</span></article><article><b>Interpretation</b><span>Cause, influence, correlation, land condition and material identity are left to the user.</span></article></div><div className="confidenceLink"><span>Current evidence coverage</span><i><em style={{width:`${changeAnalysis?changeAnalysis.confidence_percent:confidence}%`}}/></i><b>{Math.round(changeAnalysis?changeAnalysis.confidence_percent:confidence)}% · {changeAnalysis?"QA-SCREENED PIXEL EVIDENCE":"ARCHIVE COVERAGE ONLY"} · INTERPRETATION NOT PROVIDED</b></div></section>}
      {workbench==="evidence"&&<section className="evidenceLedger"><header><div><small>IMMUTABLE SOURCE LEDGER</small><strong>{available.length} preserved observations</strong></div><span>{tile.bbox.map(value=>value.toFixed(4)).join(" · ")}</span></header><div>{available.map(point=><article key={point.year}><b>{point.year}</b><span>{point.scene?.acquired_at?new Date(point.scene.acquired_at).toLocaleString("en-AU"):"Timestamp unavailable"}</span><span>{point.scene?.sensor}</span><span>{point.scene?.cloud_cover_percent?.toFixed(1)??"?"}% cloud</span><code>{point.scene?.scene_id}</code></article>)}</div></section>}

      {workbench==="field"&&<section className="fieldPlan"><div><small>FIELD VERIFICATION PLAN</small><h4>Turn the unexplained signal into testable evidence</h4><ol><li><b>Target point</b><span>Inspect the strongest computed change cluster after pixel processing.</span></li><li><b>Control point</b><span>Sample a nearby unchanged location with comparable land context.</span></li><li><b>Chain of custody</b><span>Assign sample ID, coordinates, collector, timestamp and sealed transfer record.</span></li><li><b>Laboratory scope</b><span>Select tests only after the suspected material class and safety risks are reviewed.</span></li><li><b>Return evidence</b><span>Link results to this tile, timeline, hypothesis and exact source observations.</span></li></ol></div><aside><b>NEXT EVIDENCE GATES</b>{["Multi-year pixel processing","Weather and fire connectors","Land-use and geology context","Scientist-approved sampling grid","Laboratory characterisation","Independent review"].map(item=><span key={item}>{item}<i>REQUIRED</i></span>)}</aside></section>}
      <footer className="forensicFooter"><span>Review cycle: every {refreshCadence} months · automatic scheduling requires the governed scheduler connection</span><div><button disabled>Search matching signatures · PIXEL FINGERPRINT REQUIRED</button><button disabled>Save forensic record · MEMORY CONNECTION REQUIRED</button></div></footer>
    </>}
  </div>
}
