-- Source B supplement. Live rehearsal database kdpcfbaeklkffozryjah, read through the Supabase connector on 2026-09-28. Schema only, no rows. The eight application schemas not in snapshot-2026-09-28.
-- Read at 2026-09-28 09:04:35.914286+00 (UTC), PostgreSQL 17.6. Generated from the system catalogs, read only.
-- Schema: presentation_core. Grants: schema, table, sequence, column and function privileges, and default privileges.
-- Catalog counts for presentation_core: functions 0, tables 8, views 0, sequences 1, rls_enabled_tables 0, constraints 28, triggers 0, policies 0, indexes 15.
-- Evidence of what exists, not governed code. Never edited after commit.

-- schema presentation_core owner: postgres
-- presentation_core.access_request: relacl is NULL (owner default privileges only)
-- presentation_core.activity_event: relacl is NULL (owner default privileges only)
-- presentation_core.activity_event_activity_event_id_seq: relacl is NULL (owner default privileges only)
-- presentation_core.invitation: relacl is NULL (owner default privileges only)
-- presentation_core.password_reset_request: relacl is NULL (owner default privileges only)
-- presentation_core.portal_owner: relacl is NULL (owner default privileges only)
-- presentation_core.viewer: relacl is NULL (owner default privileges only)
-- presentation_core.viewer_question: relacl is NULL (owner default privileges only)
-- presentation_core.viewer_session: relacl is NULL (owner default privileges only)
