-- Source B supplement. Live rehearsal database kdpcfbaeklkffozryjah, read through the Supabase connector on 2026-09-28. Schema only, no rows. The eight application schemas not in snapshot-2026-09-28.
-- Read at 2026-09-28 09:04:35.914286+00 (UTC), PostgreSQL 17.6. Generated from the system catalogs, read only.
-- Schema: presentation_core. Row level security: the enabled/forced setting of every table, and every policy.
-- Catalog counts for presentation_core: functions 0, tables 8, views 0, sequences 1, rls_enabled_tables 0, constraints 28, triggers 0, policies 0, indexes 15.
-- Evidence of what exists, not governed code. Never edited after commit.

-- presentation_core.access_request: row level security DISABLED
-- presentation_core.activity_event: row level security DISABLED
-- presentation_core.invitation: row level security DISABLED
-- presentation_core.password_reset_request: row level security DISABLED
-- presentation_core.portal_owner: row level security DISABLED
-- presentation_core.viewer: row level security DISABLED
-- presentation_core.viewer_question: row level security DISABLED
-- presentation_core.viewer_session: row level security DISABLED
