-- Source B supplement. Live rehearsal database kdpcfbaeklkffozryjah, read through the Supabase connector on 2026-09-28. Schema only, no rows. The eight application schemas not in snapshot-2026-09-28.
-- Read at 2026-09-28 09:04:35.914286+00 (UTC), PostgreSQL 17.6. Generated from the system catalogs, read only.
-- Schema: regulatory_core. Row level security: the enabled/forced setting of every table, and every policy.
-- Catalog counts for regulatory_core: functions 4, tables 9, views 1, sequences 0, rls_enabled_tables 0, constraints 40, triggers 0, policies 0, indexes 12.
-- Evidence of what exists, not governed code. Never edited after commit.

-- regulatory_core.dossier_evidence_link: row level security DISABLED
-- regulatory_core.dossier_passport: row level security DISABLED
-- regulatory_core.jurisdiction: row level security DISABLED
-- regulatory_core.regulatory_authority: row level security DISABLED
-- regulatory_core.regulatory_change_event: row level security DISABLED
-- regulatory_core.regulatory_requirement: row level security DISABLED
-- regulatory_core.regulatory_source: row level security DISABLED
-- regulatory_core.requirement_assessment: row level security DISABLED
-- regulatory_core.translation_run: row level security DISABLED
