// SCS-CAP-02 failure codes — exactly the error union of the contract's
// ScsPartyRegistrationFailure, each with its HTTP status. A code that is not
// in the contract is not added here; the contract changes first.
//
// Every failure is FAIL_CLOSED and writes nothing: it is thrown, so the
// request's transaction rolls back (receipt and idempotency record included).
//
// PARTY_TYPE_INVALID and PARTY_NAME_MISSING are enforced by the request schema
// (enum and required non-blank), so the server layer refuses them first with
// REQUEST_VALIDATION_FAILED (400); the codes stay listed because the contract
// defines them.


import { ScsFailure } from "../../foundation/errors.js";

export const CAPABILITY_ID = "SCS-CAP-02" as const;

export const CAP02_FAILURES = {
  REGISTRANT_NOT_AUTHORISED: 403,
  PARTY_TYPE_INVALID: 400,
  COUNTRY_CODE_UNRECOGNISED: 422,
  PARTY_NAME_MISSING: 400,
  CONFLICTING_REGISTRATION_DETECTED: 409,
  PARTY_NOT_FOUND: 404,
  PARTY_RETIRED: 422,
  EVIDENCE_ALREADY_LINKED: 409,
  FRAMEWORK_ASSOCIATION_NOT_FOUND: 422,
  FROM_PARTY_NOT_FOUND: 422,
  TO_PARTY_NOT_FOUND: 422,
  SELF_REFERENTIAL_RELATIONSHIP: 422,
  MANDATE_ACTION_NOT_ENUMERATED: 422,
  GRANTING_PARTY_NOT_FOUND: 422,
  REPRESENTATIVE_PARTY_NOT_FOUND: 422,
  FRAMEWORK_NOT_ACTIVE: 422,
  SCOPE_OUTSIDE_FRAMEWORK: 422,
  VALIDITY_PERIOD_INVALID: 400,
  OTHER_TYPE_REQUIRES_DESCRIPTION: 400,
  CONFLICTING_RECORD: 409,
  CLAIMING_PARTY_NOT_IN_RELATIONSHIP: 400,
  SELF_GRANTED_MANDATE: 400,
  RELATIONSHIP_NOT_FOUND: 422,
  VERIFIER_NOT_AUTHORISED: 403,
  VERIFICATION_STATUS_NOT_RECORDABLE: 400,
  VERIFICATION_EVIDENCE_NOT_LINKED: 422,
  SUPERSEDED_ASSESSMENT_NOT_FOUND: 422,
  // Actor–party links (AAB-PLATFORM-04; amendments of 2026-09-27)
  LINK_CREATOR_NOT_AUTHORISED: 403,
  LINK_SELF_ASSERTED: 403,
  LINK_SUBJECT_NOT_FOUND: 422,
  LINK_SUBJECT_NOT_CURRENT: 422,
  LINK_EVIDENCE_MISSING: 422,
  LINK_VALIDITY_INVALID: 400,
  LINK_ALREADY_ACTIVE: 409,
  LINK_SIGNATURE_INVALID: 422,
  LINK_SIGNATURE_UNDER_REVIEW: 422,     // AAB-PLATFORM-04 third amendment, 2026-09-28
  LINK_NOT_FOUND: 404,
  LINK_NOT_ACTIVE: 422,
  LINK_RELATION_NOT_PERMITTED: 422,
  LINK_STATUS_NOT_PERMITTED: 409,
  LINK_STATUS_WRITER_NOT_AUTHORISED: 403,
  LINK_READER_NOT_AUTHORISED: 403,
  // Mandate verification (amendment of 2026-09-27)
  MANDATE_NOT_FOUND: 404,
  MANDATE_NOT_CURRENT: 422,
  // Representative submission (amendment of 2026-09-27); the same statuses in SCS-CAP-04 and SCS-CAP-05
  REPRESENTATIVE_NOT_AUTHORISED: 403,
  LINK_AMBIGUOUS: 409,
  MANDATE_PARTIES_MISMATCH: 422,
  MANDATE_ACTION_NOT_PERMITTED: 422,
  MANDATE_SCOPE_MISMATCH: 422,
  MANDATE_RELATIONSHIP_NOT_ACTIVE: 422,
  MANDATE_NOT_VERIFIED: 422,
  DEPENDENCY_UNAVAILABLE: 503,
} as const;

export type Cap02FailureCode = keyof typeof CAP02_FAILURES;

export function cap02Failure(code: Cap02FailureCode, reasons: readonly string[]): ScsFailure<typeof CAPABILITY_ID, Cap02FailureCode> {
  return new ScsFailure({ capabilityId: CAPABILITY_ID, code, reasons, httpStatus: CAP02_FAILURES[code] });
}
