<?php declare(strict_types=1); header('X-Content-Type-Options: nosniff'); header('Referrer-Policy: strict-origin-when-cross-origin'); function mark():string{return '<span class="brand-mark" aria-hidden="true"><i></i><i></i><i></i></span>';} ?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Founding Partners | AAB</title><meta name="description" content="Explore a governed founding pilot with AAB across agriculture, universities, research institutions and country programs."><link rel="canonical" href="https://aab.ag/partners/"><link rel="stylesheet" href="/site.css"><link rel="stylesheet" href="/launch.css"><script src="/site.js" defer></script></head><body><main>
<header class="site-header inner-header"><a class="brand" href="/"><?=mark()?><span>AAB</span></a><button class="menu-toggle" data-menu-toggle aria-expanded="false">Menu</button><nav data-nav><a href="/about/">About AAB</a><a href="/how-aab-works">How AAB Works</a><a href="/agriculture">Agriculture</a><a href="/countries">Countries</a><a href="/partners/" aria-current="page">Partners</a><a href="/governance-trust">Governance</a></nav><a class="header-action" href="/enter-aab">Enter AAB <span>↗</span></a></header>
<section class="page-hero"><p class="eyebrow"><span></span>Founding partnerships</p><h1>Build one governed pilot that proves what AAB can become.</h1><p>AAB is seeking a small number of serious collaborators prepared to test scientific memory, evidence lineage and human-governed intelligence against a real problem.</p></section>
<section class="launch-section"><div class="launch-heading"><p class="eyebrow dark"><span></span>The right beginning</p><h2>A focused partnership before a broad launch.</h2><p>The first AAB partnership should be narrow enough to govern properly and meaningful enough to produce evidence: one defined setting, accountable people, measurable outcomes and learning that remains useful after the pilot ends.</p></div><div class="partner-grid"><article class="partner-card"><span>01 · UNIVERSITY</span><h3>Founding research institution</h3><p>Scientific leadership, research capability, facilities, students and governed review around a defined investigation.</p><strong>Institutional collaboration</strong></article><article class="partner-card"><span>02 · COUNTRY</span><h3>Country or regional authority</h3><p>A real national or regional problem, responsible participation, local priorities and an authorised pathway for institutions.</p><strong>Governed country pilot</strong></article><article class="partner-card"><span>03 · FIELD</span><h3>Agricultural proving partner</h3><p>Trial locations, agronomic context, operational knowledge and field observations within an approved scientific program.</p><strong>First proving domain</strong></article></div>
<div class="partner-fit"><div><p class="eyebrow dark"><span></span>Pilot shape</p><h2>Small enough to control. Strong enough to matter.</h2></div><ol><li>Define one scientific or agricultural problem and the decisions the pilot must not make automatically.</li><li>Agree ownership, authority, data boundaries, evidence requirements and success measures before work begins.</li><li>Configure only the required country, institution, team and scientific workflow.</li><li>Run the controlled journey from question through evidence, review, outcome and preserved learning.</li><li>Evaluate scientific value, governance performance and the case for expansion.</li></ol></div>
<div class="pilot-banner"><div><h2>Explore a governed founding pilot.</h2><p>A conversation does not create access, authority or a commitment. It begins a careful assessment of fit, responsibilities and the smallest credible pilot.</p></div><a class="button primary" href="mailto:david@aab.ag?subject=AAB%20founding%20pilot%20enquiry">Contact AAB ↗</a></div></section>
<footer><div class="footer-brand"><?=mark()?><div><strong>AAB</strong><p>Governed Scientific Intelligence Infrastructure</p></div></div><div class="footer-links"><a href="/about/">About</a><a href="/partners/">Partners</a><a href="/trust/">Trust</a><a href="/insights/">Insights</a><a href="/enter-aab">Access</a></div><p class="copyright">© 2026 AAB. Research and systems development stage.</p></footer></main></body></html>

