// Generates src/types/*.ts from the JSON Schemas in src/schemas/.
//
//   npm run generate:types           write the files
//   npm run generate:types -- --check  exit 1 if any file differs from what the
//                                      schemas produce (run by npm test)
//
// Types are never hand-written: edit the schema, then regenerate.
// Schemas reference each other by $id (urn:aab:scs:schema:…); those references
// are resolved to the local files here — nothing is fetched over the network.

import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { compile } from "json-schema-to-typescript";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const schemaDir = path.join(root, "src", "schemas");
const typesDir = path.join(root, "src", "types");

/** Every schema, by $id. */
const SCHEMA_FILES = [
  "shared/actor-reference.schema.json",
  "cap-01/framework-registration-request.schema.json",
  "cap-01/framework-registration-receipt.schema.json",
];

/** Output files: which schemas each contains, and which shared types it imports. */
const TARGETS = [
  { out: "shared.ts", schemas: ["shared/actor-reference.schema.json"], imports: [] },
  {
    out: "cap-01.ts",
    schemas: ["cap-01/framework-registration-request.schema.json", "cap-01/framework-registration-receipt.schema.json"],
    imports: [{ from: "./shared.js", id: "urn:aab:scs:schema:shared:actor-reference:1", name: "ActorReference" }],
  },
];

/**
 * In the generator's own copy of a schema, replace each $ref to an imported
 * shared schema with json-schema-to-typescript's tsType hint, so the shared
 * type is imported rather than declared again. The schema files are untouched.
 */
function useImportedTypes(node, imports) {
  if (Array.isArray(node)) return node.map((n) => useImportedTypes(n, imports));
  if (node === null || typeof node !== "object") return node;
  const hit = imports.find((i) => node.$ref === i.id);
  if (hit) {
    const { $ref, ...rest } = node;
    return { ...rest, tsType: hit.name };
  }
  return Object.fromEntries(Object.entries(node).map(([k, v]) => [k, useImportedTypes(v, imports)]));
}

function banner(sources) {
  return [
    "/* eslint-disable */",
    "/**",
    " * GENERATED FILE — DO NOT EDIT BY HAND.",
    " * Generated by json-schema-to-typescript from:",
    ...sources.map((s) => ` *   src/schemas/${s}`),
    " * To change these types, edit the schema(s) above, then run:",
    " *   npm run generate:types",
    " * npm test fails if this file differs from what the schemas generate.",
    " */",
  ].join("\n");
}

async function loadSchemas() {
  const byId = new Map();
  const byFile = new Map();
  for (const file of SCHEMA_FILES) {
    const schema = JSON.parse(await readFile(path.join(schemaDir, file), "utf8"));
    if (typeof schema.$id !== "string") throw new Error(`${file} has no $id`);
    byId.set(schema.$id, schema);
    byFile.set(file, schema);
  }
  return { byId, byFile };
}

/** Returns { "shared.ts": "…", "cap-01.ts": "…" } — the exact file contents. */
export async function generate() {
  const { byId, byFile } = await loadSchemas();
  const urnResolver = {
    order: 1,
    canRead: /^urn:aab:scs:schema:/,
    read: (file) => {
      const schema = byId.get(file.url);
      if (!schema) throw new Error(`unresolved schema reference ${file.url}`);
      return JSON.stringify(schema);
    },
  };

  const outputs = {};
  for (const target of TARGETS) {
    const parts = [];
    for (const file of target.schemas) {
      const ts = await compile(useImportedTypes(structuredClone(byFile.get(file)), target.imports), "", {
        bannerComment: "",
        cwd: schemaDir,
        declareExternallyReferenced: true,
        ignoreMinAndMaxItems: true,
        strictIndexSignatures: true,
        additionalProperties: false,
        unknownAny: true,
        format: true,
        $refOptions: { resolve: { urn: urnResolver, http: false, file: false } },
      });
      parts.push(ts.trim());
    }
    const imports = target.imports.map((i) => `import type { ${i.name} } from "${i.from}";`);
    outputs[target.out] = [banner(target.schemas), ...(imports.length ? [imports.join("\n")] : []), ...parts].join("\n\n") + "\n";
  }
  return outputs;
}

async function main() {
  const check = process.argv.includes("--check");
  const outputs = await generate();
  const stale = [];
  for (const [file, content] of Object.entries(outputs)) {
    const target = path.join(typesDir, file);
    if (check) {
      const current = await readFile(target, "utf8").catch(() => null);
      if (current !== content) stale.push(`src/types/${file}`);
    } else {
      await writeFile(target, content, "utf8");
      console.log(`wrote src/types/${file}`);
    }
  }
  if (check && stale.length > 0) {
    console.error(`Generated types are out of date: ${stale.join(", ")}. Run: npm run generate:types`);
    process.exit(1);
  }
  if (check) console.log("generated types are up to date");
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  await main();
}
