-- Source B. Live rehearsal database kdpcfbaeklkffozryjah, read through the Supabase connector on 2026-09-28. Schema only, no rows.
-- Read at 2026-09-28 07:30:53.092006+00 (UTC), PostgreSQL 17.6. Generated from the system catalogs, read only.
-- Schema: agriculture. Triggers (non-internal): definitions (pg_get_triggerdef).
-- Catalog counts for agriculture: functions 170, tables 121, views 65, rls_enabled_tables 121, constraints 998, triggers 80, policies 0, indexes 334.
-- Evidence of what exists, not governed code. Never edited after commit.

CREATE TRIGGER trg_agricultural_problem_archive_only BEFORE DELETE ON agriculture.agricultural_problem FOR EACH ROW EXECUTE FUNCTION agriculture.prevent_canonical_delete();
CREATE TRIGGER trg_agricultural_problem_mutation_audit AFTER INSERT OR UPDATE ON agriculture.agricultural_problem FOR EACH ROW EXECUTE FUNCTION agriculture.audit_canonical_mutation('agricultural_problem_id');
CREATE TRIGGER trg_agricultural_problem_set_updated_at BEFORE UPDATE ON agriculture.agricultural_problem FOR EACH ROW EXECUTE FUNCTION agriculture.set_updated_at();
CREATE TRIGGER trg_approved_learning_append_only BEFORE DELETE OR UPDATE ON agriculture.approved_learning FOR EACH ROW EXECUTE FUNCTION agriculture.prevent_append_only_mutation();
CREATE TRIGGER trg_approved_learning_archive_only BEFORE DELETE ON agriculture.approved_learning FOR EACH ROW EXECUTE FUNCTION agriculture.prevent_canonical_delete();
CREATE TRIGGER trg_approved_learning_mutation_audit AFTER INSERT OR UPDATE ON agriculture.approved_learning FOR EACH ROW EXECUTE FUNCTION agriculture.audit_canonical_mutation('approved_learning_id');
CREATE TRIGGER trg_approved_learning_requires_approved_candidate BEFORE INSERT ON agriculture.approved_learning FOR EACH ROW EXECUTE FUNCTION agriculture.validate_approved_learning_source();
CREATE TRIGGER trg_audit_event_no_delete BEFORE DELETE ON agriculture.audit_event FOR EACH ROW EXECUTE FUNCTION agriculture.prevent_audit_event_mutation();
CREATE TRIGGER trg_audit_event_no_update BEFORE UPDATE ON agriculture.audit_event FOR EACH ROW EXECUTE FUNCTION agriculture.prevent_audit_event_mutation();
CREATE TRIGGER trg_brain_eligibility_delete_block BEFORE DELETE ON agriculture.brain_evidence_eligibility FOR EACH ROW EXECUTE FUNCTION agriculture.prevent_append_only_mutation();
CREATE TRIGGER trg_contradiction_record_archive_only BEFORE DELETE ON agriculture.contradiction_record FOR EACH ROW EXECUTE FUNCTION agriculture.prevent_canonical_delete();
CREATE TRIGGER trg_contradiction_record_mutation_audit AFTER INSERT OR UPDATE ON agriculture.contradiction_record FOR EACH ROW EXECUTE FUNCTION agriculture.audit_canonical_mutation('contradiction_record_id');
CREATE TRIGGER trg_crop_archive_only BEFORE DELETE ON agriculture.crop FOR EACH ROW EXECUTE FUNCTION agriculture.prevent_canonical_delete();
CREATE TRIGGER trg_crop_mutation_audit AFTER INSERT OR UPDATE ON agriculture.crop FOR EACH ROW EXECUTE FUNCTION agriculture.audit_canonical_mutation('crop_id');
CREATE TRIGGER trg_crop_set_updated_at BEFORE UPDATE ON agriculture.crop FOR EACH ROW EXECUTE FUNCTION agriculture.set_updated_at();
CREATE TRIGGER trg_discovery_candidate_archive_only BEFORE DELETE ON agriculture.discovery_candidate FOR EACH ROW EXECUTE FUNCTION agriculture.prevent_canonical_delete();
CREATE TRIGGER trg_discovery_candidate_mutation_audit AFTER INSERT OR UPDATE ON agriculture.discovery_candidate FOR EACH ROW EXECUTE FUNCTION agriculture.audit_canonical_mutation('discovery_candidate_id');
CREATE TRIGGER trg_discovery_candidate_set_updated_at BEFORE UPDATE ON agriculture.discovery_candidate FOR EACH ROW EXECUTE FUNCTION agriculture.set_updated_at();
CREATE TRIGGER trg_discovery_promotion_requires_decision BEFORE INSERT OR UPDATE OF lifecycle_status, governance_decision_id ON agriculture.discovery_candidate FOR EACH ROW EXECUTE FUNCTION agriculture.prevent_automatic_discovery_promotion();
CREATE TRIGGER trg_entity_version_append_only BEFORE DELETE ON agriculture.entity_version FOR EACH ROW EXECUTE FUNCTION agriculture.prevent_append_only_mutation();
CREATE TRIGGER trg_evidence_packet_set_updated_at BEFORE UPDATE ON agriculture.evidence_packet FOR EACH ROW EXECUTE FUNCTION agriculture.set_updated_at();
CREATE TRIGGER trg_farm_archive_only BEFORE DELETE ON agriculture.farm FOR EACH ROW EXECUTE FUNCTION agriculture.prevent_canonical_delete();
CREATE TRIGGER trg_farm_mutation_audit AFTER INSERT OR UPDATE ON agriculture.farm FOR EACH ROW EXECUTE FUNCTION agriculture.audit_canonical_mutation('farm_id');
CREATE TRIGGER trg_farm_set_updated_at BEFORE UPDATE ON agriculture.farm FOR EACH ROW EXECUTE FUNCTION agriculture.set_updated_at();
CREATE TRIGGER trg_formulation_candidate_archive_only BEFORE DELETE ON agriculture.formulation_candidate FOR EACH ROW EXECUTE FUNCTION agriculture.prevent_canonical_delete();
CREATE TRIGGER trg_formulation_candidate_mutation_audit AFTER INSERT OR UPDATE ON agriculture.formulation_candidate FOR EACH ROW EXECUTE FUNCTION agriculture.audit_canonical_mutation('formulation_candidate_id');
CREATE TRIGGER trg_formulation_request_archive_only BEFORE DELETE ON agriculture.formulation_request FOR EACH ROW EXECUTE FUNCTION agriculture.prevent_canonical_delete();
CREATE TRIGGER trg_formulation_request_mutation_audit AFTER INSERT OR UPDATE ON agriculture.formulation_request FOR EACH ROW EXECUTE FUNCTION agriculture.audit_canonical_mutation('formulation_request_id');
CREATE TRIGGER trg_formulation_request_set_updated_at BEFORE UPDATE ON agriculture.formulation_request FOR EACH ROW EXECUTE FUNCTION agriculture.set_updated_at();
CREATE TRIGGER trg_formulation_version_mutation_audit AFTER INSERT OR UPDATE ON agriculture.formulation_version FOR EACH ROW EXECUTE FUNCTION agriculture.audit_canonical_mutation('formulation_version_id');
CREATE TRIGGER trg_formulation_version_protect_history BEFORE DELETE OR UPDATE ON agriculture.formulation_version FOR EACH ROW EXECUTE FUNCTION agriculture.prevent_non_draft_formulation_mutation();
CREATE TRIGGER trg_formulation_line_protect_history BEFORE DELETE OR UPDATE ON agriculture.formulation_version_ingredient_line FOR EACH ROW EXECUTE FUNCTION agriculture.prevent_locked_formulation_line_mutation();
CREATE TRIGGER trg_governance_transition_append_only BEFORE DELETE OR UPDATE ON agriculture.governance_transition_log FOR EACH ROW EXECUTE FUNCTION agriculture.prevent_append_only_mutation();
CREATE TRIGGER trg_hypothesis_set_updated_at BEFORE UPDATE ON agriculture.hypothesis FOR EACH ROW EXECUTE FUNCTION agriculture.set_updated_at();
CREATE TRIGGER trg_ingredient_archive_only BEFORE DELETE ON agriculture.ingredient FOR EACH ROW EXECUTE FUNCTION agriculture.prevent_canonical_delete();
CREATE TRIGGER trg_ingredient_mutation_audit AFTER INSERT OR UPDATE ON agriculture.ingredient FOR EACH ROW EXECUTE FUNCTION agriculture.audit_canonical_mutation('ingredient_id');
CREATE TRIGGER trg_ingredient_set_updated_at BEFORE UPDATE ON agriculture.ingredient FOR EACH ROW EXECUTE FUNCTION agriculture.set_updated_at();
CREATE TRIGGER trg_input_validation_result_append_only BEFORE DELETE OR UPDATE ON agriculture.input_validation_result FOR EACH ROW EXECUTE FUNCTION agriculture.prevent_append_only_mutation();
CREATE TRIGGER trg_integrity_result_append_only BEFORE DELETE OR UPDATE ON agriculture.integrity_check_result FOR EACH ROW EXECUTE FUNCTION agriculture.prevent_append_only_mutation();
CREATE TRIGGER trg_knowledge_gap_archive_only BEFORE DELETE ON agriculture.knowledge_gap FOR EACH ROW EXECUTE FUNCTION agriculture.prevent_canonical_delete();
CREATE TRIGGER trg_knowledge_gap_mutation_audit AFTER INSERT OR UPDATE ON agriculture.knowledge_gap FOR EACH ROW EXECUTE FUNCTION agriculture.audit_canonical_mutation('knowledge_gap_id');
CREATE TRIGGER trg_learning_candidate_archive_only BEFORE DELETE ON agriculture.learning_candidate FOR EACH ROW EXECUTE FUNCTION agriculture.prevent_canonical_delete();
CREATE TRIGGER trg_learning_candidate_mutation_audit AFTER INSERT OR UPDATE ON agriculture.learning_candidate FOR EACH ROW EXECUTE FUNCTION agriculture.audit_canonical_mutation('learning_candidate_id');
CREATE TRIGGER trg_learning_candidate_requires_eligible_evidence BEFORE INSERT OR UPDATE OF brain_evidence_eligibility_id ON agriculture.learning_candidate FOR EACH ROW EXECUTE FUNCTION agriculture.validate_learning_candidate_eligibility();
CREATE TRIGGER trg_location_archive_only BEFORE DELETE ON agriculture.location FOR EACH ROW EXECUTE FUNCTION agriculture.prevent_canonical_delete();
CREATE TRIGGER trg_location_mutation_audit AFTER INSERT OR UPDATE ON agriculture.location FOR EACH ROW EXECUTE FUNCTION agriculture.audit_canonical_mutation('location_id');
CREATE TRIGGER trg_location_set_updated_at BEFORE UPDATE ON agriculture.location FOR EACH ROW EXECUTE FUNCTION agriculture.set_updated_at();
CREATE TRIGGER trg_measurement_protect_accepted_history BEFORE DELETE OR UPDATE ON agriculture.measurement FOR EACH ROW EXECUTE FUNCTION agriculture.prevent_measurement_mutation_after_observation_acceptance();
CREATE TRIGGER trg_mechanism_hypothesis_archive_only BEFORE DELETE ON agriculture.mechanism_hypothesis FOR EACH ROW EXECUTE FUNCTION agriculture.prevent_canonical_delete();
CREATE TRIGGER trg_mechanism_hypothesis_mutation_audit AFTER INSERT OR UPDATE ON agriculture.mechanism_hypothesis FOR EACH ROW EXECUTE FUNCTION agriculture.audit_canonical_mutation('mechanism_hypothesis_id');
CREATE TRIGGER trg_metric_definition_set_updated_at BEFORE UPDATE ON agriculture.metric_definition FOR EACH ROW EXECUTE FUNCTION agriculture.set_updated_at();
CREATE TRIGGER trg_observation_archive_only BEFORE DELETE ON agriculture.observation FOR EACH ROW EXECUTE FUNCTION agriculture.prevent_canonical_delete();
CREATE TRIGGER trg_observation_mutation_audit AFTER INSERT OR UPDATE ON agriculture.observation FOR EACH ROW EXECUTE FUNCTION agriculture.audit_canonical_mutation('observation_id');
CREATE TRIGGER trg_observation_protect_accepted_history BEFORE DELETE OR UPDATE ON agriculture.observation FOR EACH ROW EXECUTE FUNCTION agriculture.prevent_final_observation_mutation();
CREATE TRIGGER trg_observation_set_updated_at BEFORE UPDATE ON agriculture.observation FOR EACH ROW EXECUTE FUNCTION agriculture.set_updated_at();
CREATE TRIGGER trg_observation_template_set_updated_at BEFORE UPDATE ON agriculture.observation_template FOR EACH ROW EXECUTE FUNCTION agriculture.set_updated_at();
CREATE TRIGGER trg_operation_failure_append_only BEFORE DELETE OR UPDATE ON agriculture.operation_failure_event FOR EACH ROW EXECUTE FUNCTION agriculture.prevent_append_only_mutation();
CREATE TRIGGER trg_organization_archive_only BEFORE DELETE ON agriculture.organization FOR EACH ROW EXECUTE FUNCTION agriculture.prevent_canonical_delete();
CREATE TRIGGER trg_organization_mutation_audit AFTER INSERT OR UPDATE ON agriculture.organization FOR EACH ROW EXECUTE FUNCTION agriculture.audit_canonical_mutation('organization_id');
CREATE TRIGGER trg_organization_set_updated_at BEFORE UPDATE ON agriculture.organization FOR EACH ROW EXECUTE FUNCTION agriculture.set_updated_at();
CREATE TRIGGER trg_outcome_archive_only BEFORE DELETE ON agriculture.outcome FOR EACH ROW EXECUTE FUNCTION agriculture.prevent_canonical_delete();
CREATE TRIGGER trg_outcome_mutation_audit AFTER INSERT OR UPDATE ON agriculture.outcome FOR EACH ROW EXECUTE FUNCTION agriculture.audit_canonical_mutation('outcome_id');
CREATE TRIGGER trg_photo_analysis_archive_only BEFORE DELETE ON agriculture.photo_analysis FOR EACH ROW EXECUTE FUNCTION agriculture.prevent_canonical_delete();
CREATE TRIGGER trg_photo_analysis_mutation_audit AFTER INSERT OR UPDATE ON agriculture.photo_analysis FOR EACH ROW EXECUTE FUNCTION agriculture.audit_canonical_mutation('photo_analysis_id');
CREATE TRIGGER trg_photo_evidence_archive_only BEFORE DELETE ON agriculture.photo_evidence FOR EACH ROW EXECUTE FUNCTION agriculture.prevent_canonical_delete();
CREATE TRIGGER trg_photo_evidence_mutation_audit AFTER INSERT OR UPDATE ON agriculture.photo_evidence FOR EACH ROW EXECUTE FUNCTION agriculture.audit_canonical_mutation('photo_evidence_id');
CREATE TRIGGER trg_photo_validation_result_append_only BEFORE DELETE OR UPDATE ON agriculture.photo_validation_result FOR EACH ROW EXECUTE FUNCTION agriculture.prevent_append_only_mutation();
CREATE TRIGGER trg_plot_archive_only BEFORE DELETE ON agriculture.plot FOR EACH ROW EXECUTE FUNCTION agriculture.prevent_canonical_delete();
CREATE TRIGGER trg_plot_mutation_audit AFTER INSERT OR UPDATE ON agriculture.plot FOR EACH ROW EXECUTE FUNCTION agriculture.audit_canonical_mutation('plot_id');
CREATE TRIGGER trg_plot_set_updated_at BEFORE UPDATE ON agriculture.plot FOR EACH ROW EXECUTE FUNCTION agriculture.set_updated_at();
CREATE TRIGGER trg_provenance_assertion_append_only BEFORE DELETE OR UPDATE ON agriculture.provenance_assertion FOR EACH ROW EXECUTE FUNCTION agriculture.prevent_append_only_mutation();
CREATE TRIGGER trg_record_governance_state_set_updated_at BEFORE UPDATE ON agriculture.record_governance_state FOR EACH ROW EXECUTE FUNCTION agriculture.set_updated_at();
CREATE TRIGGER trg_memory_entry_append_only BEFORE DELETE ON agriculture.scientific_memory_entry FOR EACH ROW EXECUTE FUNCTION agriculture.prevent_append_only_mutation();
CREATE TRIGGER trg_memory_requires_active_approved_learning BEFORE INSERT ON agriculture.scientific_memory_entry FOR EACH ROW EXECUTE FUNCTION agriculture.validate_memory_source();
CREATE TRIGGER trg_trial_archive_only BEFORE DELETE ON agriculture.trial FOR EACH ROW EXECUTE FUNCTION agriculture.prevent_canonical_delete();
CREATE TRIGGER trg_trial_mutation_audit AFTER INSERT OR UPDATE ON agriculture.trial FOR EACH ROW EXECUTE FUNCTION agriculture.audit_canonical_mutation('trial_id');
CREATE TRIGGER trg_trial_set_updated_at BEFORE UPDATE ON agriculture.trial FOR EACH ROW EXECUTE FUNCTION agriculture.set_updated_at();
CREATE TRIGGER trg_variety_archive_only BEFORE DELETE ON agriculture.variety FOR EACH ROW EXECUTE FUNCTION agriculture.prevent_canonical_delete();
CREATE TRIGGER trg_variety_mutation_audit AFTER INSERT OR UPDATE ON agriculture.variety FOR EACH ROW EXECUTE FUNCTION agriculture.audit_canonical_mutation('variety_id');
CREATE TRIGGER trg_variety_set_updated_at BEFORE UPDATE ON agriculture.variety FOR EACH ROW EXECUTE FUNCTION agriculture.set_updated_at();
